tracim/tracim

- tracim/tracim/model/data.py
- tracim/tracim/model/serializers.py
http://tracim.org/workspaces/4/folders/5/threads/129
> fixes bug #129 - Some request hang

- tracim/tracim/templates/workspace/getone.mak
See  http://tracim.org/workspaces/4/folders/5/threads/140
> fixes bug #140 - Contributor of a workspace gets a error 500 on workspace view

- tracim/tracim/controllers/admin/user.py
- tracim/tracim/controllers/admin/workspace.py
- tracim/tracim/controllers/workspace.py
- tracim/tracim/lib/content.py
- tracim/tracim/lib/helpers.py
- tracim/tracim/lib/userworkspace.py
- tracim/tracim/lib/workspace.py
- tracim/tracim/model/auth.py
- tracim/tracim/model/data.py
- tracim/tracim/model/serializers.py
- tracim/tracim/public/assets/css/dashboard.css
- tracim/tracim/templates/admin/user_getone.mak
- tracim/tracim/templates/admin/workspace_getone.mak
- tracim/tracim/templates/file/getone.mak
- tracim/tracim/templates/home.mak
- tracim/tracim/templates/page/getone.mak
- tracim/tracim/templates/thread/getone.mak
- tracim/tracim/templates/user_get_me.mak
- tracim/tracim/templates/user_workspace_widgets.mak
- tracim/tracim/templates/widgets/paragraph.mak
- tracim/tracim/templates/widgets/table_row.mak
- tracim/tracim/tests/library/test_content_api.py
- tracim/tracim/tests/library/test_helpers.py
- show full history on pages and files
- add ActionDescription.MOVE for folder-move related events 
- clean code (remove debug traces)
> show full history on pages and files

- tracim/migration/versions/43a323cc661_add_read_not_read_content_status.py
- tracim/tracim/controllers/__init__.py
- tracim/tracim/controllers/content.py
- tracim/tracim/controllers/root.py
- tracim/tracim/lib/content.py
- tracim/tracim/lib/user.py
- tracim/tracim/model/data.py
- tracim/tracim/model/serializers.py
- tracim/tracim/public/assets/css/dashboard.css
- tracim/tracim/templates/file/toolbar.mak
- tracim/tracim/templates/home.mak
- tracim/tracim/templates/page/toolbar.mak
- tracim/tracim/templates/thread/toolbar.mak
- tracim/tracim/templates/user_toolbars.mak
- tracim/tracim/templates/user_workspace_widgets.mak
- tracim/tracim/templates/widgets/button.mak
- tracim/tracim/tests/__init__.py
- tracim/tracim/tests/library/test_serializers.py
This new feature requires a dabase model upgrade with the following command :
> gearbox migrate upgrade
See http://turbogears.readthedocs.org/en/latest/turbogears/migrations.html
> add content read/not read status for each user. 

- .travis.yml
- install/requirements.txt
- tracim/tracim/tests/__init__.py
Just 2 little fix:
* backlash version compatibility with TurboGears 2.3.7
* fix in tests (see #3800083)
> Little fixes

- .travis.yml
- tracim/development.ini.base
- tracim/tracim/model/__init__.py
Mysql compatibility + test postgres and mysql in travis.
About sqlite: https://bitbucket.org/zzzeek/alembic/issues/325/dropping-columns-in-sqlite
> Mysql + Postgres compatibility

- install/requirements.txt
- tracim/tracim/config/app_cfg.py
- tracim/tracim/controllers/root.py
- tracim/tracim/lib/utils.py
Fixed with ugly patch. Not found how to do properly !
> Fix reset password issue

- tracim/tracim/templates/folder/getone.mak
- tracim/tracim/templates/home.mak
- tracim/tracim/templates/widgets/button.mak
- tracim/tracim/templates/widgets/table_row.mak
- tracim/tracim/templates/widgets/ui.mak
- tracim/tracim/templates/workspace/getone.mak
Improve user interface : 
- better design for webdav config block in workspace screen
- add some explanation about webdav
- improve filtering view tools on folder 1and workspace views
> Several user interface improvements

- .gitignore
- tracim/development.ini.base
- tracim/tracim/config/app_cfg.py
- tracim/tracim/controllers/content.py
- tracim/tracim/controllers/page.py
3 parameters require careful review:
- `cache_dir`
- `preview_cache_dir`
- `depot_storage_dir`
> Parameters the storage path of files depot.

- tracim/tracim/templates/master_anonymous.mak
- tracim/tracim/templates/master_authenticated.mak
- tracim/tracim/templates/master_no_toolbar_no_login.mak
> Puts language code between simple quotes

- tracim/tracim/templates/folder/getone.mak
This allows to view archived or deleted content in apparently empty
folders containing only archived or deleted content.
Closes #277
> Enables filter for empty folder

- tracim/tracim/lib/notifications.py
> Fixes email notification that disappears silently

- tracim/tracim/lib/userworkspace.py
- tracim/tracim/tests/library/test_workspace.py
Function tested:
tracim/tracim/lib/workspace.py:WorkspaceApi.get_notifiable_roles
lebouquetin@8c23f0a has closed #168
> Tests getting notifiable roles

- tracim/tracim/lib/notifications.py
> Fills the status update notification

- tracim/tracim/config/app_cfg.py
> Raises exception if no preview cache dir in conf

- tracim/tracim/templates/calendar/config.mak
- tracim/tracim/templates/pod.mak
- TinyMCE
- CalDavZAP
Closes #321
> Fixes front end translation language code variables

- tracim/tracim/controllers/page.py
> Names properly exported PDF files

- tracim/tracim/i18n/en/LC_MESSAGES/tracim.po
> Translates in English explicitly

- install/requirements.txt
- tracim/tracim/controllers/admin/workspace.py
- tracim/tracim/lib/userworkspace.py
- tracim/tracim/tests/library/test_workspace.py
> Fixes role api notification parameter type issue

- .travis.yml
- install/requirements.txt
- tracim/tracim/i18n/en/LC_MESSAGES/tracim.po
- tracim/tracim/model/data.py
> Orders content revisions by updated date

- doc/setting.md
> Rewrites LDAP documentation first line

- README.md
> Creates a python3 virtual environment in readme

- README.md
> Reviews path of 'gearbox' calls in readme file

- README.md
> Documents only one way to run Tracim in readme

- tracim/tracim/templates/calendar/config.mak
- tracim/tracim/templates/pod.mak
> Fixes front end language management

- README.md
Closes #260
Do not merge for the moment, the [algoo/tracim docker image](https://hub.docker.com/r/algoo/tracim/) is to be updated.
> Documents running the docker image

- doc/nginx.md
> Documents nginx/uWSGI configuration

- tracim/tracim/i18n/fr/LC_MESSAGES/tracim.po
Additionnaly fixes various errors in translation
> Translates "read mode" in french

- tracim/tracim/model/serializers.py
- tracim/tracim/templates/admin/user_getone.mak
> Drops deleted workspace roles from /admin/users/

- tracim/tracim/i18n/fr/LC_MESSAGES/tracim.po
> Translates 'restore' in french

- README.md
> Fixes running Tracim via docker

- tracim/tracim/i18n/fr/LC_MESSAGES/tracim.po
- tracim/tracim/templates/admin/user_getall.mak
- tracim/tracim/templates/admin/workspace_getall.mak
> Writes 2 labels with capitalized first letters

- tracim/tracim/lib/webdav/design.py
> Adds UTF-8 charset markup to WebDAV pages/threads

- tracim/tracim/i18n/fr/LC_MESSAGES/tracim.po
- tracim/tracim/templates/file/getone.mak
- Drops duplicate "le" grammar article in french translation,
- Replaces created_localized by updated_localized.
Closes #286
> Fixes "modified at" metadata of file contents

- install/requirements.txt
- tracim/tracim/tests/functional/test_ldap_restrictions.py
- tracim/tracim/tests/functional/test_root.py
Updates beautifulsoup4 python package as well.
Closes #223
> Uses BeautifulSoup with an explicit HTML parser

- install/requirements.txt
- tracim/tracim/lib/daemons.py
> Uses upstream WsgiDAV

- tracim/setup.py
> Drops preview generator installation from GitHub

- doc/database.md
> Uses UTF8 as MySQL character set

- tracim/tracim/controllers/workspace.py
- tracim/tracim/templates/workspace/getone.mak
Use 'https' and 'davs' in dav url when WEBSITE_BASE_URL is set with https scheme.
> Https compat

- tracim/tracim/lib/daemons.py
- tracim/tracim/lib/utils.py
Force https (when tracim use https) into wsgi.urlscheme to avoid trouble with wsgidav, see https://github.com/tracim/tracim/issues/538
> Fix wsgidav https "move" problem.

- README.md
Amélioration de la documentation pour le démarrage d'une image Docker de Tracim.
> Docker: documentation update

- doc/webdav.md
Add doc to solve webdav windows issues link to default windows config.
> better_webdav_doc

- CONTRIBUTING.md
- DCO
- LICENSE
- README.md
> add legal stuff

- backend/development.ini.sample
> remove sqlalchemy.url param for alembic section, use same as tracim

- backend/tracim_backend/lib/core/content.py
- backend/tracim_backend/tests/functional/test_contents.py
- backend/tracim_backend/views/contents_api/folder_controller.py
> correct exception behaviour for same content for folder content

- backend/tracim_backend/views/core_api/schemas.py
> set all param as required for content update

- backend/development.ini.sample
- backend/doc/setting.md
- backend/tests_configs.ini
- backend/tracim_backend/__init__.py
- backend/tracim_backend/config.py
- backend/tracim_backend/tests/functional/test_session.py
related to #1160
only tracim_backend part, docker part should be done later.
> Fix/1160 modify some development.ini behaviour: allow disable api key

- backend/tracim_backend/tests/functional/test_user.py
- backend/tracim_backend/views/core_api/schemas.py
> allow none value for password at user creation

- backend/tracim_backend/lib/core/user.py
- backend/tracim_backend/tests/functional/test_user.py
> fix issue with updating email/password of non internal user

- backend/doc/migrate_from_v1.md
> fix doc about ldap and migration

- backend/tracim_backend/tests/functional/test_system.py
- backend/tracim_backend/views/core_api/system_controller.py
related  to #1270,
this create new problem here : #1278
> allow access to config for unauthenticated user

- frontend/src/container/Login.jsx
this pr REQUIRES https://github.com/tracim/tracim/pull/1279 to be merged
> [#1270] login page now get config before user login

- tools_docker/Debian_Uwsgi/common.sh
- tools_docker/Debian_Uwsgi/entrypoint.sh
- tools_docker/Debian_Uwsgi/uwsgi.ini.sample
Add condition to upgrade database if initialization of database is not necessary.
Add parameter in wsgi file for lock with webddav.
> #1300 fix missing condition in entrypoint

- backend/doc/cli.md
> fix wrong command in documentation about tracimcli user

- backend/requirements.txt
- backend/setup.py
> add requests to global dependencies

- backend/doc/migrate_from_v1.md
- backend/tracim_backend/migration/versions/354d62d490ad_remove_page_slug_from_properties.py
- backend/tracim_backend/migration/versions/f889c2b59759_remove_page_slug_from_content_revision_.py
related to #1299.
need to be verified on all databases supported (actually check is done only on postgres) and with better database sample.
> add migrations script to replace all page slug to html-document

- backend/doc/webdav.md
related to #1165 
Replace webdav documentation file from tracim v1.
> WIP: replace old user webdav doc from v1

- backend/tracim_backend/lib/mail_notifier/notifier.py
- backend/tracim_backend/lib/mail_notifier/sender.py
> dont return smtp connection ok when its false + better logs

- backend/tracim_backend/lib/utils/utils.py
- backend/tracim_backend/lib/webdav/resources.py
- backend/tracim_backend/tests/functional/test_webdav.py
> Fix convert file_name and webdav label for webdav

- frontend/src/container/Dashboard.jsx
https://github.com/tracim/tracim/issues/1353
> [#1353] removed folder create btn from dashboard for contributor

- frontend_app_file/i18next.scanner/en/translation.json
- frontend_app_file/i18next.scanner/fr/translation.json
- frontend_app_file/src/container/File.jsx
- frontend_app_html-document/i18next.scanner/en/translation.json
- frontend_app_html-document/i18next.scanner/fr/translation.json
- frontend_app_html-document/src/container/HtmlDocument.jsx
- frontend_app_thread/i18next.scanner/en/translation.json
- frontend_app_thread/i18next.scanner/fr/translation.json
- frontend_app_thread/src/container/Thread.jsx
https://github.com/tracim/tracim/issues/1360
> [#1360] better error handling when changing title on all apps

- frontend/src/container/ForgotPassword.jsx
- frontend/src/container/Login.jsx
https://github.com/tracim/tracim/issues/1289
> [#1289] move handling of error 2049 when ldap user try to reset pw

- frontend_lib/src/component/PopinFixed/PopinFixedHeader.jsx
https://github.com/tracim/tracim/issues/1360
change to frontend_lib that requires a full rebuild of frontend
> [#1360] apps display original title after a save error

- backend/tracim_backend/models/data.py
- backend/tracim_backend/tests/models/test_content.py
> fix children function in content model

- README_translation.md
Added some intel regarding this issue: https://github.com/tracim/tracim/issues/1045
This PR **doesn't** solve the issue above
> added important notice about frontend translation keys

- frontend_app_file/i18next.scanner/en/translation.json
- frontend_app_file/i18next.scanner/fr/translation.json
- frontend_app_file/src/component/FileComponent.jsx
- frontend_app_folder_advanced/i18next.scanner/en/translation.json
- frontend_app_folder_advanced/i18next.scanner/fr/translation.json
- frontend_app_folder_advanced/src/component/FolderAdvanced.jsx
- frontend_app_folder_advanced/src/container/FolderAdvanced.jsx
- frontend_app_html-document/i18next.scanner/en/translation.json
- frontend_app_html-document/i18next.scanner/fr/translation.json
- frontend_app_html-document/src/component/DisplayState.jsx
- frontend_app_html-document/src/component/HtmlDocument.jsx
- frontend_app_html-document/src/container/HtmlDocument.jsx
- frontend_app_html-document/src/css/index.styl
- frontend_app_html-document/src/helper.js
- frontend_app_workspace_advanced/i18next.scanner/en/translation.json
- frontend_app_workspace_advanced/i18next.scanner/fr/translation.json
- frontend_app_workspace_advanced/src/container/WorkspaceAdvanced.jsx
- frontend_lib/i18next.scanner/en/translation.json
- frontend_lib/i18next.scanner/fr/translation.json
- frontend_lib/src/component/Timeline/Timeline.jsx
https://github.com/tracim/tracim/issues/1373
> Fix/1373  add msg about available draft

- tools_docker/Debian_Uwsgi/uwsgi.ini.sample
Add socket-timeout value (fix timeout when upload file)
#1438
> [#1438] add socket-timeout value for docker image

- changelog.md
> [#1445] changelog translation

- backend/development.ini.sample
> Restore allowed/restricted dim params

- .travis.yml
- backend/README.md
- backend/requirements.txt
- backend/setup.py
- setup_default_backend.sh
- tools_docker/Debian_Uwsgi/Dockerfile
related to #1472 
TODO : 
- ~~Check docker image~~ https://github.com/tracim/tracim/issues/1482
> Fix/1472  update preview generator to 0.10

- backend/requirements.txt
- backend/setup.py
- backend/tracim_backend/extensions.py
- backend/tracim_backend/views/errors.py
> Fix/1493 hapic 0.73 support

- backend/doc/cli.md
- backend/tracim_backend/__init__.py
- backend/tracim_backend/app_models/validator.py
- backend/tracim_backend/config.py
- backend/tracim_backend/exceptions.py
- backend/tracim_backend/lib/calendar/__init__.py
- backend/tracim_backend/lib/calendar/authorization.py
- backend/tracim_backend/lib/calendar/calendar.py
- backend/tracim_backend/lib/core/application.py
- backend/tracim_backend/lib/proxy/proxy.py
- backend/tracim_backend/models/context_models.py
- backend/tracim_backend/tests/functional/test_caldav.py
- backend/tracim_backend/tests/library/test_application_api.py
- backend/tracim_backend/views/calendar_api/calendar_controller.py
- backend/tracim_backend/views/core_api/schemas.py
related to #1527 
another fix : 
- fix calendar slug app (for frontend compatibility).
+ fix needed for branche radicale but not commited (caldavzap commited without last change)
to commit into radicale branch
> Fix/1527 do not return calendar app in sidebar if workspace calendar is disabled + Others fix for calendar features

- backend/tracim_backend/config.py
> correct slug for caldavzap app in default_enabled_app

- backend/development.ini.sample
Change some wrong syntaxe in development.ini.sample . Write with @lebouquetin .
> fix syntaxe about size preview information

- backend/tracim_backend/tests/functional/test_caldav.py
- backend/tracim_backend/views/calendar_api/radicale_proxy_controller.py
> Fix radicale proxy path issue between thunderbird and caldavzap behaviour.

- frontend/src/container/Tracim.jsx
- functionnal_tests/cypress/integration/app_html-document/tiny_mce__can_type_content_spec.js
https://github.com/tracim/tracim/issues/1563
> [#1563] content opened after creation is now always the proper one

- frontend_app_file/src/container/File.jsx
- frontend_app_html-document/src/container/HtmlDocument.jsx
- frontend_app_thread/src/container/Thread.jsx
https://github.com/tracim/tracim/issues/1105
> [#1105] handled error code 2041 to not display because anything changed

- frontend_app_file/src/container/File.jsx
- frontend_app_html-document/src/container/HtmlDocument.jsx
- frontend_app_thread/src/container/Thread.jsx
https://github.com/tracim/tracim/issues/1067
> [#1067] avoid creating new revision when switching apps status to the same one

- backend/README.md
- backend/update_i18n_json_file.sh
- setup_default_backend.sh
- tools_docker/Debian_Uwsgi/Dockerfile
related to #1565
Fix impossibility to build docker image => missing library for pg_config
> [#1565] fix missing library for pg_config

- backend/tracim_backend/lib/agenda/authorization.py
- backend/tracim_backend/lib/agenda/determiner.py
- backend/tracim_backend/lib/agenda/utils.py
- backend/tracim_backend/tests/functional/test_caldav.py
- backend/tracim_backend/views/agenda_api/radicale_proxy_controller.py
related to #1584 
need https://github.com/tracim/tracim/pull/1578 .
Tested with caldavzap.
Todo:
> Fix/1584  better right access mecanism for caldav agenda

- frontend/src/container/Tracim.jsx
https://github.com/tracim/tracim/issues/1374
> [#1374] save default user language if none in db

- frontend/dist/assets/_caldavzap/config.tracim.js
- frontend/dist/assets/_caldavzap/main.js
- frontend/src/container/AppFullscreenRouter.jsx
- frontend_app_agenda/src/container/Agenda.jsx
https://github.com/tracim/tracim/issues/1600
> [#1600] always display sidebar caldavzap on page for all agendas

- frontend/dist/assets/_caldavzap/index.tracim.html
https://github.com/tracim/tracim/issues/1608
tiny PR to change icon
> [#1608] changed caldavzap fullscreen icon

- frontend_app_calendar/src/css/index.styl
https://github.com/tracim/tracim/issues/1605
> [#1605] removed folder frontend_app_calendar

- frontend/src/action-creator.async.js
- frontend/src/component/Dashboard/AgendaInfo.jsx
- frontend/src/component/Dashboard/AgendaInfo.styl
- frontend/src/container/Dashboard.jsx
- frontend/src/container/Tracim.jsx
https://github.com/tracim/tracim/issues/1610
> [#1610] small various bugfix

- frontend/dist/assets/_caldavzap/main.js
- frontend/src/component/Header/MenuActionListItem/AdminLink.jsx
https://github.com/tracim/tracim/issues/1621
> [#1621] fixed 2 font awesome icons

- backend/pyproject.toml
- backend/setup.cfg
Note: This MR does not need green pipelines.
> add static tools config

- .travis.yml
Still no pipelines ...  idon't understand.
> Add static checks on pipelines

- .travis.yml
- backend/setup.cfg
related to #1634
this fix also #1026 and #1453
> Feature/1634  better travis ci file

- frontend/src/component/Dashboard/RecentActivity.jsx
- frontend/src/component/Dashboard/RecentActivity.styl
- frontend/src/container/Dashboard.jsx
https://github.com/tracim/tracim/issues/1641
> [#1641] added html link feature to recent activity in dashboard

- frontend_app_file/src/css/index.styl
https://github.com/tracim/tracim/issues/1624
> [#1624] fix app file height

- backend/tracim_backend/lib/mail_notifier/notifier.py
- backend/tracim_backend/locale/fr/LC_MESSAGES/tracim_backend.po
- backend/tracim_backend/templates/mail/content_update_body_html.mak
- backend/tracim_backend/templates/mail/created_account_body_html.mak
- backend/tracim_backend/templates/mail/reset_password_body_html.mak
> Fix/1649  better escaping for email

- frontend/src/container/Header.jsx
https://github.com/tracim/tracim/issues/1644
> [#1644] fixed btn agenda sometimes displayed when unlogged

- backend/tracim_backend/lib/core/content.py
- backend/tracim_backend/models/context_models.py
- backend/tracim_backend/models/data.py
- backend/tracim_backend/tests/library/test_content_api.py
related to #1652.
:warning: need  #1653
> Fix/1652  copy preserving id order

- backend/development.ini.sample
> [#1665] change syntaxe and add available parameter [ci skip]

- frontend/src/container/Login.jsx
https://github.com/tracim/tracim/issues/1679
> [#1679] fix test value of cookie in login.jsx

- backend/tracim_backend/lib/mail_notifier/notifier.py
- backend/tracim_backend/templates/mail/created_account_body_html.mak
> remove double escaping for password in email creation template

- tools_docker/Debian_Uwsgi/entrypoint.sh
> [#1681] fix wrong sed about webdav and caldav in apache config file

- backend/tracim_backend/templates/mail/content_update_body_html.mak
> fix url of comments in mails

- backend/development.ini.sample
- backend/tracim_backend/views/frontend.py
- frontend/dist/index.mak
> Use website title config as website title

- backend/setup.py
> remove TestTracimCommand

- backend/tracim_backend/lib/agenda/agenda.py
related to #1700
description here: https://github.com/tracim/tracim/issues/1700#issuecomment-491235727
> Fix/1700  fix agenda creation methods

- frontend/dist/assets/tracim/tinymceInit.js
- frontend/src/css/Generic.styl
- frontend_app_html-document/src/component/HtmlDocument.jsx
- frontend_app_html-document/src/css/index.styl
https://github.com/tracim/tracim/issues/1693
> [#1693] fix 2 bugs in html document

- frontend/src/container/Header.jsx
- frontend/src/css/Header.styl
https://github.com/tracim/tracim/issues/1074
> [#1074] change two breakpoints and add a padding

- frontend_app_file/src/container/File.jsx
- frontend_app_html-document/src/container/HtmlDocument.jsx
- frontend_lib/src/component/PopinFixed/PopinFixedContent.jsx
https://github.com/tracim/tracim/issues/1686
> [#1686] timeline now never closes on load

- frontend/src/css/Header.styl
https://github.com/tracim/tracim/issues/1074
> [#1074] add a margin to the buttons of small screens

- frontend_app_file/src/css/index.styl
- frontend_app_html-document/src/css/index.styl
- frontend_lib/src/component/PopinFixed/PopinFixed.styl
https://github.com/tracim/tracim/issues/1718
> [#1718] change popinfixed configuration for screens smaller than lg

- frontend/i18next.scanner/en/translation.json
- frontend/i18next.scanner/fr/translation.json
- frontend/src/container/Header.jsx
> [#1723] add plural for agenda button in header

- frontend/src/css/Login.styl
https://github.com/tracim/tracim/issues/1602 see last comment
> [#1602] added max-width to login page card

- frontend/src/css/Workspace.styl
- frontend_lib/src/component/Breadcrumbs/Breadcrumbs.styl
https://github.com/tracim/tracim/issues/1726
> [#1726] fix breadcrumbs responsive design and centered the create button

- frontend/dist/assets/tracim/tinymceInit.js
- frontend_app_file/src/css/index.styl
- frontend_app_html-document/src/css/index.styl
- frontend_lib/src/component/PopinFixed/PopinFixed.styl
https://github.com/tracim/tracim/issues/1693
> [#1693] Change the editor height after resize

- frontend/src/component/Home/Home.styl
- frontend/src/css/Workspace.styl
https://github.com/tracim/tracim/issues/1726
> [#1726] change what button is centered

- frontend/dist/assets/tracim/tinymceInit.js
https://github.com/tracim/tracim/issues/1693
> [#1693] making sure that the resize is only during fullsize screen

- frontend_lib/i18next.scanner/en/translation.json
- frontend_lib/i18next.scanner/fr/translation.json
- frontend_lib/src/component/PopinFixed/PopinFixedHeader.jsx
https://github.com/tracim/tracim/issues/1516
> [#1516] button added to undo changes in the title

- frontend/src/component/Login/FooterLogin.jsx
- frontend/src/container/Sidebar.jsx
- frontend/src/css/Login.styl
- frontend/src/css/Sidebar.styl
https://github.com/tracim/tracim/issues/1514
> [#1514] change card z-index to be bigger then copyright

- setup_default_backend.sh
> create a default radicale storage dir

- tools_docker/Debian_Uwsgi/Dockerfile
- tools_docker/Debian_Uwsgi/common.sh
- tools_docker/README.md
> fix frontend_app_agenda path for dockerfile cleanup

- frontend/src/container/Tracim.jsx
> Fix an error in redirection after a 401 causing cypress to crash

- backend/development.ini.sample
- frontend_lib/src/component/Timeline/Revision.jsx
Its to create release_02.02.00_rc4 for test.
> New Release candidate (rc4)

- frontend/src/component/FlashMessage.styl
https://github.com/tracim/tracim/issues/1758
> [#1758] change the parent div width for a margin left

- frontend_app_file/i18next.scanner/en/translation.json
- frontend_app_file/i18next.scanner/fr/translation.json
- frontend_app_file/src/component/FileComponent.jsx
- frontend_app_file/src/container/File.jsx
- frontend_app_file/src/css/index.styl
- frontend_app_html-document/i18next.scanner/en/translation.json
- frontend_app_html-document/i18next.scanner/fr/translation.json
- frontend_app_html-document/src/component/HtmlDocument.jsx
- frontend_app_html-document/src/container/HtmlDocument.jsx
- frontend_app_thread/src/container/Thread.jsx
- frontend_lib/i18next.scanner/en/translation.json
- frontend_lib/i18next.scanner/fr/translation.json
- frontend_lib/src/component/DisplayState/DisplayState.jsx
- frontend_lib/src/component/DisplayState/DisplayState.styl
- frontend_lib/src/component/Timeline/Timeline.jsx
- frontend_lib/src/component/Timeline/Timeline.styl
- frontend_lib/src/index.js
- functionnal_tests/cypress/integration/app_html-document/operation_allcontent_delete_html-document.js
- functionnal_tests/cypress/integration/app_thread/operation_allcontent_delete_thread.js
https://github.com/tracim/tracim/issues/1743
> [wip] [#1743] add a message in all deprecated contents and its translations (tracim 2.3 maybe 2.2)

- frontend/src/css/Header.styl
https://github.com/tracim/tracim/issues/1802
(there was not FIXME, TODO, NOTE or HACK in this code part)
> [#1802] change header height to be min 61px

- frontend_app_admin_workspace_user/src/component/AdminWorkspace.jsx
- frontend_app_admin_workspace_user/src/css/index.styl
https://github.com/tracim/tracim/issues/1781
> [#1781] limiting description and title width in Administration

- functionnal_tests/cypress/support/urls_commands.js
#1826 First part of the issue adds `urls_commands`
> cypress - adds 2 new functions to work with urls in cypress

- frontend_app_file/src/container/File.jsx
- frontend_app_html-document/src/container/HtmlDocument.jsx
- frontend_app_thread/src/container/Thread.jsx
*Just FIXME comments to make the code clear for the https://github.com/tracim/tracim/issues/1840*
> [#1840] FIXME comments

- tools_docker/Debian_Uwsgi/common.sh
> create required folders to start tracim [skip ci]

- frontend_app_admin_workspace_user/src/css/index.styl
*https://github.com/tracim/tracim/issues/1781*
> [#1781] add max-width for ellipsis to work

- frontend/src/container/Header.jsx
- frontend/src/css/Header.styl
> Allows middle click on agendas button

- frontend/src/container/Sidebar.jsx
- frontend/src/helper.js
- frontend/src/version.json
> front [skip ci pytest] - adds the frontend version in the sidebar

- tools_docker/Debian_Uwsgi/apache2.conf.sample
related to #1734 
We need to verify docker builded with this work properly and fix the issue.
> use proxy_sendcl in apache sample used for docker

- frontend/src/component/FlashMessage.styl
https://github.com/tracim/tracim/issues/1843
> [#1843] change width warning at small screens

- frontend_lib/src/component/DisplayState/DisplayState.styl
*https://github.com/tracim/tracim/issues/1743*
> [#1743] remove link from deprecated warning

- frontend/src/container/SearchResult.jsx
> [#1904] changing path separators

- backend/cypress_test.ini
- backend/development.ini.sample
- backend/doc/setting.md
- backend/tracim_backend/config.py
> remove website.server_name

- backend/tracim_backend/config.py
- backend/tracim_backend/migration/env.py
> Fix/1812 make sqlalchemy  url mandatory

- frontend_app_folder_advanced/src/css/index.styl
> [#1918] change width inside content page (maybe tracim 2.3)

- frontend/src/component/DragHandle.jsx
- frontend/src/component/DragHandle.styl
- frontend/src/component/Workspace/ContentItem.jsx
- frontend/src/component/Workspace/Folder.jsx
- frontend/src/container/WorkspaceContent.jsx
- frontend/src/css/ContentItem.styl
- frontend_lib/src/component/ListItemWrapper/ListItemWrapper.jsx
*Please indicate here a summary of pull request content or if related issue exist, please indicate issue reference here*
> fix drag and drop for firefox linux

- frontend/src/container/SearchResult.jsx
- frontend/src/container/WorkspaceContent.jsx
> Change breadcrumbs translation and empty search

- frontend/src/container/WorkspaceContent.jsx
Contents would not be seen as read.
> fix content do not update read status

- frontend/src/css/Generic.styl
- frontend/src/css/Tracim.styl
> [#1939] change overflow-y to auto

- frontend_app_file/src/container/File.jsx
- frontend_app_html-document/src/container/HtmlDocument.jsx
- frontend_app_thread/src/container/Thread.jsx
> Fix error with apiresponse and standardjs

- frontend/src/component/Header/Search.styl
> [#1926] changing search input width in lg screens

- backend/tracim_backend/locale/fr/LC_MESSAGES/tracim_backend.po
> Update french translations

- frontend/src/container/Login.jsx
https://github.com/tracim/tracim/issues/1958
> [#1958] fix workspace member list loading after right a connection

- backend/doc/migrate_from_v1.md
> [#1852] add documentation about migration of agenda from v1 to v2

- frontend/package.json
- frontend/src/action-creator.async.js
- frontend/src/action-creator.sync.js
- frontend/src/container/Header.jsx
- frontend/src/container/SearchResult.jsx
- frontend/src/reducer/searchResult.js
> [#1955] filter to unique results at search

- frontend/src/component/ContentItemSearch.jsx
- frontend/src/container/SearchResult.jsx
> [#1962] changing search tooltips of modification date

- tools_docker/Debian_Uwsgi/entrypoint.sh
- tools_docker/README.md
> [#1965] create file in existing folder. folder created by common.sh script

- frontend/src/component/Workspace/Folder.styl
> [#1970] align folders name inside a list

- frontend/i18next.scanner/en/translation.json
- frontend/i18next.scanner/fr/translation.json
- frontend_app_admin_workspace_user/src/component/AdminUser.jsx
- frontend_app_admin_workspace_user/src/css/index.styl
- frontend_lib/src/component/NewMemberForm/NewMemberForm.jsx
- frontend_lib/src/component/NewMemberForm/NewMemberForm.styl
> [#1964] adding warning translation and changing email icon

- .github/pull_request_template.md
> Enough is Enoug, typo issue in git PR template

- frontend/src/action-creator.async.js
https://github.com/tracim/tracim/issues/1923
> [#1923] add url encode to search keywords of the search request

- frontend/src/container/WorkspaceContent.jsx
https://github.com/tracim/tracim/issues/1974
> [#1974] change flash msg or error in move to type danger (red)

- frontend/src/css/Dashboard.styl
> [#1981] changing position and width of Advanced Dashboard button

- frontend_app_folder_advanced/src/container/FolderAdvanced.jsx
- frontend_lib/src/customEvent.js
…tent list
https://github.com/tracim/tracim/issues/1977
> Fix/1977  changin folder subcontent reload workspace content list

- frontend/i18next.scanner/en/translation.json
- frontend/i18next.scanner/fr/translation.json
- frontend/src/component/Workspace/ContentItem.jsx
- frontend/src/component/Workspace/Folder.jsx
> [#1983] changing content item tooltips at shared space

- frontend/src/css/Dashboard.styl
- frontend/src/css/Generic.styl
> [#1981] changing Advanced Dashboard button position

- frontend/src/css/Header.styl
> [#1972] adding margin-bottom at xs screens

- frontend/i18next.scanner/en/translation.json
- frontend/i18next.scanner/fr/translation.json
- frontend/src/container/SearchResult.jsx
> [#1990] changing search message and its translation

- backend/tracim_backend/lib/core/system.py
- changelog.md
- frontend/src/version.json
> [#1838] update version of tracim backend and frontend

- frontend_app_file/src/css/index.styl
> [#1992] deleting not necessaries commands and changing the file height

- frontend/src/reducer/currentWorkspace.js
> [#1774] adding file extension at recent activity reducer

- frontend_app_admin_workspace_user/i18next.scanner/en/translation.json
- frontend_app_admin_workspace_user/i18next.scanner/fr/translation.json
- frontend_app_admin_workspace_user/src/component/AdminWorkspace.jsx
- frontend_app_admin_workspace_user/src/css/index.styl
> [#1198] Right-aligned numbers in a table and change 'Member count' name (maybe v.2.3)

- backend/requirements.txt
- backend/setup.py
> [2.3.1]use preview_generator 0.11 (nice to have)

- backend/tracim_backend/lib/core/user.py
- backend/tracim_backend/tests/functional/test_user.py
- backend/tracim_backend/tests/library/test_user_api.py
related to #1470 
this will fix also #2034 
> Fix/1470  convert stored user email as lowercase

- frontend_lib/src/component/Timeline/Comment.styl
https://github.com/tracim/tracim/issues/2032
NOTE: I have pushed a previous commit directly into maintenance2.3. My bad. Here is it's id https://github.com/tracim/tracim/commit/e9a01a42f333bc0a546f59cbe43d12e2e5f9b7e2
The complete change for the Timeline comments are this PR and the commit above
> [#2032] add same link design to received comments

- .pre-commit-config.yaml
allow markdown hard linebreak for markdown file in pre-commit
see https://github.github.com/gfm/#hard-line-break
> allow markdown hard linebreak

- backend/requirements.txt
- backend/setup.py
- backend/tracim_backend/__init__.py
> [2.3.1] update some dependencies to mitigate security issue

- backend/tracim_backend/lib/core/system.py
- frontend/src/version.json
> [2.3.1] [#2044] update version of frontend and backend from 2.3.0 to 2.3.1

- tools_docker/Debian_Uwsgi/common.sh
- tools_docker/README.md
> [2.3.1] [#2005]  starting docker without envvars not deactivate notification

- frontend/src/component/Workspace/Folder.styl
- frontend/src/css/ContentItem.styl
https://github.com/tracim/tracim/issues/2058
> [#2058] fix content name overflow ellipsis on firefox

- backend/tracim_backend/lib/search/es_models.py
- backend/tracim_backend/lib/search/search.py
- backend/tracim_backend/tests/functional/test_elasticsearch_search.py
> store both label and acp label to handle exact match

- backend/tracim_backend/__init__.py
- backend/tracim_backend/app_models/applications.py
- backend/tracim_backend/app_models/contents.py
- backend/tracim_backend/app_models/validator.py
- backend/tracim_backend/command/__init__.py
- backend/tracim_backend/fixtures/__init__.py
- backend/tracim_backend/lib/agenda/agenda.py
- backend/tracim_backend/lib/agenda/authorization.py
- backend/tracim_backend/lib/core/application.py
just some typing fix done using monkeytype.
related to #2105 
> monkeytype  automatic typing fix

- frontend/src/container/Tracim.jsx
> Fix Admin User page route to respect the new naming refactor

- frontend/src/component/Header/Logo.jsx
- frontend/src/container/Header.jsx
> [Nice to have in 2.4] Fix/2092 logo route

- frontend/dist/assets/tracim/tinymceInit.js
- functionnal_tests/cypress/integration/generic_frontend/operation_tinymce.js
> Fix/2011 Hide the file input when upload an image into tinymce

- frontend/src/component/Account/Notification.jsx
> Fix/2096 user fetching in Notification to respect the new naming refactor

- frontend/src/css/ContentItem.styl
- frontend_lib/src/component/ListItemWrapper/ListItemWrapper.styl
> [Nice to have in 2.4] Fix/2046 click area to open the contents

- frontend/src/component/Account/Notification.jsx
- frontend/src/container/AdminAccount.jsx
> [Nice to have in 2.4] Fix/2096 Notifications settings in user profile

- frontend_app_admin_workspace_user/src/container/AdminWorkspaceUser.jsx
- functionnal_tests/cypress/integration/admin/switching_different_workspace_advanced.js
- functionnal_tests/cypress/support/generic_selector_commands.js
- functionnal_tests/cypress/support/urls_commands.js
> Fix/2121  bug when open two workspaces advanced app in a row in admin > workspace

- frontend/src/component/Workspace/ContentItem.jsx
- frontend/src/component/Workspace/Folder.jsx
- frontend/src/container/WorkspaceContent.jsx
- frontend_lib/src/component/ListItemWrapper/ListItemWrapper.jsx
- functionnal_tests/cypress/integration/workspace/scroll_to_active_content.js
> [Nice to have in 2.4] Scroll to 'active' content (ie opened content or opened folder)

- backend/tracim_backend/lib/core/system.py
- changelog.md
- frontend/src/version.json
-[x] update changelog and version number of backend and frontend
related to #2133 
> [2.3.2] update changelog and version number of backend and frontend [skip ci]

- frontend/src/component/Header/MenuActionListItem/AdminLink.jsx
- frontend/src/container/Login.jsx
- functionnal_tests/cypress/integration/login/login_after_disconnection.js
- functionnal_tests/cypress/support/generic_selector_commands.js
- functionnal_tests/cypress/support/urls_commands.js
-[x] import fix from develop about this issue #2134 
> [2.3.2] hotfix from develop branch about email notification when disconnect

- backend/cypress_test.ini
- backend/development.ini.sample
> [#2177] Reduce level about sqlalchemy log

- frontend_app_file/src/container/File.jsx
- functionnal_tests/cypress/integration/app_file/switch_between_file_spec.js
- functionnal_tests/cypress/support/commands.js
- functionnal_tests/cypress/support/db_commands.js
- functionnal_tests/cypress/support/urls_commands.js
https://github.com/tracim/tracim/issues/2174
> [#2174] app file now always opens in view mode when switching content

- frontend_app_file/src/container/File.jsx
- frontend_app_office_document/i18next.scanner/en/translation.json
- frontend_app_office_document/i18next.scanner/fr/translation.json
- frontend_app_office_document/src/container/CollaborativeEditionFrame.jsx
- frontend_app_office_document/src/index.js
> WIP : [#2180] Allow to view file as a reader in collaborative edition software

- frontend/i18next.scanner/en/translation.json
- frontend/i18next.scanner/fr/translation.json
- frontend/src/helper.js
#573 
Add plural to descriptions and add 'profile + description' in profiles descriptions
> Fix/573 Fix profiles descriptions and roles descriptions

- frontend_app_office_document/src/container/CollaborativeEditionFrame.jsx
#2190
#2180 can't edit document anymore
#2157 popup translation
> Collabora iframe translation

- backend/tracim_backend/applications/share/models_in_context.py
- backend/tracim_backend/applications/share/schema.py
- backend/tracim_backend/tests/functional/test_share_content.py
> Fix/2185  add share token to content share in api

- backend/tracim_backend/applications/share/controller.py
- backend/tracim_backend/tests/functional/test_share_content.py
related to #2184 
need frontend support.
> use post instead of put for add share

- frontend/i18next.scanner/en/translation.json
- frontend/i18next.scanner/fr/translation.json
- frontend/src/action-creator.async.js
- frontend/src/container/WorkspaceContent.jsx
> Fix/2141  no redict for unknow workspace or unknown file

- frontend_app_file/src/container/File.jsx
- frontend_app_file/src/css/index.styl
- frontend_lib/src/component/Button/GenericButton.jsx
- frontend_lib/src/component/Button/GenericButton.styl
- frontend_lib/src/component/Input/SelectStatus/SelectStatus.jsx
- frontend_lib/src/component/Input/SelectStatus/SelectStatus.styl
> [#2203] css changes to have a responsive behavior

- backend/tracim_backend/applications/share/email_manager.py
- backend/tracim_backend/applications/share/lib.py
- backend/tracim_backend/templates/mail/shared_content_to_emitter_body_html.mak
- backend/tracim_backend/templates/mail/shared_content_to_receiver_body_html.mak
- backend/tracim_backend/tests/functional/test_share_content.py
> Fix/2200  email template for download

- backend/tracim_backend/applications/share/email_manager.py
- backend/tracim_backend/applications/share/models_in_context.py
- backend/tracim_backend/templates/mail/shared_content_to_emitter_body_html.mak
- backend/tracim_backend/templates/mail/shared_content_to_receiver_body_html.mak
*Please indicate here a summary of pull request content or if related issue exist, please indicate issue reference here*
> Fix/xxx  minor fix on  email templates

- frontend_app_folder_advanced/src/container/FolderAdvanced.jsx
> [#2191] changing the logic to file in the allowed contents inside a folder

- frontend/src/container/WorkspaceContent.jsx
- functionnal_tests/cypress/integration/app_interface/switching_workspace_feature_spec.js
> fix content list not reloading when switching workspace

- frontend_app_file/i18next.scanner/en/translation.json
- frontend_app_file/i18next.scanner/fr/translation.json
- frontend_app_file/src/container/File.jsx
- frontend_lib/i18next.scanner/en/translation.json
- frontend_lib/i18next.scanner/fr/translation.json
- frontend_lib/src/component/ShareDownload/NewShareDownload.jsx
- frontend_lib/src/component/Timeline/Revision.jsx
> [#2226] specify password errors

- frontend/src/css/GuestPage.styl
- frontend/src/css/UnloggedPage.styl
> [#2235] fix responsive issue at guestdownload class

- backend/tracim_backend/applications/share/lib.py
- backend/tracim_backend/applications/upload_permissions/lib.py
- backend/tracim_backend/tests/functional/test_share_content.py
- backend/tracim_backend/tests/functional/test_upload_permission.py
> Fix/2231  disable access to disabled content share

- backend/tracim_backend/applications/share/controller.py
- backend/tracim_backend/applications/share/schema.py
- backend/tracim_backend/tests/functional/test_share_content.py
> replace tracim share password header to post method

- backend/tracim_backend/models/data.py
- backend/tracim_backend/tests/models/test_content.py
> avoid not allowed content property error

- frontend_app_folder_advanced/src/container/FolderAdvanced.jsx
- frontend_app_share_folder_advanced/src/container/ShareFolderAdvanced.jsx
> [#2244] fix content authorizations at folder

- frontend_app_office_document/src/container/PopupCreateOfficeDocument.jsx
- frontend_lib/src/component/Input/RadioBtn/RadioBtn.jsx
> adds keydown on radiobtn

- backend/development.ini.sample
- backend/requirements.txt
- backend/setup.cfg
- backend/setup.py
- backend/tracim_backend/lib/utils/logger.py
> Fix/2132  full datetime on logger

- backend/tracim_backend/applications/share/schema.py
- backend/tracim_backend/applications/upload_permissions/schema.py
- backend/tracim_backend/tests/functional/test_share_content.py
- backend/tracim_backend/tests/functional/test_upload_permission.py
> do not accept empty email list

- backend/tracim_backend/applications/share/controller.py
- backend/tracim_backend/applications/share/schema.py
- backend/tracim_backend/applications/upload_permissions/controller.py
- backend/tracim_backend/applications/upload_permissions/schema.py
- backend/tracim_backend/tests/functional/test_share_content.py
- backend/tracim_backend/tests/functional/test_upload_permission.py
> Fix/2254  fix password protected upload

- frontend_lib/src/component/Timeline/Comment.jsx
- frontend_lib/src/component/Timeline/Timeline.jsx
- frontend_lib/src/component/Timeline/Timeline.styl
- functionnal_tests/cypress/integration/app_thread/operation_allcontent_delete_thread.js
> Fix/2276  fix timeline buttons not visible

- frontend_lib/src/component/ShareDownload/ShareDownload.styl
> [#2258] Center the cancel button icon in ShareDownload

- frontend_lib/src/component/Timeline/Timeline.styl
#2276
The form should be always at the bottom of the Timeline
> [#2276] Fix the form position in the Timeline

- frontend/package.json
- frontend/src/component/GuestPage/DownloadForm.jsx
- frontend/src/component/GuestPage/UploadForm.jsx
- frontend_app_share_folder_advanced/package.json
- frontend_app_share_folder_advanced/src/component/NewUpload.jsx
- frontend_lib/package.json
- frontend_lib/src/component/ShareDownload/NewShareDownload.jsx
- frontend_lib/src/component/Timeline/Comment.styl
> [#2282] Fix css in sidebar of the app

- frontend_app_workspace_advanced/src/css/index.styl
- frontend_lib/src/component/NewMemberForm/NewMemberForm.jsx
- frontend_lib/src/component/NewMemberForm/NewMemberForm.styl
- frontend_lib/src/component/PopinFixed/PopinFixed.styl
> Fix/2237  css fix at dashboard advanced

- frontend_lib/src/component/Input/SelectStatus/SelectStatus.styl
> [#2294] Repsonsive fix for status icon in app header

- frontend_lib/src/component/ShareLink/ShareLink.styl
> [#2297] Resize share link width

- frontend_lib/src/component/Timeline/Comment.styl
> [#2300] Handle long words in comments of timeline

- frontend/i18next.scanner/en/translation.json
- frontend/i18next.scanner/fr/translation.json
- frontend/src/i18n.js
- frontend_app_share_folder_advanced/i18next.scanner/en/translation.json
- frontend_app_share_folder_advanced/i18next.scanner/fr/translation.json
#2312 
Some translations was removed when I built the translations
> Fix translations issues for share upload

- backend/tracim_backend/applications/upload_permissions/controller.py
- backend/tracim_backend/applications/upload_permissions/schema.py
- backend/tracim_backend/tests/functional/test_upload_permission.py
> new endpoint to get upload permission info

- README.md
- install_frontend_dependencies.sh
- setup_default_backend.sh
- setup_functionnal_tests.sh
> [#2314] nodejs version ready for debian buster

- frontend_lib/src/component/PopinFixed/PopinFixed.styl
- frontend_lib/src/component/PopinFixed/PopinFixedRightPart.jsx
> [#2316] fix css at the icons of the file internal menu

- frontend_app_share_folder_advanced/src/component/NewUpload.jsx
- frontend_app_share_folder_advanced/src/css/index.styl
- frontend_lib/src/component/ShareDownload/NewShareDownload.jsx
- frontend_lib/src/component/ShareDownload/ShareDownload.styl
> [#2330] smaller input for emails and change qustion mark color

- frontend_app_share_folder_advanced/src/container/ShareFolderAdvanced.jsx
- frontend_lib/src/component/PopinFixed/PopinFixedHeader.jsx
- frontend_lib/test/component/PopinFixedHeader.spec.js
> [#2310] Remove the editTitle button in ShareFolderAdvanced header

- backend/tracim_backend/applications/share/lib.py
- backend/tracim_backend/applications/upload_permissions/lib.py
> lowercase email for shared_content and upload permission

- backend/tracim_backend/lib/webdav/dav_provider.py
- backend/tracim_backend/lib/webdav/resources.py
> do not show inbox content in webdav

- .travis.yml
reorder unit and functional test for frontend in travis
> put frontend unit test before functional tests

- frontend/i18next.scanner/en/translation.json
- frontend/i18next.scanner/fr/translation.json
- frontend/src/component/Workspace/ShareFolder.jsx
- frontend_app_share_folder_advanced/src/container/ShareFolderAdvanced.jsx
> [#2358] change inbox name to received files and its translations

- backend/tracim_backend/applications/share/controller.py
- backend/tracim_backend/applications/share/lib.py
- backend/tracim_backend/applications/share/models.py
- backend/tracim_backend/applications/share/models_in_context.py
- backend/tracim_backend/tests/functional/test_share_content.py
> access to content using contentlib with default filter

- frontend_app_office_document/src/container/CollaborativeEditionFrame.jsx
> Fix bug content list cycling after closing collabora iframe

- backend/tracim_backend/lib/core/system.py
- backend/tracim_backend/models/context_models.py
- backend/tracim_backend/tests/functional/test_system.py
- backend/tracim_backend/views/core_api/schemas.py
> max workspace size and max workspace per user in config endpoint

- backend/tracim_backend/config.py
- frontend/src/component/Workspace/Folder.jsx
- frontend/src/component/Workspace/OpenContentApp.jsx
- frontend/src/component/Workspace/OpenCreateContentApp.jsx
- frontend/src/container/WorkspaceContent.jsx
https://github.com/tracim/tracim/issues/2372
> Fix/2372  remove collabora from content type endpoint

- backend/tracim_backend/applications/upload_permissions/controller.py
- backend/tracim_backend/lib/core/content.py
- backend/tracim_backend/tests/functional/test_upload_permission.py
related to #2029: add  workspace size check on upload.
> add workspace size check on public upload

- tools_docker/Debian_Uwsgi/Dockerfile
> delete node_module folder not necessary to build image

- frontend_app_share_folder_advanced/src/css/index.styl
> [#2374] change share folder size

- backend/tracim_backend/lib/core/system.py
- backend/tracim_backend/migration/versions/cd79614189ac_add_owner_to_workspace.py
- changelog.md
- frontend/src/version.json
> New stable version of tracim: release_02.04.01

- backend/tracim_backend/lib/core/system.py
- changelog.md
- frontend/src/version.json
- frontend_lib/src/component/Timeline/Comment.styl
> New stable version of tracim: release_02.04.02

- tools_docker/Debian_Uwsgi/common.sh
> fix wrong path about file template dir

- backend/tracim_backend/lib/core/system.py
- changelog.md
- frontend/src/component/Workspace/Folder.jsx
- frontend/src/version.json
- tools_docker/Debian_Uwsgi/common.sh
> New stable version of tracim: release_02.04.03

- frontend_lib/src/component/Timeline/Comment.styl
https://github.com/tracim/tracim/issues/2455
> [#2455] links in comments of timeline have default design

- frontend/src/component/Workspace/ContentItem.jsx
> [#2494] Align all content texts and icons in workspace

- functionnal_tests/cypress/integration/app_html-document/operation_dashboard_dashboardbutton_create_html-document.js
- functionnal_tests/cypress/integration/sidebar/presence_sidebar_dashboard.js
- functionnal_tests/cypress/integration/workspace/content_dashboard_activity.js
> Fix/2500  fix broken cypress test

- frontend_app_file/src/container/File.jsx
> [#2501] When load new content in app file, always load the first page

- .travis.yml
- README.md
- backend/README.md
- backend/requirements.txt
- backend/setup.py
- backend/tracim_backend/lib/agenda/__init__.py
- backend/tracim_backend/lib/core/system.py
- backend/tracim_backend/models/auth.py
- changelog.md
- frontend/src/version.json
- functionnal_tests/cypress/integration/app_html-document/operation_dashboard_dashboardbutton_create_html-document.js
- functionnal_tests/cypress/integration/sidebar/presence_sidebar_dashboard.js
- functionnal_tests/cypress/integration/workspace/content_dashboard_activity.js
- setup_default_backend.sh
- tools_docker/Debian_Uwsgi/Dockerfile
> Feature/2503  use preview generator 0.12 (master)

- backend/tracim_backend/applications/share/schema.py
> fix share endpoint default password value

- backend/tracim_backend/lib/core/system.py
- changelog.md
- frontend/src/version.json
- functionnal_tests/cypress/integration/app_html-document/tiny_mce__can_type_content_spec.js
> New stable version of tracim: release_02.04.05

- backend/tracim_backend/models/context_models.py
- backend/tracim_backend/tests/functional/test_account.py
- backend/tracim_backend/tests/functional/test_user.py
- backend/tracim_backend/tests/functional/test_workspaces.py
- backend/tracim_backend/views/core_api/account_controller.py
- backend/tracim_backend/views/core_api/schemas.py
- backend/tracim_backend/views/core_api/user_controller.py
- backend/tracim_backend/views/core_api/workspace_controller.py
> Feature/2518  allowed user and workspace space

- backend/tracim_backend/views/agenda_api/schemas.py
- backend/tracim_backend/views/core_api/schemas.py
> use description instead of descriptions in marshmallow schema

- color.json.sample
- frontend_app_gallery/i18next.scanner/en/translation.json
- frontend_app_gallery/i18next.scanner/fr/translation.json
- frontend_app_gallery/src/component/Carousel.jsx
- frontend_app_gallery/src/container/Gallery.jsx
- frontend_app_gallery/src/css/index.styl
*Please indicate here a summary of pull request content or if related issue exist, please indicate issue reference here*
> Fix/2512  fix app gallery

- backend/tracim_backend/lib/core/system.py
- changelog.md
- frontend/src/version.json
> new release 2.5.0

- backend/development.ini.sample
- backend/tracim_backend/__init__.py
- backend/tracim_backend/config.py
- backend/tracim_backend/views/frontend.py
- frontend/dist/index.mak
> [for 2.5.1] add mecanism to inject easily javascript code in existing tracim

- frontend/dist/index.mak
- tools_docker/Debian_Uwsgi/apache2.conf.sample
- tools_docker/Debian_Uwsgi/common.sh
- tools_docker/README.md
> [for 2.5.1] plugins/custom_toolbox available with docker image

- backend/tracim_backend/lib/core/user.py
- backend/tracim_backend/lib/mail_notifier/notifier.py
- backend/tracim_backend/locale/en/LC_MESSAGES/tracim_backend.po
- backend/tracim_backend/locale/fr/LC_MESSAGES/tracim_backend.po
- backend/tracim_backend/templates/mail/created_account_body_html.mak
- backend/tracim_backend/tests/functional/test_daemons.py
- backend/tracim_backend/tests/functional/test_mail_notification.py
- backend/tracim_backend/tests/functional/test_user.py
- backend/tracim_backend/tests/functional/test_workspaces.py
related to #2565 
-> change template to make email about new account created more explicit about origin.
> explicit origin user for email notification

- backend/tracim_backend/lib/core/system.py
- changelog.md
- frontend/src/version.json
> WIP : [for 2.5.1] new release 2.5.1

- frontend_app_gallery/src/component/Carousel.jsx
- frontend_app_gallery/src/container/Gallery.jsx
> [#2538] Change lazyloading to 'progressive' when autoplay is enabled

- frontend_app_gallery/src/container/Gallery.jsx
- frontend_app_gallery/src/css/index.styl
> [for 2.6.0] Fix/2541  hide lightbox buttons in app gallery when mouse not active

- frontend_app_gallery/src/css/index.styl
> [for 2.6.0] Fix/2551 add a separation between thumbnails and mainPreview in app gallery

- frontend_app_gallery/src/component/Carousel.jsx
- frontend_app_gallery/src/container/Gallery.jsx
- frontend_app_gallery/test/component/Carousel.spec.js
- frontend_app_gallery/test/component/Gallery.spec.js
- frontend_app_gallery/test/component/MainPreview.spec.js
- frontend_app_gallery/test/component/ThumbnailPreview.spec.js
- frontend_app_gallery/test/setup.js
- run_frontend_unit_test.sh
> [for 2.6.0] Feature/2574  gallery  app  unit  tests

- tools_docker/Debian_Uwsgi/Dockerfile
- tools_docker/Debian_Uwsgi/entrypoint.sh
Related to #2570 
- xvfb now working to build preview image of 3D file.
> [for 2.6.0] fix preview-generator of 3D file failed

- backend/README.md
- backend/create_test_storage_dir.sh
- setup_default_backend.sh
> add create test_storage_dir script to make pytest command work almost out of the box from new fresh install

- frontend/src/component/Dashboard/MemberList.jsx
- frontend/src/component/Sidebar/WorkspaceListItem.jsx
- frontend/src/component/Workspace/BtnExtandedAction.jsx
- frontend/src/component/Workspace/ContentItem.jsx
- frontend/src/component/Workspace/Folder.jsx
- frontend/src/component/Workspace/ShareFolder.jsx
- frontend/src/container/Dashboard.jsx
- frontend/src/container/Sidebar.jsx
- frontend/src/container/Tracim.jsx
- frontend/src/container/WorkspaceContent.jsx
- frontend/test/src/component/BtnExtandedAction.spec.js
- frontend/test/src/helper.spec.js
- frontend_app_collaborative_document_edition/src/container/CollaborativeEditionFrame.jsx
- frontend_app_collaborative_document_edition/src/index.js
- frontend_app_file/src/container/File.jsx
- frontend_app_folder_advanced/src/index.js
- frontend_app_html-document/src/container/HtmlDocument.jsx
- frontend_app_share_folder_advanced/dist/index.html
- frontend_app_share_folder_advanced/src/index.js
- frontend_app_thread/src/container/Thread.jsx
- frontend_lib/src/component/NewMemberForm/NewMemberForm.jsx
- frontend_lib/src/component/PopinFixed/PopinFixedHeader.jsx
- frontend_lib/src/component/ShareDownload/ShareDownloadManagement.jsx
- frontend_lib/src/component/ShareLink/ShareLink.jsx
- frontend_lib/src/component/Timeline/Timeline.jsx
- frontend_lib/src/debug.js
- frontend_lib/src/helper.js
https://github.com/tracim/tracim/issues/1656
> harmonized ROLE and PROFILE object to match backend + refactor

- backend/setup.cfg
- backend/setup.py
- backend/tracim_backend/lib/core/system.py
> Fix/1484  consistent python version using setup cfg for metadata

- backend/cypress_test.ini
- backend/development.ini.sample
- backend/doc/setting.md
- backend/tests_configs.ini
- backend/tracim_backend/config.py
> remove ldap_base_url and ldap_base_url deprecated parameters

- frontend/dist/index.mak
> do not load gallery frontend app twice

- frontend/src/component/Workspace/BtnExtandedAction.jsx
- frontend/src/component/Workspace/OpenContentApp.jsx
- frontend/src/container/WorkspaceContent.jsx
- frontend/test/fixture/app/gallery.js
- frontend/test/hocMock/redux/appList/appList.js
- frontend/test/src/component/BtnExtandedAction.spec.js
- frontend_app_workspace_advanced/src/component/OptionalFeatures.jsx
- frontend_app_workspace_advanced/src/container/WorkspaceAdvanced.jsx
Merge frontend fix for #617 into `fix/617__reorganise_apps` 
> Merge frontend fix for #617 into `fix/617__reorganise_apps` 

- frontend/src/container/WorkspaceContent.jsx
> [for 2.6.0] Fix/2611 Hide/show collabora/libreoffice button in dropdown according to config

- backend/tracim_backend/lib/mail_notifier/notifier.py
- backend/tracim_backend/templates/mail/content_update_body_html.mak
- backend/tracim_backend/templates/mail/created_account_body_html.mak
- backend/tracim_backend/templates/mail/new_upload_event_body_html.mak
- backend/tracim_backend/templates/mail/reset_password_body_html.mak
- backend/tracim_backend/templates/mail/shared_content_to_emitter_body_html.mak
- backend/tracim_backend/templates/mail/shared_content_to_receiver_body_html.mak
- backend/tracim_backend/templates/mail/upload_permission_to_emitter_body_html.mak
- backend/tracim_backend/templates/mail/upload_permission_to_receiver_body_html.mak
> [2.6.X] html tag for email template

- frontend_app_file/src/container/PopupCreateFile.jsx
- functionnal_tests/cypress/integration/app_file/add_file_as_user_spec.js
> Fix/2669 Wrong url after uploading a file

- frontend_lib/i18next.scanner/en/translation.json
- frontend_lib/i18next.scanner/fr/translation.json
> [for 2.6.1] fix roles translation in frontend_lib

- frontend/src/component/Dashboard/RecentActivity.jsx
- frontend/src/component/Sidebar/WorkspaceListItem.jsx
- frontend/src/component/Workspace/BtnExtandedAction.jsx
- frontend/src/component/Workspace/ContentItem.jsx
- frontend/src/component/Workspace/Folder.jsx
- frontend/src/container/WorkspaceContent.jsx
- frontend/test/src/component/BtnExtandedAction.spec.js
- frontend_app_file/src/container/File.jsx
- frontend_app_folder_advanced/src/container/FolderAdvanced.jsx
> [for 2.6.1] fix some permissions right for some roles

- frontend_app_file/src/container/File.jsx
- frontend_lib/src/component/FileDropzone/FileDropzone.jsx
- frontend_lib/test/component/FileDropzone.spec.js
> [For 2.6.1] Fix/2674 filename when updating file and no preview

- frontend_app_workspace/src/container/PopupCreateWorkspace.jsx
- functionnal_tests/cypress/integration/workspace/create_workspace_spec.js
> [For 2.6.1] Fix/2665 fix workspace to open in sidebar after creating one

- README.md
> [for 2.6.1] Add instructions to run frontend unit tests in the readme of tracim

- frontend/dist/assets/tracim/tinymceInit.js
> [For 2.6.x] Fix/1342 don't auto cut url with same domain in tinyMCE

- frontend/src/component/GuestPage/UploadForm.jsx
- frontend/src/css/GuestPage.styl
> Fix/2437 Responsive in guest upload form

- frontend/src/component/Dashboard/MemberList.jsx
- frontend/src/component/Dashboard/MemberList.styl
> [for 2.6.2] Fix/1513 put add member button at the top of memberList in Dashboard

- changelog.md
> [for 2.6.2] fixes some typo in changelog

- install_frontend_dependencies.sh
> fix: verify if -> check whether to install deps

- frontend_app_folder_advanced/i18next.scanner/translation.json
I made a portuguese traduction of the frontend_app_folder_advanced
Related to #2743
> translation.json

- .travis.yml
- README.md
> [for 2.6.2] Fix/2692 Regroup frontend tests into one stage in TravisCI

- frontend/src/component/common/Input/InputGroupText.jsx
- frontend/src/container/Login.jsx
- functionnal_tests/cypress/integration/login/content_login_page.js
>  [for 2.6.2] Fix/1294 login (email+password) and email auto completion in browser

- setup_functionnal_tests.sh
> [For 2.6.2] fix(build): Fix typos in setup_functionnal_tests.sh

- frontend/src/container/Sidebar.jsx
- frontend/test/src/container/Sidebar.spec.js
> [for 2.6.2] Fix/1503 close the sidebar when the device is a mobile

- frontend_app_gallery/src/component/Carousel.jsx
- frontend_app_gallery/src/component/MainPreview.jsx
- frontend_app_gallery/src/container/Gallery.jsx
- functionnal_tests/cypress/integration/app_gallery/app_gallery_spec.js
> [for 2.6.2] fix/2648 hide delete button according to current user role in Gallery

- frontend_app_workspace_advanced/package.json
- frontend_app_workspace_advanced/src/component/WorkspaceMembersList.jsx
- frontend_app_workspace_advanced/src/css/index.styl
- frontend_app_workspace_advanced/test/src/component/WorkspaceMemberList.spec.js
> [for 2.6.2] Fix/1513 put add member button at the top of memberList in Workspace advanced

- backend/tracim_backend/lib/search/elasticsearch_search/elasticsearch_search.py
- backend/tracim_backend/lib/search/elasticsearch_search/es_models.py
> [For 2.6.3] Use multifield for elasticsearch indexing

- frontend/test/src/component/RecentActivity.spec.js
- functionnal_tests/cypress/integration/app_file/switch_between_file_spec.js
- functionnal_tests/cypress/integration/app_folder/app_folder_spec.js
- functionnal_tests/cypress/support/urls_commands.js
> [For 2.6.3] Fix/2688 Add cypress and unit test for #2683

- backend/setup.cfg
- backend/setup.py
- backend/tracim_backend/applications/share/email_manager.py
- backend/tracim_backend/applications/upload_permissions/email_manager.py
- backend/tracim_backend/lib/mail_notifier/notifier.py
- backend/tracim_backend/lib/mail_notifier/utils.py
- backend/tracim_backend/tests/functional/test_mail_notification.py
- backend/tracim_backend/tests/library/test_utils.py
related to #2687 
Many mail optimization:
- Refactoring: Unique code for creating Message(EmailNotificationMessage)
- Add somes headers for best spam checker notation: Message-ID, Date
- Add "Content-Language" header for semantic
- Add "X-Auto-Response-Suppress" and "Auto-Submitted" headers in order to avoid receiving autoreply message.
- Add automatically generated text version of the html email with **html2text** (markdown like mail) and tracim **html sanitizer** (clean html used for conversion) for spam checker notation.
**For …
> [For 2.6.3] Feature/2687  improve email quality

- frontend_app_file/i18next.scanner/en/translation.json
- frontend_app_file/i18next.scanner/fr/translation.json
- frontend_app_file/src/component/PreviewComponent.jsx
- frontend_app_file/src/component/PreviewComponent.styl
- frontend_app_file/src/helper.js
- frontend_app_file/test/component/PreviewComponent.spec.js
> [for 2.6.x] fix/1515 Display a loading message when the img is loading in app file

- frontend/src/component/Sidebar/WorkspaceListItem.jsx
- frontend/src/container/Tracim.jsx
- functionnal_tests/cypress/integration/workspace/create_workspace_spec.js
> [for 2.6.x] Fix/2693 Scroll to workspace created in Sidebar

- frontend/dist/assets/tracim/tinymceInit.js
- frontend_lib/src/component/NewMemberForm/NewMemberForm.jsx
- frontend_lib/src/component/PopinFixed/PopinFixedHeader.jsx
#2679 
I don't think tests are required here because it will test the feature of `input` and `tinyMCE` instead of `Tracim`
> [For 2.6.x] Fix/2679 Input and tinyMCE auto focus

- backend/tracim_backend/lib/core/userworkspace.py
- backend/tracim_backend/tests/functional/test_workspaces.py
- backend/tracim_backend/views/core_api/schemas.py
- backend/tracim_backend/views/core_api/workspace_controller.py
- frontend/src/action-creator.async.js
- frontend/src/container/Dashboard.jsx
- frontend_app_workspace_advanced/src/action.async.js
- frontend_app_workspace_advanced/src/component/WorkspaceMembersList.jsx
- frontend_app_workspace_advanced/src/container/WorkspaceAdvanced.jsx
- functionnal_tests/cypress/integration/app_workspace_advanced/operation_workspace_advanced.js
- functionnal_tests/cypress/support/db_commands.js
> [for 2.6.x] Fix/1444 Hide disabled user in workspace advanced dashboard

- frontend_lib/package.json
- frontend_lib/src/appContentFactory.js
> [For 2.6.x] Fix/2454 Parse simple text in comment saved to get clickable links

- frontend/src/container/AppFullscreenRouter.jsx
- frontend/test/src/container/AppFullscreenRouter.spec.js
> [for 2.6.x] Fix/2791 Wrong warning message when disconnecting from Gallery App

- frontend_lib/i18next.scanner/en/translation.json
- frontend_lib/i18next.scanner/fr/translation.json
- frontend_lib/src/component/Timeline/Timeline.jsx
- frontend_lib/src/component/Timeline/Timeline.styl
- frontend_lib/test/component/Timeline.spec.js
> [for 2.6.x] fix/2406 Change style to rich text button displayed in apps which is confusing

- frontend_app_html-document/src/css/index.styl
- frontend_lib/src/component/Timeline/Comment.jsx
- frontend_lib/src/component/Timeline/Comment.styl
- functionnal_tests/cypress/integration/timeline/comment_size__spec.js
> [For 2.6.x] Fix #2595 / add a overflow wrap for fix long strings

- frontend/dist/assets/tracim/tinymceInit.js
- frontend/src/css/Generic.styl
- frontend_app_html-document/src/component/HtmlDocument.jsx
- frontend_app_html-document/src/css/index.styl
- frontend_lib/src/component/Input/TextAreaApp/TextAreaApp.styl
- frontend_lib/src/component/Timeline/Timeline.jsx
- frontend_lib/src/component/Timeline/Timeline.styl
> [for 2.6.x] Fix/2764 TinyMCE height responsivity

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
add default label to github issue template
> feature(repo): better github issue template

- tools_docker/Debian_Uwsgi/Dockerfile
- tools_docker/README.md
> [For 2.6.x] Allow a custom Tracim repo to build the Docker image

- frontend/src/component/Account/PersonalData.jsx
- frontend_lib/src/component/Avatar/Avatar.jsx
- frontend_lib/test/component/Avatar.spec.js
- functionnal_tests/cypress/integration/account/account_main_page.js
> [For 2.6.x] Fix/2569  Fix generated avatars when using spaces in the public name

- frontend/src/action-creator.async.js
- frontend/src/container/AdminAccount.jsx
- functionnal_tests/cypress/integration/admin/content_admin_user.js
> Fix/1855 add user's agenda at adminis view

- frontend/dist/index.html
- frontend/dist/index.mak
- frontend/src/component/Account/MenuSubComponent.styl
- frontend/src/component/Dashboard/MemberList.jsx
- frontend/src/component/Dashboard/MemberList.styl
- frontend/src/component/Dashboard/RecentActivity.jsx
- frontend/src/component/Dashboard/RecentActivity.styl
- frontend/src/component/Header/MenuActionListItem/AdminLink.jsx
- frontend/src/component/Header/MenuActionListItem/AdminLink.styl
- frontend/src/component/Header/MenuActionListItem/DropdownLang.jsx
- frontend/src/component/Header/MenuActionListItem/DropdownLang.styl
- frontend/src/component/Header/MenuActionListItem/MenuProfil.jsx
- frontend/src/component/Header/MenuActionListItem/MenuProfil.styl
- frontend/src/component/Workspace/BtnExtandedAction.jsx
- frontend/src/component/Workspace/BtnExtandedAction.styl
- frontend/src/component/Workspace/Folder.jsx
- frontend/src/component/Workspace/Folder.styl
- frontend/src/component/Workspace/ShareFolder.jsx
- frontend/src/component/common/Input/SubDropdownCreateButton.jsx
- frontend/src/component/common/Input/SubDropdownCreateButton.styl
- frontend_app_workspace_advanced/src/component/WorkspaceMembersList.jsx
- frontend_app_workspace_advanced/src/css/index.styl
- frontend_lib/src/component/Input/SelectStatus/SelectStatus.jsx
- frontend_lib/src/component/Input/SelectStatus/SelectStatus.styl
- frontend_lib/src/component/ListItemWrapper/ListItemWrapper.jsx
- frontend_lib/src/component/ListItemWrapper/ListItemWrapper.styl
- frontend_lib/src/component/NewMemberForm/NewMemberForm.jsx
- frontend_lib/src/component/NewMemberForm/NewMemberForm.styl
- frontend_lib/src/css/Variable.styl
- frontend_lib/test/component/ListItemWrapper.spec.js
> Fix/2673 Lighter background color on hover for content in list

- backend/setup.cfg
- changelog.md
- frontend/src/version.json
> prepare new stable release 2.7.0

- functionnal_tests/cypress/integration/admin/switching_different_workspace_advanced.js
> [for 3.0.0] Fix switching_different_workspace_advanced cypress test 

- .gitignore
- backend/tracim_backend/lib/core/user.py
- backend/tracim_backend/lib/core/workspace.py
- backend/tracim_backend/tests/functional/test_workspaces.py
Removes the circular dependency between `lib/core/user.py` and `lib/core/workspace.py`
Closes #2939 
> Fix/2939  user workspace circular dependency

- backend/development.ini.sample
- backend/doc/i18n.md
- backend/tracim_backend/config.py
- setup_default_backend.sh
- tools_docker/Debian_Uwsgi/Dockerfile
- tools_docker/Debian_Uwsgi/common.sh
- tools_docker/README.md
> [For 2.7.1] fix(backend): fix default value for parameters and others config file fix

- install_frontend_dependencies.sh
- tools_docker/Debian_Uwsgi/Dockerfile
> Install Node 10 in the docker image

- backend/tracim_backend/migration/versions/2bb8ccb44ce0_current_revision_id_in_content.py
related to #2962
remove non-null constraint in migration script for all databases.
> [For 2.7.2] revert non nullable constraint for cached_revision_id

- frontend/src/action-creator.async.js
- frontend/src/action-creator.sync.js
- frontend/src/container/Account.jsx
- frontend/src/reducer/user.js
- frontend/test/fixture/user/globalManager.js
- frontend/test/src/container/Account.spec.js
- frontend/test/src/reducer/user.spec.js
- frontend_app_admin_workspace_user/src/helper.js
- frontend_app_agenda/src/helper.js
- frontend_lib/src/debug.js
- functionnal_tests/cypress/fixtures/baseUser.json
- functionnal_tests/cypress/fixtures/defaultAdmin.json
> [For 3.0.0] Feature/2917 adding username to user at redux

- backend/doc/migration.md
- backend/setup.cfg
- backend/tracim_backend/migration/versions/2bb8ccb44ce0_current_revision_id_in_content.py
- changelog.md
- frontend/src/version.json
> New stable version of tracim: release_02.07.02

- frontend_app_collaborative_document_edition/src/container/CollaborativeEditionFrame.jsx
- frontend_app_collaborative_document_edition/test/CollaboraEditionFrame.spec.js
- frontend_app_collaborative_document_edition/test/setup.js
- frontend_app_custom-form/package.json
- run_frontend_unit_test.sh
This pull request fixes the frontend unit test script.
#2999 
> fix(test): run unit tests of frontend applications

- backend/doc/migration.md
Related to #2984 
(both checks checked because I don't this is is relevant here)
> fix(documentation): typo in the migration doc

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/pull_request_template.md
> fix: some errors in the GitHub templates

- backend/tracim_backend/lib/core/user.py
- backend/tracim_backend/lib/utils/authentification.py
- backend/tracim_backend/models/context_models.py
- backend/tracim_backend/tests/functional/test_workspaces.py
- backend/tracim_backend/views/core_api/schemas.py
- backend/tracim_backend/views/core_api/workspace_controller.py
#2970 
This pull request removes `public_name` from the `members` endpoint
:warning: This is my first contribution to the backend so I may have missed something.
RJ: I didn't write any test since this is a "feature" removal.
I tried to add an user to a workplace.
> fix(backend): remove public name from members endpoint

- backend/tracim_backend/models/context_models.py
- backend/tracim_backend/tests/functional/test_reset_password.py
- backend/tracim_backend/views/core_api/reset_password_controller.py
- backend/tracim_backend/views/core_api/schemas.py
> Fix/3020 Backend - allow resetting the password by username

- frontend_lib/src/component/Timeline/Timeline.jsx
- frontend_lib/src/component/Timeline/Timeline.styl
https://github.com/tracim/tracim/issues/3026
:warning: this PR must be merged in maintenance/2.7 and not in develop.
> [For 2.7.4] fix(front): fix tinymce height in responsive

- backend/tracim_backend/lib/utils/authorization.py
This PR adds a log when an HTTP request is made by an authenticated user.
The log includes the request method, path and user id.
Related to #3043
> [For 2.7.4] Log authenticated user

- backend/tracim_backend/lib/core/event.py
- backend/tracim_backend/tests/functional/test_contents.py
- backend/tracim_backend/tests/functional/test_user.py
- backend/tracim_backend/tests/functional/test_workspaces.py
> refactor(backend): include full entity detail in events

- backend/tracim_backend/lib/core/event.py
- backend/tracim_backend/models/event.py
- backend/tracim_backend/tests/library/test_event.py
Event is fired when is_deleted becomes True->False
Refs #3075
> feat(backend): undeleted event for user/content/workspace

- backend/tracim_backend/lib/core/user.py
- backend/tracim_backend/lib/utils/authentification.py
- backend/tracim_backend/lib/webdav/authentification.py
- backend/tracim_backend/lib/webdav/dav_provider.py
- backend/tracim_backend/tests/functional/test_webdav.py
- backend/tracim_backend/tests/functional/test_workspaces.py
- backend/tracim_backend/views/core_api/reset_password_controller.py
- backend/tracim_backend/views/core_api/schemas.py
- backend/tracim_backend/views/core_api/workspace_controller.py
> feat(backend): allow a user to identify on WebDAV using his username

- backend/development.ini.sample
- backend/tracim_backend/config.py
- backend/tracim_backend/tests/commands/test_commands.py
- backend/tracim_backend/tests/library/test_cleanup.py
> feature(backend): Rename default anonymized public name to Deleted user

- .travis.yml
- backend/README.md
- backend/daemons/mail_fetcher.py
- backend/daemons/mail_notifier.py
- backend/tests_configs.ini
- backend/tracim_backend/lib/rq/__init__.py
- backend/tracim_backend/lib/rq/foo.py
- backend/tracim_backend/lib/rq/worker.py
- backend/tracim_backend/lib/utils/daemon.py
- backend/tracim_backend/tests/library/test_rq.py
This worker class provides a connection to the tracim main database.
Start it with:
export TRACIM_CONF_PATH="$(pwd)/development.ini"
rq worker -w tracim_backend.lib.rq.worker.DatabaseWorker <queue>
Refs #2991
> feat(backend): RQ database worker

- install_frontend_dependencies.sh
#3096 
Automated tests are not made for installation scripts.
> Fix/3096 update configEnv path at installation script

- backend/tracim_backend/lib/core/event.py
- backend/tracim_backend/tests/library/test_event.py
Correction of a bug in TLMs when deleting/undeleting contents: #3114.
> fix(backend): content deletion was reported as modified

- backend/tracim_backend/models/context_models.py
- backend/tracim_backend/tests/functional/test_contents.py
> fix(backend): add missing current_revision_type into ContentInContext

- frontend/src/action-creator.sync.js
- frontend/src/container/Header.jsx
- frontend/src/container/Login.jsx
- frontend/src/container/Tracim.jsx
- frontend/src/reducer/TLMManager.js
- frontend/src/reducer/root.js
- frontend/src/reducer/tlmManager.js
- frontend/src/util/LiveMessageManager.js
- frontend/test/src/reducer/tlmManager.spec.js
https://github.com/tracim/tracim/issues/2850
> add TLM connection opening from Login.jsx

- backend/doc/apache.md
- tools_docker/Debian_Uwsgi/Dockerfile
- tools_docker/Debian_Uwsgi/apache2.conf.sample
- tools_docker/Debian_Uwsgi/common.sh
- tools_docker/Debian_Uwsgi/entrypoint.sh
- tools_docker/Debian_Uwsgi/supervisord_tracim.conf
Also improved docker build (split in several RUN commands)
Refs #3055.
> feat(backend): integrate pushpin and custom rq worker for TLMs

- backend/tracim_backend/hookspec.py
- backend/tracim_backend/lib/core/event.py
- backend/tracim_backend/lib/utils/authentification.py
- backend/tracim_backend/lib/utils/cors.py
- backend/tracim_backend/lib/utils/request.py
- backend/tracim_backend/models/event.py
- backend/tracim_backend/tests/functional/test_contents.py
- backend/tracim_backend/tests/functional/test_user.py
- backend/tracim_backend/tests/functional/test_workspaces.py
> add client token support for tracim web request

- backend/doc/live_message_setup.md
> fix(doc): use cypress_test.ini in the pushpin doc

- frontend_app_file/src/component/FileComponent.jsx
https://github.com/tracim/tracim/issues/2103
:warning: this PR points to `maintenance/2.7`
> fix(front): video player of app file properly change video source

- frontend_app_html-document/src/container/HtmlDocument.jsx
> Fix/3135  updade handleContentModified at frontend_app_html_doument

- README.md
- backend/README.md
- backend/development.ini.sample
- backend/doc/apache.md
- backend/doc/live_message_setup.md
- backend/doc/setting.md
- backend/tracim_backend/config.py
- backend/tracim_backend/views/core_api/account_controller.py
- frontend_app_file/test/fixture/content/shareList.js
> Improving documentation related to Live Message feature

- frontend_app_file/src/component/FileComponent.jsx
- frontend_app_file/src/container/File.jsx
- frontend_app_file/src/helper.js
- frontend_app_file/test/helper.spec.js
https://github.com/tracim/tracim/issues/2103
> fix(front): switch video mime type from whitelist to blacklist

- install_frontend_dependencies.sh
- yarn.lock
> fix(frontend) force minimal version of yarn

- backend/README.md
- backend/requirements.txt
- backend/setup.cfg
- backend/setup.py
- backend/tracim_backend/tests/functional/test_share_content.py
- changelog.md
- frontend/src/version.json
- frontend_app_file/i18next.scanner/en/translation.json
- frontend_app_file/i18next.scanner/fr/translation.json
- frontend_app_file/i18next.scanner/pt/translation.json
- frontend_app_file/src/component/FileComponent.jsx
- frontend_app_file/src/container/File.jsx
- frontend_app_file/src/css/index.styl
- frontend_app_file/src/helper.js
- frontend_app_file/test/helper.spec.js
> New stable version of tracim: release_02.07.05

- frontend_app_file/src/container/File.jsx
- frontend_app_file/test/component/File.spec.js
> [for 3.0.0] Update timeline according to TLM in app File

- frontend_app_workspace/src/container/PopupCreateWorkspace.jsx
- frontend_app_workspace/test/container/PopupCreateWorkspace.spec.js
> [for 3.0.0] Refactor CustomEvent handlers in app workspace

- frontend_app_folder_advanced/src/container/FolderAdvanced.jsx
- frontend_app_folder_advanced/test/.mocharc.js
- frontend_app_folder_advanced/test/apiMock.js
- frontend_app_folder_advanced/test/container/FolderAdvanced.spec.js
- functionnal_tests/cypress/integration/app_folder/app_folder_spec.js
> Feature/3106  tlm in app folder advanced

- frontend/src/container/Tracim.jsx
- frontend/test/src/container/Tracim.spec.js
> Feature/2850 Handle custom events at Tracim.jsx

- backend/tracim_backend/migration/versions/fb2ae8c604ac_add_undelete_operation_type_in_enum.py
> fix(backend): add missing migration script for UNDELETED event operation type

- backend/tracim_backend/lib/core/event.py
- backend/tracim_backend/lib/core/user.py
- backend/tracim_backend/tests/library/test_event.py
> limit content event to workspace members only

- backend/development.ini.sample
- tools_docker/Debian_Uwsgi/common.sh
> use redis session as default one for docker

- frontend/src/action-creator.sync.js
- frontend/src/container/ReduxTlmDispatcher.jsx
- frontend/src/container/Sidebar.jsx
- frontend/src/container/Tracim.jsx
- frontend/src/reducer/workspaceList.js
- frontend/src/util/helper.js
- frontend/test/src/container/Sidebar.spec.js
- frontend/test/src/reducer/workspaceList.spec.js
- frontend_app_workspace/src/container/PopupCreateWorkspace.jsx
- frontend_app_workspace_advanced/src/container/WorkspaceAdvanced.jsx
- frontend_lib/src/customEvent.js
- frontend_lib/src/helper.js
- yarn.lock
> Feature/2850 handle TLM in Sidebar

- frontend/src/container/ReduxTlmDispatcher.jsx
- frontend/src/container/Sidebar.jsx
- frontend_app_workspace/src/container/PopupCreateWorkspace.jsx
- frontend_lib/src/helper.js
- frontend_lib/src/index.js
https://github.com/tracim/tracim/issues/3230
> move the handling of the TLM member.created when user is creating a workspace for his own

- frontend/src/container/WorkspaceContent.jsx
- frontend/test/apiMock.js
- frontend/test/src/container/WorkspaceContent.spec.js
> Fix/3236 FlashMessage error is always displayed when moving content

- backend/tracim_backend/lib/core/live_messages.py
- backend/tracim_backend/tests/functional/test_live_messages.py
- backend/tracim_backend/views/core_api/user_controller.py
> add keepalive and stream opened event

- frontend_lib/src/helper.js
- frontend_lib/test/helper.spec.js
- frontend_lib/test/index.js
> fix(frontend): set revision number in timeline to revision count + 1

- frontend_lib/i18next.scanner/en/translation.json
- frontend_lib/i18next.scanner/fr/translation.json
- frontend_lib/i18next.scanner/pt/translation.json
- frontend_lib/src/appContentFactory.js
- yarn.lock
> Fix/3241  add a more specific error message and update translations

- frontend/src/component/Account/Notification.jsx
- frontend/src/container/ReduxTlmDispatcher.jsx
#3254 
Automated tests were not written because the only function changed was to render and we do not have unit tests for rendering and in relation to functional tests we do not have yet a mechanism that allows to open multiple windows/tabs in functional tests to reproduce this problem.
> Fix/3254 fix blank page at Account

- frontend/src/reducer/currentWorkspace.js
- frontend/src/reducer/workspaceContentList.js
- frontend/src/reducer/workspaceShareFolderContentList.js
- frontend/test/src/reducer/currentWorkspace.spec.js
- frontend/test/src/reducer/workspaceContent.spec.js
- frontend/test/src/reducer/workspaceShareFolderContentList.spec.js
> Fix/3247 Handle move content in a new workspace in Redux reducer

- backend/tracim_backend/lib/webdav/resources.py
> unallow reader to update content

- frontend/src/container/Home.jsx
- frontend/test/src/container/Home.spec.js
> Fix/3268 don't show the message when username lenght is 0

- frontend/src/container/AdminAccount.jsx
- frontend/test/setup.js
- frontend/test/src/container/AdminAccount.spec.js
> Fix/3257 fix blank page at AdminAccount

- frontend_app_file/src/container/File.jsx
- frontend_app_html-document/src/container/HtmlDocument.jsx
- frontend_app_thread/src/container/Thread.jsx
- frontend_lib/src/component/Timeline/Timeline.jsx
- frontend_lib/src/helper.js
- frontend_lib/test/component/Timeline.spec.js
- frontend_lib/test/fixture/contentCommentList.js
- frontend_lib/test/fixture/contentRevisionList.js
> Fix/3242 Timeline fix auto-scroll when new items arrives from TLM

- frontend_app_file/src/container/File.jsx
- frontend_app_file/test/component/File.spec.js
- frontend_app_html-document/src/container/HtmlDocument.jsx
- frontend_app_html-document/test/container/HtmlDocument.spec.js
- frontend_app_thread/src/container/Thread.jsx
- frontend_app_thread/test/container/Thread.spec.js
> Fix/3291 handle user.modified TLM at appFeatures

- frontend_app_admin_workspace_user/src/component/AdminUser.jsx
- frontend_app_admin_workspace_user/src/css/index.styl
- functionnal_tests/cypress/integration/admin/content_admin_user.js
> Fix/3286 handle large input in the table at Admin page

- .github/pull_request_template.md
- ~~[ ] Automated tests have been written (covering the feature or non regression), or *at least* an issue has been created to implement the test~~ (irrelevant)
- ~~[ ] Manual tests done to ensure stability on whole application layers~~ (irrelevant)
- ~~[ ] The original issue has been updated with a short summary of the implemented solution~~ (no issue)
- ~~[ ] Tested by the quality team~~ irelevant
> Github PR Template - Move the developer section before the reviewer section

- frontend_app_admin_workspace_user/src/container/AdminWorkspaceUser.jsx
#3303 
Tests are not relevant in this case because we don't have a way to test the good order of component's import.
> Fix/3303 fix order Radium at frontend_app_admin_workspace_user

- frontend/src/component/Header/MenuActionListItem/DropdownLang.jsx
- frontend/src/component/Header/MenuActionListItem/MenuProfil.jsx
- frontend/src/reducer/user.js
- functionnal_tests/cypress/integration/login/new_user_first_login_spec.js
> Fix/3225 put a default language if user don't have

- frontend/src/container/Login.jsx
> refactor(frontend): change login input type to text for autocomplete

- backend/README.md
- backend/doc/apache.md
- functionnal_tests/cypress/integration/workspace/add_members__as_admin_spec.js
- tools_docker/Debian_Uwsgi/apache2.conf.sample
- tools_docker/Debian_Uwsgi/common.sh
- tools_docker/Debian_Uwsgi/entrypoint.sh
- tools_docker/Debian_Uwsgi/uwsgi.ini.sample
> adapt uwsgi and apache config

- frontend/src/container/Tracim.jsx
- functionnal_tests/cypress/integration/login/content_login_page.js
> fix(frontend): hide connection message if connection is closed

- tools_docker/Debian_Uwsgi/apache2.conf.sample
- tools_docker/Debian_Uwsgi/entrypoint.sh
> RequestHeader can't be apply in Apache Location

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
This MR updates the bug templates.
> Update bug templates

- backend/doc/cli.md
- backend/setup.py
- backend/tracim_backend/command/__init__.py
- backend/tracim_backend/command/database.py
> feat(backend): add db update-naming-conventions command to tracimcli

- backend/tracim_backend/lib/utils/authentification.py
- backend/tracim_backend/tests/functional/test_session.py
> Bugfix/3373  fix remote authentication

- frontend/src/reducer/currentWorkspace.js
- frontend/test/src/reducer/currentWorkspace.spec.js
- frontend_app_workspace_advanced/src/container/WorkspaceAdvanced.jsx
- frontend_app_workspace_advanced/test/src/container/WorkspaceAdvanced.spec.js
Warning: This PR is ready for review, but will be merge only after v3.0.0 release!!!
#3316 
> Fix/3316  handle user tlm at dashboard and adv dashboard

- frontend_app_admin_workspace_user/src/container/AdminWorkspaceUser.jsx
- frontend_app_admin_workspace_user/test/container/AdminWorkspaceUser.spec.js
> Fix/3335 Update AdminWorkspace when a user is removed from the workspace

- backend/cypress_test.ini
- frontend_app_file/src/container/PopupCreateFile.jsx
- frontend_app_html-document/src/container/PopupCreateHtmlDocument.jsx
- frontend_app_thread/src/container/PopupCreateThread.jsx
- functionnal_tests/cypress/integration/app_file/add_file_as_user_spec.js
- functionnal_tests/cypress/integration/app_thread/delete_content.js
> Feat/3185 Control the app redirection after creating a content with HTTP API return code

- frontend_app_workspace_advanced/src/css/index.styl
Warning: This PR is ready for review, but will be merge only after v3.0.0 release!!!
#3314 
Developer note: automated tests were not written because we can't test touch-pad touches with the current cypress architecture.
> fix horizontal scroll

- frontend_app_file/src/container/File.jsx
- frontend_app_file/test/component/File.spec.js
- frontend_app_folder_advanced/src/container/FolderAdvanced.jsx
- frontend_app_folder_advanced/test/container/FolderAdvanced.spec.js
- frontend_app_html-document/package.json
- frontend_app_html-document/src/container/HtmlDocument.jsx
- frontend_app_html-document/test/container/HtmlDocument.spec.js
- frontend_app_thread/package.json
- frontend_app_thread/src/container/Thread.jsx
- frontend_app_thread/test/container/Thread.spec.js
- frontend_app_workspace_advanced/src/container/WorkspaceAdvanced.jsx
- frontend_lib/src/appContentFactory.js
- frontend_lib/test/appContentFactory.spec.js
- yarn.lock
> Fix/3342 Update breadcrumbs and head title when a content is modified

- frontend_app_admin_workspace_user/package.json
- frontend_app_admin_workspace_user/src/container/AdminWorkspaceUser.jsx
- frontend_app_admin_workspace_user/test/apiMock.js
- frontend_app_admin_workspace_user/test/container/AdminWorkspaceUser.spec.js
- yarn.lock
> Fix/3363 Get a more specific message when adding user with a invalid password

- backend/tracim_backend/exceptions.py
- backend/tracim_backend/lib/core/content.py
- backend/tracim_backend/lib/core/user.py
- backend/tracim_backend/lib/core/workspace.py
- backend/tracim_backend/lib/mail_notifier/notifier.py
- backend/tracim_backend/lib/mail_notifier/sender.py
- backend/tracim_backend/lib/utils/logger.py
- backend/tracim_backend/lib/utils/utils.py
- backend/tracim_backend/models/context_models.py
- backend/tracim_backend/models/data.py
- backend/tracim_backend/tests/commands/test_commands.py
- backend/tracim_backend/tests/functional/test_user.py
- backend/tracim_backend/tests/library/test_user_api.py
- backend/tracim_backend/tests/models/test_user.py
- backend/tracim_backend/tests/utils.py
- backend/tracim_backend/views/core_api/schemas.py
- backend/tracim_backend/views/core_api/user_controller.py
#2830 
Some random cleanups and fixes related to types snicked in this MR.
> Feat/2830 (backend) Support include_workspace_ids in the known_members endpoint

- tools_docker/Debian_Uwsgi/common.sh
> fix(docker): set uwsgi configuration correctly for docker

- tools_docker/Debian_Uwsgi/Dockerfile
> fix(docker): use last pushpin version

- tools_docker/Debian_Uwsgi/common.sh
- tools_docker/Debian_Uwsgi/entrypoint.sh
> fix(docker):  move pushpin and redis log to docker volume

- backend/doc/apache.md
- backend/doc/setting.md
- tools_docker/Debian_Uwsgi/apache2.conf.sample
> fix(docker): fix non explicit regex about live_message in apache config

- tools_docker/Debian_Uwsgi/common.sh
> [for 3.0.0] fix(docker): add chmod command for zurl log file and fix wrong syntax

- backend/tracim_backend/lib/core/event.py
- backend/tracim_backend/models/context_models.py
- backend/tracim_backend/tests/functional/test_message.py
- backend/tracim_backend/views/core_api/schemas.py
- backend/tracim_backend/views/core_api/user_controller.py
> Feat/3374  number of read messages

- backend/doc/apache.md
> add documentation about how accessing old API path for public download with apache

- frontend_app_file/src/container/File.jsx
- frontend_app_html-document/src/component/HtmlDocument.jsx
- frontend_app_html-document/src/container/HtmlDocument.jsx
- frontend_app_html-document/test/container/HtmlDocument.spec.js
- frontend_lib/src/appContentFactory.js
- frontend_lib/src/helper.js
- frontend_lib/src/index.js
> Fix/3393 Fix wrong version number in html document app

- backend/pyproject.toml
- backend/tracim_backend/__init__.py
- backend/tracim_backend/applications/content_html_document/application.py
- backend/tracim_backend/applications/content_thread/application.py
- backend/tracim_backend/lib/core/event.py
- backend/tracim_backend/lib/core/mention.py
- backend/tracim_backend/lib/core/plugins.py
- backend/tracim_backend/lib/core/workspace.py
- backend/tracim_backend/lib/rq/worker.py
- backend/tracim_backend/lib/utils/request.py
- backend/tracim_backend/lib/webdav/middlewares.py
- backend/tracim_backend/migration/versions/5d3331933ef3_add_mention_in_entitytype_enum.py
- backend/tracim_backend/models/context_models.py
- backend/tracim_backend/models/event.py
- backend/tracim_backend/models/tracim_session.py
- backend/tracim_backend/tests/fixtures.py
- backend/tracim_backend/tests/functional/test_comments.py
- backend/tracim_backend/tests/functional/test_live_messages.py
- backend/tracim_backend/tests/library/test_event.py
- backend/tracim_backend/tests/library/test_mention.py
- backend/tracim_backend/tests/utils.py
- backend/tracim_backend/views/core_api/schemas.py
See #3347.
**Manual test method**
Manual tests of this PR must be done by viewing the `events` table contents as generating the messages is part of #3349. Inserting a mention can be done with:
```html
<span id="mention-12345">@TheAdmin</span>
```
Viewing table contents with `sqlite3`:
```sql
select * from events where entity_type="MENTION"
```
> Feature/3347  generate mentions

- backend/doc/apache.md
- tools_docker/Debian_Uwsgi/Dockerfile
- tools_docker/Debian_Uwsgi/apache2.conf.sample
- tools_docker/Debian_Uwsgi/common.sh
- tools_docker/Debian_Uwsgi/entrypoint.sh
- tools_docker/Debian_Uwsgi/uwsgi.ini.sample
> Fix/3383  uwsgi errors multiple requests

- backend/daemons/mail_fetcher.py
- backend/daemons/mail_notifier.py
- backend/development.ini.sample
- backend/doc/hello_world_plugin.py
- backend/doc/live_message_setup.md
- backend/doc/setting.md
- backend/requirements.txt
- backend/setup.py
- backend/setup_dev_env.py
- backend/tests_configs.ini
- backend/tracim_backend/config.py
- backend/tracim_backend/lib/core/live_messages.py
- backend/tracim_backend/tests/fixtures.py
- backend/tracim_backend/tests/functional/test_live_messages.py
- backend/tracim_backend/tests/utils.py
- backend/wsgi/caldav.py
- backend/wsgi/web.py
- backend/wsgi/webdav.py
- tools_docker/Debian_Uwsgi/Dockerfile
> Fix/3415  publish tlm with 0mq pushpin

- frontend/src/util/tinymceInit.js
- frontend_app_file/src/component/FileComponent.jsx
- frontend_app_file/src/container/File.jsx
- tools_docker/Debian_Uwsgi/Dockerfile
> Fix/3418  pushpin install

- frontend_app_admin_workspace_user/src/component/AdminUser.jsx
- frontend_app_admin_workspace_user/src/css/index.styl
- frontend_lib/src/component/Input/BtnSwitch/BtnSwitch.jsx
- frontend_lib/src/component/Input/BtnSwitch/BtnSwitch.styl
- functionnal_tests/cypress/integration/admin/content_admin_user.js
#3331 
Dev note: Automated tests aren't write because we don't have a way to test responsive interface at cypress yet.
> Fix/3331  redistribute column sizes

- frontend_app_admin_workspace_user/i18next.scanner/fr/translation.json
- frontend_app_admin_workspace_user/i18next.scanner/pt/translation.json
- frontend_app_admin_workspace_user/src/component/AddUserForm.jsx
> Fix/3250 (front) Remove '@' in placeholder in creation user page

- .travis.yml
- frontend_app_gallery/src/container/Gallery.jsx
- frontend_app_gallery/test/container/Gallery.spec.js
> Fix/3425 initialize folderId to undefined instead of 0 in the Gallery

- backend/requirements.txt
See #3436.
**Testing method**
Build a docker image with:
```bash
cd tools_docker/Debian_Uwsgi/
sudo docker build --no-cache .
```
> chore(backend): update packaging as its version is now incompatible with last wheel

- .travis.yml
- backend/requirements.txt
- backend/setup.cfg
- backend/tests_configs.ini
- backend/tracim_backend/lib/utils/authentification.py
- backend/tracim_backend/tests/functional/test_session.py
- changelog.md
- frontend/src/version.json
- frontend_app_admin_workspace_user/i18next.scanner/fr/translation.json
- frontend_app_admin_workspace_user/i18next.scanner/pt/translation.json
- frontend_app_admin_workspace_user/src/component/AddUserForm.jsx
- frontend_app_gallery/src/container/Gallery.jsx
- frontend_app_gallery/test/container/Gallery.spec.js
> New stable version of tracim: release_03.00.02

- backend/tracim_backend/models/context_models.py
- backend/tracim_backend/tests/functional/test_comments.py
- backend/tracim_backend/views/core_api/schemas.py
> feat(backend): add parent label in API comments

- backend/requirements.txt
- backend/setup.py
related to #3401 
repair one page pdf preview using new preview_generator version
note: this does not repair uncorrected preview already generated !
> fix(backend) repair one page pdf preview

- frontend/i18next.scanner/en/translation.json
- frontend/i18next.scanner/fr/translation.json
- frontend/i18next.scanner/pt/translation.json
- frontend/package.json
- frontend/src/container/Tracim.jsx
- frontend/src/container/WorkspaceContent.jsx
- frontend/src/util/LiveMessageManager.js
- frontend/test/.mocharc.js
- frontend/test/apiMock.js
- frontend/test/setup.js
- frontend/test/src/LiveMessageManager.spec.js
- yarn.lock
> Fix/3461  safeguard fetch

- backend/setup.cfg
- changelog.md
- frontend/src/version.json
> doc: prepare new stable release 3.0.4

- backend/tracim_backend/app_models/validator.py
- backend/tracim_backend/command/cleanup.py
- backend/tracim_backend/fixtures/users.py
- backend/tracim_backend/lib/utils/utils.py
- backend/tracim_backend/models/userconfig.py
- backend/tracim_backend/tests/commands/test_commands.py
- backend/tracim_backend/tests/functional/test_user_config.py
- backend/tracim_backend/views/core_api/schemas.py
- backend/tracim_backend/views/core_api/user_controller.py
> Fix/3451  strict user config validation

- install_frontend_dependencies.sh
> Chore/3473 Set Yarn 2 version to 2.1.1

- backend/requirements.txt
- backend/setup.cfg
- backend/setup.py
- changelog.md
- frontend/i18next.scanner/en/translation.json
- frontend/i18next.scanner/fr/translation.json
- frontend/i18next.scanner/pt/translation.json
- frontend/package.json
- frontend/src/container/Tracim.jsx
- frontend/src/container/WorkspaceContent.jsx
- frontend/src/util/LiveMessageManager.js
- frontend/src/version.json
- frontend/test/.mocharc.js
- frontend/test/apiMock.js
- frontend/test/setup.js
- frontend/test/src/LiveMessageManager.spec.js
- install_frontend_dependencies.sh
- yarn.lock
Brings the 3.0.4 fixes (#3461, #3401), and #3473.
**DO NOT MERGE WITH SQUASH&MERGE!!!**
> Merge 3.0.4 in develop

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/pull_request_template.md
Comment the help texts in github templates.
> Chore: comment help texts in the github templates

- backend/tracim_backend/migration/versions/41449c86b94b_add_cascade_to_events.py
- backend/tracim_backend/models/event.py
> add cascade between event and message

- frontend_app_html-document/src/container/HtmlDocument.jsx
- frontend_app_html-document/test/container/HtmlDocument.spec.js
- functionnal_tests/cypress/integration/app_html-document/notify_all_content_message_spec.js
> fix(frontend,html): display notify all message only when viewing

- backend/tracim_backend/lib/core/event.py
- frontend/src/action-creator.async.js
- frontend/src/container/ReduxTlmDispatcher.jsx
- frontend_lib/i18next.scanner/en/translation.json
- frontend_lib/i18next.scanner/fr/translation.json
- frontend_lib/i18next.scanner/pt/translation.json
- frontend_lib/src/helper.js
- frontend_lib/src/index.js
- frontend_lib/src/tracimComponent.js
- frontend_lib/src/tracimLiveMessage.js
- frontend_lib/test/helper.spec.js
#3528 (back and front fixes are in this PR)
> Fix/3528  handle notifications for anonymized and deleted users

- backend/setup.cfg
- changelog.md
- frontend/src/version.json
> doc: prepare new release 3.1.0

- frontend/src/component/Workspace/OpenContentApp.jsx
#3518
:warning: please check if this also fixes issue #3578
> Fix/3518 open files with the right workspace [3.1]

- frontend_lib/package.json
- frontend_lib/src/mention.js
- frontend_lib/test/mention.spec.js
- frontend_lib/test/setup.js
> Fix/3507 Prevent the mention wrapping logic from adding text after mentions

- backend/tracim_backend/app_models/validator.py
- backend/tracim_backend/lib/core/workspace.py
- backend/tracim_backend/migration/versions/37dfaf107e08_add_workspace_access_type_to_workspace.py
- backend/tracim_backend/models/context_models.py
- backend/tracim_backend/models/data.py
- backend/tracim_backend/tests/functional/test_workspaces.py
- backend/tracim_backend/views/core_api/schemas.py
- backend/tracim_backend/views/core_api/workspace_controller.py
- frontend_app_workspace/src/action.async.js
- functionnal_tests/cypress/fixtures/baseWorkspace.json
- functionnal_tests/cypress/integration/admin/content_admin_workspace.js
- functionnal_tests/cypress/support/db_commands.js
related to #3536 
Add access type to both workspace api and workspace database object
> Feature/3536  add access type parameter to space

- frontend/i18next.scanner/pt/translation.json
- frontend_lib/i18next.scanner/en/translation.json
- frontend_lib/i18next.scanner/fr/translation.json
- frontend_lib/i18next.scanner/pt/translation.json
- frontend_lib/src/component/NewMemberForm/NewMemberForm.jsx
- functionnal_tests/cypress/integration/workspace/add_members__as_admin_spec.js
- functionnal_tests/cypress/integration/workspace/add_members__unknown_users__as_user_wm_spec.js
> Fix/3562 Translation strings

- frontend/src/container/Tracim.jsx
- frontend/src/util/LiveMessageManager.js
#3524
I think we can write a test for this fix later to release 3.1.1 faster if you agree.
> Fix/3524  correctly handle disconnection reconnection

- frontend/src/util/tinymceInit.js
- frontend_app_html-document/src/container/HtmlDocument.jsx
- frontend_lib/src/appContentFactory.js
- frontend_lib/src/component/Timeline/CommentTextArea.jsx
- frontend_lib/src/index.js
- frontend_lib/src/tinymceAutoCompleteHelper.js
- functionnal_tests/cypress/integration/generic_frontend/operation_tinymce.js
#3548
tests here seem pretty hard to write. If you think we should give it a shot anyway, I'll write a ticket. 
> Fix/3548  various improvements for mention autocompletion

- frontend/src/util/LiveMessageManager.js
- frontend/test/setup.js
- frontend/test/src/LiveMessageManager.spec.js
#3547
:warning: this PR probably fixes the issues, but some discussions in the ticket are unresolved, so keep this in mind when reviewing this code.
> Fix/3547  avoid handling tlm twice in the frontend

- backend/setup.cfg
- changelog.md
- frontend/src/version.json
> doc: prepare new release 3.1.2

- frontend/src/container/ReduxTlmDispatcher.jsx
- frontend_app_html-document/src/container/HtmlDocument.jsx
- frontend_lib/test/component/CommentTextArea.spec.js
> Fix/3643  broken realtime notifications

- backend/setup.cfg
- changelog.md
- frontend/src/version.json
> doc: prepare new release 3.1.3

- backend/tracim_backend/__init__.py
- backend/tracim_backend/tests/functional/test_not_found.py
> fix some issue with non-dommable transaction

- frontend/src/util/LiveMessageManager.js
- frontend/test/setup.js
- frontend/test/src/LiveMessageManager.spec.js
#3547 
This was merged in develop by mistake, merging this into maintenance/3.1.
The code is already reviewed and tested on branch at https://github.com/tracim/tracim/pull/3558
> [For 3.1] Fix/3547  avoid handling tlm twice in the frontend

- backend/setup.cfg
- changelog.md
- frontend/src/version.json
> doc: prepare new release 3.1.4

- backend/setup.cfg
- changelog.md
- frontend/src/version.json
This merges maintenance/3.1 (3.1.4) in develop.
DO NOT SQUASH.
> Merge 3.1.4 in develop

- backend/tracim_backend/command/__init__.py
- backend/tracim_backend/command/cleanup.py
- backend/tracim_backend/lib/core/event.py
- backend/tracim_backend/lib/core/mention.py
- backend/tracim_backend/models/context_models.py
- backend/tracim_backend/tests/commands/test_commands.py
> [for 3.1.5] Fix/3685  force delete user

- backend/setup.cfg
- changelog.md
- frontend/src/version.json
> [for 3.1.5] doc: prepare new release 3.1.5

- backend/setup.cfg
- backend/tracim_backend/command/__init__.py
- backend/tracim_backend/command/cleanup.py
- backend/tracim_backend/lib/core/event.py
- backend/tracim_backend/lib/core/mention.py
- backend/tracim_backend/models/context_models.py
- backend/tracim_backend/tests/commands/test_commands.py
- changelog.md
- frontend/src/version.json
Brings the version 3.1.5 fixes in develop. The only fix is #3686.
**DO NOT MERGE WITH SQUASH!!**
> Merge 3.1.5 in develop

- backend/setup.cfg
- backend/tracim_backend/command/__init__.py
- backend/tracim_backend/command/cleanup.py
- backend/tracim_backend/lib/core/event.py
- backend/tracim_backend/lib/core/mention.py
- backend/tracim_backend/models/context_models.py
- backend/tracim_backend/tests/commands/test_commands.py
- changelog.md
- frontend/src/version.json
> Revert "Merge 3.1.5 in develop"

- backend/setup.cfg
- changelog.md
- frontend/src/version.json
> [for 3.2.0] doc: prepare new release 3.2.0

- .pre-commit-config.yaml
- backend/official_plugins/README.md
- backend/official_plugins/tracim_backend_autoinvite/README.md
- backend/official_plugins/tracim_backend_autoinvite/__init__.py
- backend/tracim_backend/lib/core/workspace.py
- backend/tracim_backend/models/data.py
- backend/tracim_backend/tests/fixtures.py
- backend/tracim_backend/tests/plugins/test_autoinvite_plugin.py
- backend/tracim_backend/tests/utils.py
related to #3604 
Original PR: https://github.com/tracim/tracim/pull/3721
> Feat/3604  add auto invite plugin

- frontend_lib/src/component/Button/IconButton.styl
> Fix/3765 IconButton height depends on it content

- backend/tracim_backend/lib/core/event.py
- backend/tracim_backend/tests/library/test_event.py
Even for OPEN/ON_REQUEST spaces
See #3763
> Fix/3763 member events are only sent to members + administrators

- frontend/src/component/Sidebar/WorkspaceListItem.jsx
> Fix/3771 Fix margin when space is active

- frontend/webpack.optimized.config.js
- frontend_app_admin_workspace_user/package.json
- frontend_app_admin_workspace_user/webpack.optimized.config.js
- frontend_app_agenda/webpack.optimized.config.js
- frontend_app_collaborative_document_edition/webpack.optimized.config.js
- frontend_app_custom-form/webpack.optimized.config.js
- frontend_app_file/webpack.optimized.config.js
- frontend_app_folder_advanced/webpack.optimized.config.js
- frontend_app_gallery/package.json
- frontend_app_gallery/webpack.optimized.config.js
- frontend_app_html-document/webpack.optimized.config.js
- frontend_app_share_folder_advanced/webpack.optimized.config.js
- frontend_app_thread/webpack.optimized.config.js
- frontend_app_workspace/webpack.optimized.config.js
- frontend_app_workspace_advanced/webpack.optimized.config.js
- frontend_lib/webpack.optimized.config.js
- frontend_vendors/README.md
- frontend_vendors/package.json
- frontend_vendors/src/index.js
- frontend_vendors/src/list.js
- frontend_vendors/webpack.list.config.js
> Fix/3776  list of vendors

- .travis.yml
> Fix/3779 Frontend unit tests in Travis

- frontend/src/component/Sidebar/WorkspaceListItem.jsx
- frontend/src/container/Sidebar.jsx
> Fix/3771  border active space should not move the title at sidebar

- backend/tracim_backend/applications/content_html_document/controller.py
- backend/tracim_backend/applications/content_thread/controller.py
- backend/tracim_backend/models/data.py
- backend/tracim_backend/tests/functional/test_contents.py
related to #3710 
previous PR : #3819
> add preview for html-document and thread

- backend/docker-compose.yml
- tools_docker/Debian_Uwsgi/Dockerfile
> fix(backend,docker): enforce pushpin version 1.30

- backend/tracim_backend/lib/core/event.py
- backend/tracim_backend/models/context_models.py
- backend/tracim_backend/tests/functional/test_message.py
- backend/tracim_backend/views/core_api/schemas.py
- backend/tracim_backend/views/core_api/user_controller.py
related to #3802 
previous PR : https://github.com/tracim/tracim/pull/3812
> Feature/3802  workspace filter for message endpoint

- README.md
- backend/docker-compose.yml
- tools_docker/Debian_Uwsgi/Dockerfile
> Fix/3836  define pushpin version

- frontend/src/reducer/currentWorkspace.js
- frontend/test/fixture/workspace/firstWorkspace.js
- frontend/test/src/reducer/currentWorkspace.spec.js
- frontend_app_workspace/i18next.scanner/pt/translation.json
- frontend_app_workspace_advanced/i18next.scanner/en/translation.json
- frontend_app_workspace_advanced/i18next.scanner/fr/translation.json
- frontend_app_workspace_advanced/i18next.scanner/pt/translation.json
- frontend_app_workspace_advanced/src/action.async.js
- frontend_app_workspace_advanced/src/component/WorkspaceAdvancedConfiguration.jsx
- frontend_app_workspace_advanced/src/container/WorkspaceAdvanced.jsx
- frontend_app_workspace_advanced/src/css/index.styl
- functionnal_tests/cypress/integration/app_workspace_advanced/operation_workspace_advanced.js
> Fix/3805  allow change default role

- README.md
- backend/setup.cfg
- changelog.md
- frontend/src/version.json
This brings the 3.2.2 changes in develop, mainly a small documentation update concerning pushpin's installation.
**DO NOT MERGE WITH SQUASH**
- ~~[ ] Manual, quality tests have been done~~ No need for testing here, only documentation changes coming from an already tested branch.
> Merge 3.2 2 in develop

- frontend/src/action-creator.sync.js
- frontend/src/component/Activity/ContentActivityHeader.styl
- frontend/src/component/Activity/MemberActivity.styl
- frontend/src/component/TimedEvent.styl
- frontend/src/container/ActivityFeed.jsx
- frontend/src/reducer/workspaceActivity.js
> fix(frontend,activity): right-align author

- frontend/dist/index.html
- frontend/dist/index.mak
- frontend/src/action-creator.async.js
- frontend/src/component/Activity/ContentWithPreviewActivity.jsx
- frontend/src/component/Activity/Preview.jsx
- frontend/src/component/Activity/Preview.styl
- frontend/src/container/ActivityFeed.jsx
- frontend/src/container/ReduxTlmDispatcher.jsx
- frontend/src/util/activity.js
- frontend/test/setup.js
- frontend/webpack.config.js
- frontend_app_file/src/component/PreviewComponent.styl
- frontend_lib/package.json
- frontend_lib/src/css/Variable.styl
- frontend_lib/src/helper.js
- frontend_lib/src/htmlRemoveInteractivity.js
- frontend_lib/src/index.js
- frontend_lib/src/screenSizes.json
- frontend_lib/test/htmlRemoveInteractivity.spec.js
- functionnal_tests/cypress/integration/activity_feed/workspace_activity_feed.spec.js
> Feat/3657 Activity feed previews

- frontend/src/component/Activity/Preview.styl
> Fix/3876 Update unavailable preview icon size and padding

- frontend/src/component/Activity/ActivityList.jsx
- frontend/src/container/PersonalActivityFeed.jsx
- frontend/src/container/WorkspaceActivityFeed.jsx
- frontend/src/container/withActivity.jsx
- functionnal_tests/cypress/integration/activity_feed/common.spec.js
> fix(frontend,activity): only show refresh button when it has an effect

- frontend/i18next.scanner/en/translation.json
- frontend/i18next.scanner/fr/translation.json
- frontend/i18next.scanner/pt/translation.json
- frontend/src/action-creator.async.js
- frontend/src/component/Activity/MemberActivity.jsx
- frontend/src/component/Activity/Preview.jsx
- frontend/src/component/Activity/Preview.styl
- frontend_app_file/test/component/File.spec.js
- frontend_app_html-document/src/component/HtmlDocument.jsx
- frontend_app_html-document/src/css/index.styl
- frontend_app_share_folder_advanced/test/setup.js
- frontend_lib/src/component/DistanceDate.jsx
- frontend_lib/src/component/HTMLContent/HTMLContent.jsx
- frontend_lib/src/component/HTMLContent/HTMLContent.styl
- frontend_lib/src/component/Layout/PageWrapper.jsx
- frontend_lib/src/component/Timeline/Comment.jsx
- frontend_lib/src/component/Timeline/Comment.styl
- frontend_lib/src/css/Variable.styl
- frontend_lib/src/helper.js
- frontend_lib/src/htmlRemoveInteractivity.js
- frontend_lib/src/index.js
- frontend_lib/test/helper.spec.js
> Feat/3874 Preview improvements

- backend/setup.cfg
- changelog.md
- frontend/src/version.json
Related to #3841 
- No Manual tests are necessary
> doc: prepare new release 3.3.0

- .github/pull_request_template.md
Everything is in the title.
- Manual, quality tests not necessary here.
> chore: add a checkbox for documentation in PR template

- frontend/src/component/Workspace/OpenContentApp.jsx
- frontend_app_file/src/container/File.jsx
- frontend_app_html-document/i18next.scanner/en/translation.json
- frontend_app_html-document/i18next.scanner/fr/translation.json
- frontend_app_html-document/i18next.scanner/pt/translation.json
- frontend_app_html-document/src/component/HtmlDocument.jsx
- frontend_app_html-document/src/container/HtmlDocument.jsx
- frontend_app_html-document/src/css/index.styl
- frontend_app_thread/src/container/Thread.jsx
- frontend_lib/i18next.scanner/en/translation.json
- frontend_lib/i18next.scanner/fr/translation.json
- frontend_lib/i18next.scanner/pt/translation.json
- frontend_lib/src/appContentFactory.js
- frontend_lib/src/component/ConfirmPopup/ConfirmPopup.jsx
- frontend_lib/src/component/Input/TextAreaApp/TextAreaApp.jsx
- frontend_lib/src/component/Timeline/Timeline.jsx
- frontend_lib/src/component/Timeline/Timeline.styl
- frontend_lib/src/index.js
- frontend_lib/src/mention.js
- frontend_lib/test/apiMock.js
- frontend_lib/test/appContentFactory.spec.js
- frontend_lib/test/mention.spec.js
- frontend_lib/test/setup.js
- functionnal_tests/cypress/integration/admin/content_admin_workspace.js
- functionnal_tests/cypress/integration/app_file/add_invalid_mentions_spec.js
- functionnal_tests/cypress/integration/app_html-document/add_invalid_mentions_spec.js
- functionnal_tests/cypress/integration/app_thread/add_invalid_mentions_spec.js
> Fix/3722 Add confirm popup to invalid mentions

- frontend/src/component/Login/FooterLogin.jsx
- frontend/src/container/Sidebar.jsx
> chore(frontend): update copyright to 2021

- .github/pull_request_template.md
> Chore: migration process in PR templates

- backend/setup.cfg
- changelog.md
- frontend/src/version.json
> chore: prepare 3.4.0 release
