tracim/tracim

- README.md
Little update of install process for python3.4. 
PS: I'm looking at docker usage for test installation process in "one docker command line": You can take a look [here](https://github.com/buxx/tracim/blob/dev/install/scripts/install/scripts/ubuntu_trusty.sh).
> Update README.md: specific install for >= python3.4

- tracim/tracim/public/assets/css/dashboard.css
add a bottom margin to left menu, so that last items in the menu are never hidden by the footer
> fix #83 - Last items of the left menu are hidden (behind the footer)

- tracim/tracim/controllers/content.py
- tracim/tracim/lib/content.py
Anciennement, l'usage de ``folder.get_valid_children`` faisait qu'on ne réutilisait pas la même "configuration" qu'avec l'instance de ``ContentApi``.
J'ai également du rajouter ``ContentApi.get_children``. Je voulais utiliser ``ContentApi.get_all`` mais elle ne permet de préciser qu'un seul ``ContentType``. Or le code actuel précise cette liste:
```
[
ContentType.Folder,
ContentType.File,
ContentType.Page,
ContentType.Thread,
]
```
> Closes #107: folder sub_items must be filtered (temporary, archived, …) to

- tracim/tracim/config/app_cfg.py
- tracim/tracim/lib/daemons.py
- tracim/tracim/lib/email.py
- tracim/tracim/lib/system.py
- tracim/tracim/lib/utils.py
Avec ces changements Tracim se ferme enfin correctement:
* Le worker RQ se termine également correctement: J'ai procédé à une astuce : on passe l'attribut du worker, dans le daemon,`_stop_requested` à vrai depuis le main thread. Et un surcharge dans le worker vérifie cet attribut entre chaque "traitement" de job. On fait par la suite faire au worker un job "bidon" (d'ailleurs il y a un job bidon à disposition dans le code de rq, à se demander si ça sert pas à un truc similaire), notre surcharge lève par la suite un StopRequested qui applique la procédure standard d'arrêt du worker.
* Une fois les démons arrétés on fait un kill sur le processus de tracim. Après avoir essayé de trouver un moyen de stopper "softwarement" le process du serveur WSGI je me suis randu compte que ce n'était …
> change stopping tracim strategy

- tracim/development.ini.base
- tracim/tracim/config/app_cfg.py
- radicale.client.base_url.host
Calendar url must start with "http://" to avoid caldavzap regex to fail.
- radicale.server.filesystem.folder
the fallback value "./radicale/collections" was misused somewhere after
initial configuration
Closes #273
> Setups properly Radicale by default

- tracim/tracim/templates/workspace/getone.mak
This allows to view archived or deleted folder in apparently empty
workspaces containing only archived or deleted folder.
Closes #367
> Enables filter for empty workspace

- tracim/tracim/lib/email.py
- tracim/tracim/lib/notifications.py
Use _formataddr_ from standard lib instead of homemade format for _To_ and _From_ Header in both notification mail and new user mail. Allow to use utf8 character and special character (like @) in "label" part of these header. 
double-quote (**"**) character is also escaped when needed.
Closes #490
> Better escaping for mail header with formataddr method

- install/requirements.txt
- tracim/development.ini.base
- tracim/tracim/config/app_cfg.py
- tracim/tracim/lib/daemons.py
- tracim/tracim/lib/email_fetcher.py
- Use imapclient instead of imaplib : more pythonic lib
- IDLE Imap feature option
- Don't recreate connection each time, stay in connection up to 'connection_max_lifetime'
- renaming : delay->heartbeat
- Better exceptions : more precise.
> Imapclient instead of imaplib as imap lib

- tracim/tracim/lib/email_fetcher.py
- Do not rely anymore on "seen" flag (buggy) for mail fetcher.
- Explicit Exception when strange behaviour of "fetch" command happend (see https://github.com/mjs/imapclient/issues/334)
> Mail fetcher rely only on checked flag.

- tracim/tracim/i18n/fr/LC_MESSAGES/tracim.po
membres (members) -> propose both genders
travaille -> typo (noun is travail)
my first PR :-)
> Fix 2 typos in French t10n

- tracim/tracim/lib/content.py
- tracim/tracim/lib/webdav/design.py
- tracim/tracim/lib/webdav/sql_resources.py
- tracim/tracim/model/__init__.py
- tracim/tracim/model/data.py
- tracim/tracim/tests/library/test_content_api.py
- tracim/tracim/tests/models/test_content_revision.py
Fix https://github.com/tracim/tracim/issues/540 .
**About contentAPI copy feature into tracim :**
Copy feature support copy of all type of document, copy are not exact copy, history and comments are not added to the copy. Copy is same as a special case of "creation" .
**About COPY and webdav**
Webdav support now COPY feature using copy method of tracim contentAPI.
In nautilus 3.26 , recursive COPY of folder work.
closes #540
closes #543
closes #552
> add copy method into tracim contentAPI and COPY support for webdav

- tracim/tracim/lib/webdav/sql_resources.py
Temporary fix for #550 . Disallow moving/creating file at root of workspace.
> disallow moving file at root for workspace

- tracim/tracim/lib/webdav/sql_resources.py
davfs2 need a working "LOCK" (Doing a lock create automatically an empty file) . As method to create empty file doesn't return a 'File' type, automatic creation of new file when "LOCK" inexistent file in wsgidav failed. 
Return a valid File in method to create empty file resolve this issue.
> WIP: Fix webdav for davfs2

- tracim/setup.py
- uppgrade_caldavzap.sh
Our Jenkins build is broken because test package missing in docker image. To permit install them, put them in setup.py and update docker_tracim (https://github.com/tracim/docker_tracim/pull/11)
> Permit install tests packages

- tools_docker/Debian_Uwsgi/Dockerfile
Add EXPOSE directive into Dockerfile, so metadata can provide the
listening port
Signed-off-by: Uggla <uggla@free.fr>
> Dockerfile "fix"

- backend/tracim_backend/lib/mail_notifier/notifier.py
related to #1183.
This fix 'async email' wrong log for reset and account generation, which are lacking in https://github.com/tracim/tracim/pull/1344 fix.
> remove wrong async email in log and variable

- backend/CHANGES.txt
- backend/cypress_test.ini
- backend/development.ini.sample
- backend/tests_configs.ini
- backend/tracim_backend/config.py
- backend/tracim_backend/lib/core/user.py
- changelog.md
related to [tracim/tracim#970](https://github.com/tracim/tracim/issues/970)
to do:
> Rename user.reset_password.validity to .token_validity

- tools_docker/Debian_Uwsgi/common.sh
If you have used volume before, development.ini file is not changed (you need to change this parameter manually).
> [#1226] fix wrong parameter for reply by email [ci skip]

- functionnal_tests/cypress/support/generic_selector_commands.js
#1826 adds 2 new function to format tags and a new cypress command to use instead of the usual `cy.get`
> front - adds new commands to format tags in cypress

- frontend/src/component/Header/MenuActionListItem/MenuProfil.styl
- frontend/src/container/Header.jsx
- frontend/src/container/Home.jsx
- frontend/src/css/Header.styl
- frontend/src/css/Home.styl
- frontend/src/css/index.styl
> Change e-mail message, dropdown menu and welcome message

- frontend/src/css/Sidebar.styl
#1891 
This issues seems to be related to the parent div which has `overflow: hidden` and the sidebar arrow has `position: fixed`, the sidebar arrow become hidden only on IOS.
This workaround have been found [here](https://stackoverflow.com/questions/29482203/iphone-fixed-position-div-invisible)
> [for 2.6.0] Fix hidden sidebar arrow on ios

- backend/tracim_backend/lib/core/content.py
- backend/tracim_backend/lib/mail_fetcher/email_fetcher.py
- backend/tracim_backend/lib/mail_notifier/notifier.py
- backend/tracim_backend/lib/mail_notifier/sender.py
- backend/tracim_backend/lib/utils/logger.py
- backend/tracim_backend/models/context_models.py
Related to #2812 
Done:
- refactor Logger
- remove all exception string value logging and replace them to exc_info=true option or logger.exception() method
:warning: **Reviewers**: please take time to reviews this code, this code change code for many error case that are not well tested because they does not occured in normal working Tracim, some are needed to ensure daemon does not failed at all for example. So, please have this in mind when reviewing this code, in order to avoid "broken code" that we don't see at all.
**For …
> [For 2.6.3] avoid logging exception string value, log traceback instead

- backend/development.ini.sample
- backend/doc/setting.md
- backend/tracim_backend/applications/share/lib.py
- backend/tracim_backend/applications/upload_permissions/lib.py
- backend/tracim_backend/config.py
- backend/tracim_backend/lib/mail_fetcher/email_fetcher.py
- backend/tracim_backend/lib/mail_notifier/notifier.py
- backend/tracim_backend/lib/mail_notifier/sender.py
- backend/tracim_backend/lib/mail_notifier/utils.py
- backend/tracim_backend/tests/functional/test_mail_notification.py
add a boolean config parameter `email.notification.use_implicit_ssl` to active implicit encryption for smtp (ssl over smtp, most of the time on port 465) and code needed to support this feature.
related to #2793 
> [For 2.6.3] fix(backend): add smtp implicit encryption support

- frontend_lib/src/component/FileDropzone/FileDropzone.jsx
Related to this fix: #2444 
Use `fa-upload` instead of `fa-download` in FileDropzone
> [For 2.7.0] Fix upload icon in FileDropzone

- .gitignore
- install_frontend_dependencies.sh
Related to #2918.
This allows using any installed version of yarn on the developer's system.
The fix consists in using command `yarn policies set-version berry` instead of `yarn set version berry` and checking that Yarn is not already version 2.
> fix(dep): support any installed version of yarn

- backend/pytest.ini
- backend/tests_configs.ini
- backend/tracim_backend/app_models/contents.py
- backend/tracim_backend/lib/core/event.py
- backend/tracim_backend/migration/versions/a074395d3caf_add_subtype_in_events_table.py
- backend/tracim_backend/models/event.py
- backend/tracim_backend/tests/functional/test_comments.py
- backend/tracim_backend/tests/functional/test_contents.py
- backend/tracim_backend/views/core_api/schemas.py
Adds an optional sub-type for events. This sub-type is used in content events to indicate the content's type.
Refs #3095.
> Feature/3095  content type in event type

- backend/requirements.txt
- backend/setup.py
- functionnal_tests/cypress/integration/app_gallery/app_gallery_spec.js
related to #3231 
PreviewGenerator 0.14 add lock feature that solve same preview generation case, we should use it to avoid problems with preview_generation
> Upgrade preview_generator to use lock

- backend/tests_configs.ini
- backend/tracim_backend/lib/utils/authentification.py
- backend/tracim_backend/tests/functional/test_session.py
See #3431 
Testing method: start the backend with a small cookie expiry date in `development.ini` (`session.cookie_expires = 30` for example). Then play with Tracim and check in the dev toobar that the cookie expiry date is extended properly.
> fix(backend): ensure cookie expiry date is extended when too old

- README.md
Replace travis status url to show real status of CI used by tracim since migratation from travis-ci.org to travis-ci.com [skip ci]
> doc: change travis status url

- frontend_app_collaborative_document_edition/test/PopupCreateOfficeDocument.spec.js
- frontend_app_file/test/component/File.spec.js
- frontend_app_folder_advanced/test/container/FolderAdvanced.spec.js
- frontend_app_html-document/test/container/HtmlDocument.spec.js
- frontend_app_share_folder_advanced/test/container/ShareFolderAdvanced.spec.js
- frontend_app_thread/test/container/Thread.spec.js
- frontend_app_workspace_advanced/test/src/container/WorkspaceAdvanced.spec.js
#3712 broke the frontend unit tests. This PR fixes this.
> Fix unit tests in develop

- frontend/src/util/activity.js
- frontend/test/apiMock.js
- frontend/test/src/activity.spec.js
See #3852 
[skip ci pytest]
- ~~[ ] Manual, quality tests have been done~~: as reproducing the error in a real situation is difficult I would test it directly on our pre-production (as we have a content triggering this error inside).
> fix(frontend,activity): handle case of a comment message with unavailable parent content

- .pre-commit-config.yaml
- .travis.yml
- backend/official_plugins/tracim_backend_child_removal/__init__.py
- backend/requirements-devtool.txt
- backend/setup.py
- backend/setup_dev_env.py
- backend/tracim_backend/lib/core/application.py
- backend/tracim_backend/lib/rq/worker.py
- backend/tracim_backend/migration/versions/5d3331933ef3_add_mention_in_entitytype_enum.py
- backend/tracim_backend/migration/versions/a074395d3caf_add_subtype_in_events_table.py
- backend/tracim_backend/migration/versions/fb2ae8c604ac_add_undelete_operation_type_in_enum.py
- backend/tracim_backend/tests/plugins/test_child_removal_plugin.py
This is easier to launch: `flake8` for only checking and also simplifies the CI (only one job for linting).
> feat(backend): add black and isort plugins to flake8

- .travis.yml
- backend/README.md
- backend/tracim_backend/lib/core/content.py
Introduce preview_generator cache for non-local storage like s3.
related to #4000 
previous PR: https://github.com/tracim/tracim/pull/4005
> add support for preview_generator cache for non-local storage type

- backend/tracim_backend/views/frontend.py
- frontend/src/container/PublicProfile.jsx
- frontend_lib/src/component/FileDropzone/FileDropzone.jsx
- frontend_lib/src/container/PopupUploadFile.jsx
See #4101
And use blobs for previewing the image in the browser.
**Testing method**
Try to upload an image >1MB but <10MB, it should be possible. With an image >10MB the popup should refuse to upload the file.
Check that the preview of the image is properly displayed.
> fix(frontend, public-profile): File size limit upgraded to 10MB

- frontend_app_agenda/src/css/index.styl
#3553
Moved the refresh button to the right, next to the title. 
In order to make the refresh button appear on the calendar, edit one of the space's title in another page. 
> moved refresh button to the right [skip ci pytest]

- backend/tracim_backend/lib/core/event.py
- backend/tracim_backend/migration/versions/35cfa7c2f8f9_remove_workspace_description_from_non_.py
- backend/tracim_backend/tests/functional/test_comments.py
- backend/tracim_backend/tests/functional/test_contents.py
- backend/tracim_backend/tests/functional/test_reactions.py
- backend/tracim_backend/tests/functional/test_workspace_subscription.py
- backend/tracim_backend/tests/functional/test_workspaces.py
- backend/tracim_backend/views/core_api/schemas.py
See #4557.
- Before using this PR's branch, create a space with a description including an image. Add some contents to it.
- Check the time (and size of `messages` response) when displaying the recent activities of the space. Browsers include a throttle capability in devtools to decrease the download speed.
- Checkout this branch and restart `./run_dev_backend.sh`. Check that the time and size of `messages` response has dropped.
- Add other contents and recheck
- Navigate to the …
> fix(backend): remove workspace description from events

- backend/tracim_backend/locale/de/LC_MESSAGES/tracim_backend.po
- backend/tracim_backend/locale/en/LC_MESSAGES/tracim_backend.po
- backend/tracim_backend/locale/fr/LC_MESSAGES/tracim_backend.po
- backend/tracim_backend/locale/pt/LC_MESSAGES/tracim_backend.po
- backend/tracim_backend/templates/mail/reset_password_body_html.mak
- backend/tracim_backend/tests/functional/test_mail_notification.py
- frontend/i18next.scanner/de/translation.json
- frontend/i18next.scanner/en/translation.json
- frontend/i18next.scanner/fr/translation.json
- frontend/i18next.scanner/pt/translation.json
- frontend/src/container/ResetPassword.jsx
See #4759
**Testing method**
- Start the backend with:
```shell
cd backend
docker-compose up -d
export TRACIM_EMAIL__NOTIFICATION__FROM__EMAIL=test@test.te
export TRACIM_EMAIL__NOTIFICATION__REPLY_TO__EMAIL=test@test.te
export TRACIM_EMAIL__NOTIFICATION__REFERENCES__EMAIL=test@test.te
export TRACIM_EMAIL__NOTIFICATION__ACTIVATED=True
export TRACIM_EMAIL__NOTIFICATION__SMTP__SERVER=localhost
export TRACIM_EMAIL__NOTIFICATION__SMTP__PORT=1025
export …
```
> fix(frontend, backend): add link lifetime to mail + proper message

- .travis.yml
This modification can decrease response time from CI by 2. If just one PR need test, we can have all test done in 50min, if more than one PR the time can be egal to the last ci workflow (so near 90min).
All skip command work and the other modification is all test are done also if quick-test an unit-test failed, but in many PR, this kind of test finish with good result. 
This modification can use also all 5 job available with commercial plan (before, we just have 4 job in the same time).
**For …
> feat(ci): improve ci test time before using concourse

- backend/tracim_backend/lib/search/elasticsearch_search/es_models.py
Can help to avoid errors if a field contains too big tokens.
See #5055 (even if the issue's error was due to a mis-configuration and can be corrected by changing the configuration).
> Ensure a maximum length for tokens when indexing in elasticsearch

- frontend/src/component/NotificationItem.jsx
- frontend/src/container/GroupedNotificationItem.jsx
- frontend/src/container/NotificationWall.jsx
- frontend/src/css/NotificationWall.styl
- functionnal_tests/cypress/integration/notification_wall/mark_as_read_spec.js
Issue #3361
Add a handle for a click on the notification circle (see issue)
Behavior for group notification -> Open the group and read put everything as read
This PR doesn't implement any tooltip. My thought was "we got this button/action on every items, if we put a tooltip on each, the user will be overwhelmed".
> Feat(frontent): New click handle on circle notification to read it without being redirected

- backend/doc/live_messages.md
- backend/tracim_backend/applications/content_file/controller.py
- backend/tracim_backend/models/context_models.py
- backend/tracim_backend/tests/functional/test_contents.py
- backend/tracim_backend/views/core_api/schemas.py
- frontend_app_file/src/container/File.jsx
- frontend_app_file/test/component/File.spec.js
- frontend_app_gallery/src/container/Gallery.jsx
- frontend_app_gallery/test/apiMock.js
- frontend_app_gallery/test/component/Gallery.spec.js
- frontend_app_gallery/test/container/Gallery.spec.js
- frontend_app_gallery/test/setup.js
- frontend_lib/src/action.async.js
- frontend_lib/src/index.js
- functionnal_tests/cypress/integration/app_file/switch_between_file_spec.js
Done by moving preview-related infos to a specific endpoint.
And removing them from the generated TLM (content.modified).
See #5495
-------
Hints for testing: play with the file and gallery apps (as they were both impacted), the fix itself can be checked by uploading the same file with the code on develop and this branch, then notice the time the upload popup stays open with `99%` progress. Good candidate files are office files as they take a relatively long time to be previewed.
> fix(file): Avoid computing the preview while uploading a file.

- backend/development.ini.sample
- backend/doc/env_settings.md
- backend/doc/setting.md
- backend/tests_configs.ini
- backend/tracim_backend/applications/share/lib.py
- backend/tracim_backend/applications/upload_permissions/lib.py
- backend/tracim_backend/command/devtools.py
- backend/tracim_backend/config.py
- backend/tracim_backend/lib/mail_notifier/notifier.py
- backend/tracim_backend/lib/mail_notifier/sender.py
- backend/tracim_backend/lib/mail_notifier/utils.py
- backend/tracim_backend/tests/functional/test_mail_notification.py
YunoHost include a postfix smtp server. And as almost servers, it allows to send mail to local users anonymously
Tested on YunoHost, when creating a user in tracim, YunoHost user receive the invitation mail
Fixe #2954
> Allow anonymous smtp authentication

- frontend_lib/src/container/PopupUploadFile.jsx
- functionnal_tests/cypress/integration/app_file/add_file_error_messages_spec.js
- functionnal_tests/cypress/support/urls_commands.js
#3497
Now displaying a more specific message if a file upload fails, note that in the case of more than one erroneous file the generic message is displayed. This is also the case when XHR crashes.
> feat(frontend): displaying a more specific message if a file upload fails

- frontend/src/container/FeedItemWithPreview.jsx
- functionnal_tests/cypress/integration/activity_feed/activity_spec.js
> fix(frontend): No content preview on news when it's content is a file in the dashboard

- backend/tracim_backend/lib/core/content.py
- backend/tracim_backend/lib/core/event.py
- frontend/src/action-creator.sync.js
- frontend/src/container/NotificationWall.jsx
- frontend/src/container/ReduxTlmDispatcher.jsx
- frontend/src/reducer/notificationPage.js
- frontend/test/src/reducer/notificationPage.spec.js
Issue #5940
The filter is done only in the client (frontend) twice.
An issue has been created to uniform the filters (see #5946).
> fix(frontend): do not display task notification if you are not the assignee

- frontend/dist/index.mak
https://github.com/tracim/tracim/issues/6006
This pr fixes an issue from https://github.com/tracim/tracim/pull/6010
The issue was that the emoji library from tinymce was loading the emoji database on the fly upon clicking on the emoji button. But was trying to load the library without including the csp and got blocked …
> fix(front): add emoji library using the cache token and the csp

- backend/tracim_backend/hookspec.py
- backend/tracim_backend/lib/core/content.py
- backend/tracim_backend/lib/core/event.py
- backend/tracim_backend/lib/utils/request.py
- backend/tracim_backend/lib/webdav/resources.py
- backend/tracim_backend/migration/versions/b7aa3b477519_add_copied_and_moved_operation_type.py
- backend/tracim_backend/models/event.py
- backend/tracim_backend/tests/library/test_content_api.py
- doc/backend_specific/live_messages.md
- frontend/src/component/FeedItem/FeedItemHeader.jsx
- frontend/src/container/FeedItemWithPreview.jsx
- frontend_app_file/src/container/File.jsx
- frontend_app_html-document/src/container/HtmlDocument.jsx
- frontend_app_kanban/src/container/Kanban.jsx
- frontend_app_thread/src/container/Thread.jsx
- frontend_lib/src/appContentFactory.js
- frontend_lib/src/component/DropdownMenu/DropdownMenu.jsx
- frontend_lib/src/component/TimedEvent/TimedEvent.jsx
- frontend_lib/src/tracimLiveMessage.js
Disable event creation (TLMs) during a copy and send only one event (TLM) after the copy is finished.
Reduce the amount of API calls for a modified commentary (regression during #5846)
Issue linked #6068 
> Fix(backend, frontend): reduce the number of communication during a copy from webdav

- frontend_lib/src/component/TinyEditor/TinyEditor.jsx
Autocompletion no longer gives a js error if someone doesn't have a username
> fix(frontend): error js with mention autocompletion

- frontend_lib/src/component/TinyEditor/TinyEditor.jsx
The user can still select to open in the same window when using the
advanced edition's link button.
Ref #5546
-------
> fix(tinymce): open links in external window/tab

- tools_docker/Debian_New_Uwsgi/entrypoint.sh
- tools_docker/Debian_Uwsgi/entrypoint.sh
- tools_docker/Debian_Uwsgi_ARM64/entrypoint.sh
Related to #6157 
This fix add verification before uwsgi start, to make sure redis-server, pushpin and zurl services works. If not, starting of tracim docker images is stopped. An error message is visible in docker logs.
Error visible for each services.
- [17:02:14] $ Redis service must be running.
- [17:10:16] $ Pushpin service must be running.
- [17:12:46] $ Zurl service must be running.
- ~~Automated tests covering the feature or the fix, have been written, deemed irrelevant (give the reason), or an issue has been created to implement the test (give the link)~~
- Make sure that:
- ~~if there are modifications in the Tracim configuration files (eg. `development.ini`), they are documented in `backend/doc/setting.md`~~
- ~~any migration process required for existing …
> fix(docker): check if services running before starting tracim

- frontend/src/component/PublicProfile/CustomFormManager.jsx
- frontend_app_html-document/src/container/HtmlDocument.jsx
no related issue
It is to fix the code highlight language list in app note that was empty since release_04.05.00
> fix(front): add list of handled code language highligh for app note

- frontend_lib/src/component/TinyEditor/TinyEditor.jsx
To enable correct performance when base64 images are inserted.
Issue Ref: #4591
Coming from https://github.com/tracim/tracim/pull/6199 but with `develop` as target branch.
> fix(frontend, tinymce): re-introduce workaround for Chrome

- frontend_app_admin_workspace_user/src/component/AdminWorkspace.jsx
- frontend_app_admin_workspace_user/src/container/AdminWorkspaceUser.jsx
- frontend_app_admin_workspace_user/src/css/index.styl
Issue #3953
Replace the javascript events by html links in admin spaces list
I could not run the pre-commit scripts because of requirement of https://gitlab.com/pycqa/flake8.git/ which doesn't seems to exists
- See https://github.com/tracim/tracim/pull/6149#issuecomment-1521393369
> fix(frontend): links instead of js events in admin

- backend/tracim_backend/views/core_api/user_controller.py
https://github.com/tracim/tracim/issues/6271 
fix the list of setting returned by the backend in the setting endpoint to not return setting from workspace deleted
> fix(backend) : fix the list of setting returned by the backend

- frontend_app_kanban/src/component/KanbanCard.jsx
- frontend_app_logbook/src/component/LogbookEntry.jsx
- frontend_app_logbook/src/component/LogbookEntry.styl
https://github.com/tracim/tracim/issues/6522
https://github.com/tracim/tracim/issues/5270
also fix a kanban issue about the see more button not appearing on description change
> feat(front): add preview of logbook entry description and see more button
