tracim/tracim

backend/development.ini.sample
tools_docker/Debian_New_Uwsgi/common.sh
tools_docker/Debian_Uwsgi/common.sh

See #3979.
**Testing Method**
- build the docker image from this PR's branch:
```
cd tools_docker/Debian_Uwsgi/
docker build --no-cache --build-arg BRANCH=fix/3979__docker_run -t algoo/tracim:fix .
```
- run this image:
```
docker run -p 8080:80 --rm --name fix -e DATABASE_TYPE=sqlite algoo/tracim:fix
```
- check that tracim is accessible on http://localhost:8080 and is functional (login, upload a file)

fix(backend,docker): fix new docker container launch

---

backend/setup.cfg
changelog.md
frontend/src/version.json

chore: preparing version 3.4.1

---

.travis.yml

chore: mitigating docker limitations

---

frontend/src/component/Home/HomeNoWorkspace.jsx
frontend/src/container/NotificationWall.jsx

Fix/3785 do not display notification if it's accepted request

---

backend/doc/setting.md

Document how to delete all sessions for both file and redis storage

---

backend/tracim_backend/applications/collaborative_document_edition/application.py
backend/tracim_backend/lib/utils/app.py
backend/tracim_backend/tests/functional/test_frontend.py
backend/tracim_backend/views/frontend.py

Fix/3997  csp collabora

---

backend/official_plugins/tracim_backend_child_removal/__init__.py
backend/setup.py
backend/tracim_backend/applications/agenda/application.py
backend/tracim_backend/applications/collaborative_document_edition/application.py
backend/tracim_backend/lib/utils/app.py

Feat/4033  add self to frame src for calendars

---

backend/setup.cfg
changelog.md
frontend/src/version.json

Related to #4034 
- No manual test necessary

doc: prepare new stable release 3.4.3

---

frontend/src/component/Workspace/OpenContentApp.jsx
frontend/src/component/Workspace/OpenShareFolderApp.jsx
frontend/src/container/WorkspaceContent.jsx
frontend/src/util/appInterface.js
frontend/test/src/component/OpenContentApp.spec.js
frontend/webpack.config.js
frontend_app_custom-form/src/container/PopupCreateCustomForm.jsx
frontend_lib/src/appContentFactory.js
frontend_lib/src/customEvent.js
functionnal_tests/cypress/integration/app_interface/switching_different_apps_feature_spec.js
functionnal_tests/cypress/integration/app_interface/switching_same_apps_feature_spec.js

Fix/3578 switch between workspaces, same app

---

backend/doc/setting.md

doc: fix broken link related to custom properties

---

backend/tracim_backend/tests/functional/test_frontend.py
backend/tracim_backend/views/frontend.py

Related to #4039 
Tuning CSP for this new dependency.

fix(backend): tune CSP for react-jsonschema-form dependency

---

frontend/src/container/PublicProfile.jsx
frontend/webpack.config.js
frontend_app_gallery/build_gallery.sh

Fix/4104 Gallery app in dev mode

---

backend/development.ini.sample
backend/doc/user_custom_properties.md
backend/tests_configs.ini

better naming and doc for user.custom_properties.dir shortcut

---

.travis.yml
frontend/src/component/PublicProfile/CustomFormManager.jsx
functionnal_tests/cypress/fixtures/baseOtherUser.json
functionnal_tests/cypress/integration/profile/edit_react_json_schema_form.js

https://github.com/tracim/tracim/issues/4105

fix(front): set <Form /> (rjsf) as a controlled component

---

frontend/src/util/activity.js
frontend/test/src/activity.spec.js

Fix/4109 Null check in the activity feed component

---

backend/tracim_backend/applications/agenda/authorization.py
backend/tracim_backend/exceptions.py
backend/tracim_backend/lib/core/user.py
backend/tracim_backend/lib/utils/authorization.py
backend/tracim_backend/tests/library/test_authorization_checker.py

Fix(backend): Consistent known user rule: Allow both admin and trusted user to get access to user public profile

---

backend/development.ini.sample
backend/doc/user_custom_properties.md
backend/examples/user_custom_properties/default/data_sample.json
backend/examples/user_custom_properties/default/locale/en.json
backend/examples/user_custom_properties/default/locale/fr.json
backend/examples/user_custom_properties/default/locale/pt.json
backend/examples/user_custom_properties/default/schema.json
backend/examples/user_custom_properties/default/ui.json
backend/examples/user_custom_properties/organization/locale/fr.json

add better default example for jsonschema

---

frontend/src/container/PublicProfile.jsx
frontend/webpack.config.js

Fix/4128 Ensure we do not dereference undefined in the public profile

---

backend/examples/user_custom_properties/organization/schema.json
frontend/src/component/PublicProfile/CustomFormManager.jsx
functionnal_tests/cypress/integration/profile/edit_react_json_schema_form.js

update personal page title to space and frontend to handle it

---

frontend/src/container/PublicProfile.jsx
frontend/test/src/container/PublicProfile.spec.js
yarn.lock

Fix/4102  hide edit button when empty json at profile

---

backend/tracim_backend/lib/core/mention.py

Handle case where mention is not more related to an existing user

---

backend/tracim_backend/tests/functional/test_frontend.py
backend/tracim_backend/views/frontend.py

Fix/4142 allow * in frame-src

---

backend/tracim_backend/lib/core/event.py
backend/tracim_backend/tests/library/test_event.py

fix(backend): spaces without access_type are CONFIDENTIAL

---

backend/tracim_backend/lib/core/user.py
backend/tracim_backend/tests/functional/test_user.py

fix avatar and cover bug related to user without avatar

---

.travis.yml
backend/tracim_backend/config.py
backend/tracim_backend/templates/user_custom_properties/default/locale/fr.json
backend/tracim_backend/tests/functional/test_system.py
frontend/src/component/Workspace/ContentItem.jsx
frontend_lib/src/component/ShareLink/ShareLink.jsx

Fix/Quick: icons and the Travis configuration

---

frontend/src/css/NotificationWall.styl

fix/3791 add word-break on notification message

---

.github/pull_request_template.md

misc(github): add procedure for merging long-lived branches.

---

backend/docker-compose.yml
backend/tracim_backend/command/search.py
backend/tracim_backend/lib/search/elasticsearch_search/elasticsearch_search.py
backend/tracim_backend/lib/search/search.py
backend/tracim_backend/lib/search/simple_search/simple_search_api.py

Fix index populate

---

backend/tracim_backend/lib/search/elasticsearch_search/elasticsearch_search.py
backend/tracim_backend/lib/search/elasticsearch_search/models.py
backend/tracim_backend/lib/search/models.py
backend/tracim_backend/tests/functional/test_elasticsearch_search.py
backend/tracim_backend/views/core_api/schemas.py
backend/tracim_backend/views/search_api/schemas.py

Misc/4094  fixes and tests

---

backend/README.md
backend/tests_configs.ini
backend/tracim_backend/lib/core/content.py
backend/tracim_backend/lib/core/event.py
backend/tracim_backend/lib/mail_notifier/daemon.py
backend/tracim_backend/lib/mail_notifier/sender.py
backend/tracim_backend/lib/rq/__init__.py
backend/tracim_backend/lib/rq/worker.py
backend/tracim_backend/lib/search/elasticsearch_search/elasticsearch_search.py
backend/tracim_backend/tests/fixtures.py
backend/tracim_backend/tests/functional/test_mail_notification.py
backend/tracim_backend/tests/functional/test_share_content.py
backend/tracim_backend/tests/functional/test_upload_permission.py
backend/tracim_backend/tests/library/test_elasticsearch.py
backend/tracim_backend/tests/library/test_rq.py
backend/tracim_backend/tests/utils.py
tools_docker/Debian_New_Uwsgi/supervisord_tracim.conf
tools_docker/Debian_Uwsgi/supervisord_tracim.conf

Feat/4149  async es indexing

---

backend/tracim_backend/lib/translate/services/systran.py
backend/tracim_backend/lib/translate/translator.py
backend/tracim_backend/tests/library/test_translator.py

Add translation encapsulation with systran support

---

backend/tracim_backend/lib/search/elasticsearch_search/elasticsearch_search.py
backend/tracim_backend/lib/search/elasticsearch_search/es_models.py
backend/tracim_backend/tests/functional/test_elasticsearch_search.py

fix(backend, search): index content description

---

frontend_app_file/src/container/File.jsx
frontend_app_html-document/i18next.scanner/en/translation.json
frontend_app_html-document/i18next.scanner/fr/translation.json
frontend_app_html-document/i18next.scanner/pt/translation.json
frontend_app_html-document/src/component/HtmlDocument.jsx
frontend_app_html-document/src/container/HtmlDocument.jsx
frontend_app_html-document/src/helper.js
frontend_app_html-document/test/component/HtmlDocument.spec.js
frontend_app_thread/src/container/Thread.jsx
frontend_lib/i18next.scanner/en/translation.json
frontend_lib/i18next.scanner/fr/translation.json
frontend_lib/i18next.scanner/pt/translation.json
frontend_lib/src/action.async.js
frontend_lib/src/appContentFactory.js
frontend_lib/src/component/Button/TranslateButton.jsx
frontend_lib/src/component/Button/TranslateButton.styl
frontend_lib/src/component/HTMLContent/HTMLContent.jsx
frontend_lib/src/component/HTMLContent/HTMLContent.styl
frontend_lib/src/component/Timeline/Comment.jsx
frontend_lib/src/component/Timeline/Comment.styl
frontend_lib/src/component/Timeline/Timeline.jsx
frontend_lib/src/helper.js
frontend_lib/src/index.js
frontend_lib/src/translation.js
frontend_lib/test/appContentFactory.spec.js
frontend_lib/test/component/TranslateButton.spec.js
functionnal_tests/cypress/integration/app_html-document/translate_document.spec.js
functionnal_tests/cypress/integration/generic_frontend/translate_comment.spec.js
run_dev_backend.sh
yarn.lock

Feat/4063  comments translation

---

frontend/dist/assets/_caldavzap/index.tracim.html
frontend_app_agenda/src/container/Agenda.jsx
frontend_app_custom-form/src/container/CustomForm.jsx
frontend_app_gallery/src/container/Gallery.jsx

Fix/4177 Fullscreen icons in the gallery and the agendas

---

frontend_lib/src/component/Timeline/Revision.jsx
frontend_lib/src/helper.js
yarn.lock

fix(frontend): fix icons and icon titles in the timeline

---

backend/tracim_backend/command/search.py
backend/tracim_backend/tests/functional/test_elasticsearch_search.py

related to #4200 (explanation here: https://github.com/tracim/tracim/issues/4200#issuecomment-790473935)

force jobs processing mode to sync for index-populate command

---

frontend/src/css/NotificationWall.styl
yarn.lock

Fix/3543  consistent borders for notification wall

---

backend/development.ini.sample
backend/doc/setting.md
backend/tracim_backend/applications/content_html_document/controller.py
backend/tracim_backend/config.py
backend/tracim_backend/lib/translate/providers.py
backend/tracim_backend/lib/translate/services/systran.py
backend/tracim_backend/lib/translate/translator.py
backend/tracim_backend/views/contents_api/comment_controller.py

Fix/4237  same language translation

---

frontend/src/action-creator.async.js
frontend/src/component/Search/ContentItemSearch.jsx
frontend/src/component/Search/DateFilter.jsx
frontend/src/component/Search/SearchInput.jsx
frontend/src/container/AdvancedSearch.jsx
frontend/src/container/SearchFilterMenu.jsx
frontend/src/css/AdvancedSearch.styl
frontend/src/util/helper.js
frontend/test/hocMock/redux/searchResult/searchResult.js
frontend/test/src/container/AdvancedSearch.spec.js
frontend/test/src/container/NotificationWall.spec.js
frontend_app_file/src/debug.js.sample
frontend_lib/package.json
frontend_lib/src/component/FilenameWithExtension/FilenameWithExtension.jsx
frontend_lib/src/helper.js
frontend_lib/src/index.js
frontend_vendors/package.json
yarn.lock

See #4224 (8th, 17th, 19th and 20th tasks).

Fix/4224  search fixes 8 17 19 20

---

backend/doc/migration.md
backend/tracim_backend/applications/content_file/controller.py
backend/tracim_backend/migration/env.py
backend/tracim_backend/migration/versions/78a01733957f_add_publication_namespace.py
backend/tracim_backend/models/context_models.py
backend/tracim_backend/models/data.py
backend/tracim_backend/tests/functional/test_contents.py
backend/tracim_backend/tests/functional/test_workspaces.py
backend/tracim_backend/views/core_api/schemas.py
backend/tracim_backend/views/core_api/workspace_controller.py

Feat/4263  publication namespace

---

backend/tracim_backend/command/search.py
backend/tracim_backend/exceptions.py
backend/tracim_backend/lib/search/elasticsearch_search/elasticsearch_search.py
backend/tracim_backend/tests/library/test_elasticsearch.py

fix(backend, search): do not stop on first error.

---

backend/tracim_backend/lib/search/elasticsearch_search/elasticsearch_search.py

Fix/4292  multiple create index

---

backend/requirements.txt
backend/tracim_backend/lib/core/content.py
backend/tracim_backend/lib/utils/authentification.py
backend/tracim_backend/models/context_models.py
backend/tracim_backend/models/utils.py
backend/tracim_backend/tests/functional/test_upload_permission.py
backend/tracim_backend/tests/functional/test_workspaces.py
backend/tracim_backend/views/core_api/schemas.py
backend/tracim_backend/views/core_api/workspace_controller.py
frontend/src/container/WorkspaceContent.jsx
frontend_app_gallery/src/container/Gallery.jsx

See #4264.
~~N.B.: the SQLite tests won't be green because of https://github.com/djrobstep/sqlakeyset/issues/48.~~

feat(backend, publication): add sort and pagination to contents endpoint

---

backend/tracim_backend/app_models/contents.py
backend/tracim_backend/applications/content_file/application.py
backend/tracim_backend/applications/content_folder/application.py
backend/tracim_backend/applications/content_html_document/application.py
backend/tracim_backend/applications/content_thread/application.py
backend/tracim_backend/lib/utils/app.py
backend/tracim_backend/migration/versions/ae30497b6168_taking_care_of_moved_contents_properties.py
backend/tracim_backend/models/data.py
backend/tracim_backend/tests/functional/test_contents.py
backend/tracim_backend/tests/functional/test_workspaces.py
backend/tracim_backend/tests/library/test_application_api.py
backend/tracim_backend/tests/library/test_content_api.py

See #4266.
:warning: don't forget to put the migration revisions with #4278 in sequence.

Feat/4266  sub content types

---

frontend/src/action-creator.async.js
frontend/src/container/AdvancedSearch.jsx

fix date format: https://github.com/tracim/tracim/issues/4300
~~increase search result number: workaround of https://github.com/tracim/tracim/issues/4299~~
the search result number hasn't been increased. A better fix has been found here https://github.com/tracim/tracim/pull/4301/commits/6fe78e20430af1f43484acf4a4dfddc54b5a783f
:warning: Be advised that this PR points to maintenance/3.6

fix(front): fix iso format of date range sent to api for advanced search + increase number of results

---

backend/tracim_backend/migration/env.py
backend/tracim_backend/migration/versions/bf040d1a4922_fix_missing_reaction_in_events.py

fix(backend): add REACTION entity type during migration

---

frontend_lib/src/component/CardPopup/CardPopup.jsx
frontend_lib/src/component/CardPopup/CardPopup.styl
frontend_lib/test/component/CardPopup.spec.js
functionnal_tests/cypress/integration/app_file/navigation_create_file.js
functionnal_tests/cypress/integration/app_html-document/navigation_allcontent_contentbutton_create_html-document.js
functionnal_tests/cypress/integration/app_html-document/navigation_allcontent_headerbutton_create_html-document.js
functionnal_tests/cypress/integration/app_html-document/navigation_dashboard_dashboardbutton_create_html-document.js
functionnal_tests/cypress/integration/app_thread/navigation_allcontent_contentbutton_create_thread.js
functionnal_tests/cypress/integration/app_thread/navigation_allcontent_headerbutton_create_thread.js
functionnal_tests/cypress/integration/app_thread/navigation_dashboard_dashboardbutton_create_thread.js
functionnal_tests/cypress/integration/notification_wall/mark_as_read_spec.js
functionnal_tests/cypress/integration/workspace/navigation_create_workspace.js
yarn.lock

#4190
Added a button around the close icon with the class  "transparentButton"

fix/4290 added a button around the close icon 

---

frontend/i18next.scanner/en/translation.json
frontend/i18next.scanner/fr/translation.json
frontend/i18next.scanner/pt/translation.json
frontend/src/container/Publications.jsx
yarn.lock

#4318 
Tests will be added at `fix/4254__add_tests_for_publication_page`

Fix/4318 add more user-friendly name for publications

---

backend/setup.cfg
changelog.md
frontend/src/version.json

Ref #4150 
- No manual test necessary here

doc: prepare new release 3.6.0

---

frontend/src/component/FeedItem/FeedItemHeader.jsx
frontend/src/component/TabBar/TabBar.jsx
frontend/src/container/FeedItemWithPreview.jsx
frontend/src/container/Publications.jsx
frontend/src/container/Tracim.jsx
frontend_lib/src/component/ScrollToBottomWrapper/ScrollToBottomWrapper.jsx
frontend_lib/src/helper.js

fix(frontend): scroll to given publication

---

backend/setup.cfg
backend/tracim_backend/command/search.py
backend/tracim_backend/exceptions.py
backend/tracim_backend/lib/search/elasticsearch_search/elasticsearch_search.py
backend/tracim_backend/tests/library/test_elasticsearch.py
changelog.md
frontend/src/action-creator.async.js
frontend/src/container/AdvancedSearch.jsx
frontend/src/reducer/searchResult.js
frontend/src/util/helper.js
frontend/src/version.json
frontend/test/src/reducer/searchResult.spec.js

There were no conflict during merge :smile: 
**DO NOT MERGE WITH "SQUASH"!!!!!**

Merge 3.6 in develop

---

backend/setup.cfg
changelog.md
frontend/src/version.json

Related to #4355 
- No test necessary here

doc: prepare new release 3.6.1

---

backend/setup.cfg
changelog.md
frontend/src/version.json

**DO NOT USE SQUASHING WHEN MERGING**
- No manual quality tests necessary

Merge 3.6.1 in develop

---

frontend/src/container/Dashboard.jsx
frontend/src/css/Dashboard.styl
frontend_app_admin_workspace_user/src/component/AdminUser.jsx
frontend_app_admin_workspace_user/src/component/AdminWorkspace.jsx

Feat/4337  remove space name on dashboard

---

frontend/src/component/FeedItem/Preview.jsx
frontend/test/apiMock.js
frontend/test/setup.js
frontend/test/src/component/Preview.spec.js
frontend/test/src/container/Publications.spec.js

#4254 
Don't need to tests, there are only tests in this PR.

Fix/4254  add tests for publication page

---

frontend/src/component/Activity/ActivityList.jsx
frontend/src/component/FeedItem/FeedItemHeader.jsx
frontend/src/component/FeedItem/FeedItemHeader.styl
frontend/src/component/FeedItem/Preview.jsx
frontend/src/container/FeedItemWithPreview.jsx
frontend/src/container/Publications.jsx
frontend_lib/src/component/Timeline/CommentFilePreview.jsx
frontend_lib/src/helper.js
frontend_lib/src/index.js

- preview of file publications is now a download link
- preview of timeline file is now a download link
- removed link from title of publications

feat: download link for file publications and comment

---

frontend/i18next.scanner/en/translation.json
frontend/i18next.scanner/fr/translation.json
frontend/i18next.scanner/pt/translation.json
frontend_lib/src/component/Timeline/AddFileToUploadButton.jsx

Added a tooltip to the attach files icon, with translations

added a tooltip [skip ci pytest]

---

frontend/src/css/Publications.styl

Added a 30px margin bottom between publication items
This same margin (30px) can be found in the page "my profile" on profile_content, and on the dashboard on contentTypeBtn.

add 30px margin bottom [skip ci pytest]

---

backend/setup.cfg
changelog.md
frontend/src/version.json

Related to #4282 
- No manual, quality tests necessary here

doc: prepare new release 3.7.0

---

frontend/src/container/Publications.jsx

This is an Integration/3.8 fix.

feat(frontend): remove links to previews in publications

---

frontend/src/container/Dashboard.jsx
frontend/src/container/WorkspaceRecentActivities.jsx
frontend/src/container/withActivity.jsx

- avoid to load previous workspace activities if the user changes the space before the activities are loaded
- do not load workspace details in `WorkspaceActivities.jsx` as it is done in `Dashboard.jsx`.

Integration 3.8/recent activites load

---

frontend_lib/src/component/Timeline/Comment.styl

fix/place margin on text [skip ci pytest]

---

frontend/src/component/FeedItem/FeedItemFooter.jsx
frontend/src/component/FeedItem/FeedItemFooter.styl
frontend/src/component/FeedItem/Preview.jsx
frontend/src/container/FeedItemWithPreview.jsx
frontend/src/util/activity.js
frontend/test/src/activity.spec.js
frontend_app_html-document/src/action.async.js
frontend_app_html-document/src/container/HtmlDocument.jsx
frontend_lib/src/action.async.js
frontend_lib/src/index.js
frontend_lib/src/translation.js
functionnal_tests/cypress/integration/activity_feed/action_menu_spec.js

This PR adds translation buttons in publications. We will need to open an issue to factorize the code handling translation buttons when we have time.

Feat/integration 3.8 translation in publications

---

frontend_lib/src/LiveMessageManager.js
frontend_lib/test/LiveMessageManager.spec.js

Ensure that out-of-order messages are dispatched.

fix(frontend, tlm): ensure we dispatch out-of-order TLMs

---

frontend/src/container/Dashboard.jsx
frontend/src/container/WorkspaceRecentActivities.jsx
frontend/src/container/withActivity.jsx

Cherry-picks the blinking recent activities fix from 3.8, the original commit is https://github.com/tracim/tracim/commit/5e30f35adc57c2ad464d166bde6f3256e38b341c
- tests will be done on our server.

fix(frontend, dashboard): avoid setting activities if space changed

---

backend/setup.cfg
changelog.md
frontend/src/version.json

Ref: #4506 [skip ci]
- No manual, quality tests necessary

doc: prepare new release 3.7.1

---

run_dev_backend.sh

(no issue)
- No original issue
- Automated tests NOT DONE

misc: check cypress config existence in run_dev_backend.sh [skip ci]

---

backend/setup.cfg
changelog.md
frontend/src/version.json

Merge 3.7.1 in develop

---

backend/tracim_backend/migration/versions/bfbd0fa4d8a9_workspace_descriptions_to_html.py
frontend/src/container/Dashboard.jsx

#4462
:warning: this breaks line breaks for descriptions that have not been edited with tinyMCE. 

Fix/4462 Leave worskpace description untransformed

---

frontend/i18next.scanner/en/translation.json
frontend/i18next.scanner/fr/translation.json
frontend/i18next.scanner/pt/translation.json
frontend/src/component/FeedItem/FeedItemHeader.jsx
frontend/src/container/withActivity.jsx
frontend/src/util/activity.js
frontend/test/apiMock.js
frontend/test/src/activity.spec.js
frontend_lib/src/action.async.js
frontend_lib/src/index.js
functionnal_tests/cypress/integration/activity_feed/common_spec.js
functionnal_tests/cypress/integration/activity_feed/ignored_modification_type_spec.js
functionnal_tests/cypress/integration/favorites/favorites.spec.js
functionnal_tests/cypress/support/db_commands.js

Fix/4441 Ignore on recent activities comment modified or deleted

---

frontend/src/component/Activity/ActivityList.styl
frontend/src/component/FeedItem/Preview.styl
frontend_lib/src/component/Timeline/Comment.styl
functionnal_tests/cypress/integration/activity_feed/common_spec.js

feat(frontend): add  box shadow around file preview

---

backend/tracim_backend/lib/core/url_preview.py

See #4470.
Also works for news.google.xxx.
- Automated tests covering the feature or the fix, have been written, deemed irrelevant (give the reason), or an issue has been created to implement the test (give the link): proper automated tests are not advisable since it would need to make requests to external websites in them.

fix(backend,link preview): bypass youtube cookie banner

---

frontend_app_admin_workspace_user/src/container/AdminWorkspaceUser.jsx

fix(frontend): tlm function handleWorkspaceMemberCreated

---

frontend/src/container/FeedItemWithPreview.jsx
frontend/src/css/FeedItemWithPreview.styl
frontend/src/css/Publications.styl
frontend_app_html-document/src/container/HtmlDocument.jsx
frontend_app_html-document/src/css/index.styl
frontend_lib/src/component/AttachedFile/AttachedFile.styl
frontend_lib/src/component/DropdownMenu/DropdownMenu.jsx
frontend_lib/src/component/DropdownMenu/DropdownMenu.styl
frontend_lib/src/component/LinkPreview/LinkPreview.styl
frontend_lib/src/component/ScrollToBottomWrapper/ScrollToBottomWrapper.jsx
frontend_lib/src/component/Timeline/Comment.jsx
frontend_lib/src/component/Timeline/Comment.styl
frontend_lib/src/component/Timeline/CommentFilePreview.jsx
frontend_lib/src/component/Timeline/CommentFilePreview.styl
frontend_lib/src/component/Timeline/Revision.jsx
frontend_lib/src/component/Timeline/Timeline.jsx
frontend_lib/src/component/Timeline/Timeline.styl
frontend_lib/src/index.js
frontend_lib/test/component/Comment.spec.js
frontend_lib/test/component/Revision.spec.js
frontend_lib/test/component/ScrollToBottomWrapper.spec.js
frontend_lib/test/component/SelectStatus.spec.js
functionnal_tests/cypress/integration/activity_feed/common_spec.js
functionnal_tests/cypress/integration/app_html-document/operation_dashboard_dashboardbutton_create_html-document.js
functionnal_tests/cypress/integration/helpers/index.js
functionnal_tests/cypress/integration/publication/publications.spec.js
functionnal_tests/cypress/integration/timeline/comment_size__spec.js
functionnal_tests/cypress/support/urls_commands.js
run_dev_backend.sh
setup_functionnal_tests.sh

Feat/4468 Preview links in publications by using the Comment component

---

frontend_app_admin_workspace_user/src/container/AdminWorkspaceUser.jsx
frontend_app_file/package.json
frontend_app_file/src/index.dev.js
frontend_app_file/src/index.js
frontend_app_folder_advanced/package.json
frontend_app_folder_advanced/src/index.dev.js
frontend_app_folder_advanced/src/index.js
frontend_app_gallery/webpack.config.js
frontend_app_html-document/package.json
frontend_app_html-document/src/index.dev.js
frontend_app_html-document/src/index.js
frontend_app_share_folder_advanced/package.json
frontend_app_share_folder_advanced/src/index.dev.js
frontend_app_share_folder_advanced/src/index.js
frontend_app_thread/package.json
frontend_app_thread/src/index.dev.js
frontend_app_thread/src/index.js
frontend_app_workspace_advanced/package.json
frontend_app_workspace_advanced/src/index.dev.js
frontend_app_workspace_advanced/src/index.js
functionnal_tests/cypress/integration/app_workspace_advanced/operation_workspace_advanced.js
yarn.lock

Feat/4406 add router to appFeatures

---

backend/requirements.txt
backend/setup.py

#4552 
0.16.1/0.16.2 adds a 60-second timeout for libreoffice processes.

fix(backend): update preview-generator version

---

frontend/dist/assets/branding.sample/welcome-simple-text.html

fix(backend): set default welcome text

---

backend/setup.cfg
changelog.md
frontend/src/version.json

Related to #4429 
- No manually test necessary

doc: prepare new release 3.8.0

---

frontend/src/css/PublicProfile.styl

feat(frontend): add margin on public profile content

---

backend/color-test.json
backend/tracim_backend/views/frontend.py
color.json.sample
frontend/dist/index.mak
frontend/src/css/Sidebar.styl

feat(backend, frontend): tune sidebar color via color.json

---

backend/doc/branding.md
backend/doc/env_settings.md

update branding documentation and env settings list

---

frontend/dist/assets/branding.sample/welcome-simple-text.html
frontend/i18next.scanner/de/translation.json
frontend/src/component/PublicProfile/ProfileMainBar.jsx
frontend/src/container/PublicProfile.jsx

fix(frontend): fix icon home

---

backend/requirements.txt
backend/setup.py
backend/tracim_backend/lib/core/storage.py

update preview_generator to 0.18

---

backend/tracim_backend/lib/core/event.py
backend/tracim_backend/migration/versions/44a268b2d39c_add_index_for_workspace_id.py
backend/tracim_backend/models/event.py
backend/tracim_backend/tests/functional/test_message.py
backend/tracim_backend/tests/library/test_event.py
backend/tracim_backend/tests/library/test_mention.py
frontend/src/container/withActivity.jsx
frontend/src/util/activity.js
frontend/test/src/activity.spec.js

See #4590 for the details.
***Testing hints***
*with develop*
- prepare a database with activities: create/edit/comment contents + add users + …
- load the recent activities (both personal and space) and note the their loading time
*with this PR's branch*
- restart `run_dev_backend.sh` and compile the frontend.
- load the recent activities (both personal and space) and note the their loading time

Fix/4590  improve recent activities performance

---

frontend/package.json
frontend/src/container/JoinWorkspace.jsx
frontend/test/setup.js
frontend_app_admin_workspace_user/package.json
frontend_app_admin_workspace_user/src/component/AdminWorkspace.jsx
frontend_lib/src/helper.js
frontend_lib/src/index.js
functionnal_tests/cypress/fixtures/openWorkspace.json
functionnal_tests/cypress/integration/join_workspace/join_workspace_page.spec.js

fix(frontend, join): display description's html as text

---

backend/tracim_backend/migration/versions/eb9b7e534b54_add_creation_author_and_creation_type.py

See #4632.
Which is mandatory for postgresql.
[skip ci cypress]
**Testing method**
*on develop*: start `./run_dev_backend.sh --database=postgresql`, check tracim works, then exit `run_dev_backend.sh`.
*on this branch*: start `./run_dev_backend.sh --database=postgresql`, check tracim works.
You can then stop the backend and remove the database (`cd backend; docker-compose down; docker volume prune`).

fix(backend): properly create the enum

---

frontend/src/component/ContentListItem.jsx
frontend/src/css/Favorites.styl
frontend_lib/src/component/ProfileNavigation/ProfileNavigation.styl
functionnal_tests/cypress/integration/favorites/favorites.spec.js

feat(frontend):  add public profile link in favorites

---

frontend/i18next.scanner/de/translation.json
frontend/i18next.scanner/en/translation.json
frontend/i18next.scanner/fr/translation.json
frontend/i18next.scanner/pt/translation.json
frontend/src/component/Account/UserInfo.jsx
frontend/src/container/Conditions.jsx

feat (frontend): reformulate terms and conditions message

---

backend/tracim_backend/lib/core/url_preview.py
backend/tracim_backend/models/context_models.py
backend/tracim_backend/tests/functional/test_preview_link.py
backend/tracim_backend/views/core_api/schemas.py
backend/tracim_backend/views/core_api/url_preview_controller.py

Fix/4637 don't double unquote link preview URLs

---

frontend/src/util/appInterface.js
frontend_app_file/src/index.js
frontend_app_html-document/src/index.js
frontend_app_thread/src/index.js

#4646
Not needed
Test:
- creation popup: open, close, validate...
- open app
- close app
- switch between apps while an app is open (same type and different types)
- open, close and reopen same content

Fix/4646 unmount appFeature synchronously

---

frontend_app_file/src/container/File.jsx
frontend_app_file/src/css/index.styl
frontend_app_html-document/src/container/HtmlDocument.jsx
frontend_app_html-document/src/css/index.styl
frontend_lib/src/component/Input/SelectStatus/SelectStatus.styl

fix(frontend): add responsiveness to "last version" btn in files and html text

---

backend/doc/branding.md
backend/setup.cfg
changelog.md
frontend/src/version.json

Related to #4661 
- No test necessary here

doc: prepare new release 3.8.2

---

backend/requirements.txt
backend/setup.py

to avoid orphan libreoffice process staying alive eternally.
Refs: #4552

Upgrade tracim to preview generator 0.20

---

backend/tracim_backend/migration/versions/92daba01d07a_add_tag_table.py

The migration was telling postgresql to use a specific sequence, but was not creating it. This fix creates said sequence.

[ integration / sprint 1] fix tag migration

---

backend/tracim_backend/lib/core/user.py
backend/tracim_backend/tests/functional/test_user.py

[Integration / Sprint 1] ignore comments in content autocompletion

---

backend/tracim_backend/__init__.py

related to https://github.com/tracim/tracim/issues/4552

Hack to disable spreadsheet previews

---

.travis.yml
backend/README.md
backend/tracim_backend/command/database.py
run_dev_backend.sh
setup_default_backend.sh
tools_docker/Debian_New_Uwsgi/entrypoint.sh
tools_docker/Debian_Uwsgi/entrypoint.sh

stamp head in tracimcli command

---

frontend_lib/src/component/Input/AutoComplete/AutoComplete.jsx

misc(frontend): add bold on title 

---

backend/development.ini.sample
backend/requirements-test.txt
backend/setup.cfg
backend/tests_configs.ini
backend/tracim_backend/config.py
backend/tracim_backend/lib/core/event.py
backend/tracim_backend/lib/core/tag.py
backend/tracim_backend/lib/crud_hook/caller.py
backend/tracim_backend/lib/crud_hook/hookspec.py
backend/tracim_backend/migration/versions/e733c295afb4_add_tag_and_content_tag_event_entity_.py
backend/tracim_backend/models/event.py
backend/tracim_backend/tests/fixtures.py
backend/tracim_backend/tests/functional/test_live_messages.py
frontend_lib/src/component/Tags/NewTagForm.jsx
frontend_lib/src/component/Tags/TagList.jsx
frontend_lib/src/tracimLiveMessage.js
functionnal_tests/cypress/integration/tags/tags.spec.js

Feat/4700  tlms for tags

---

frontend_app_workspace_advanced/src/component/WorkspaceAdvancedConfiguration.jsx
frontend_app_workspace_advanced/src/container/WorkspaceAdvanced.jsx
frontend_lib/src/appContentFactory.js
frontend_lib/src/component/Input/AutoComplete/AutoComplete.jsx

Feat/4701  add link in space description and comment edition

---

backend/tracim_backend/lib/core/tag.py
backend/tracim_backend/lib/search/elasticsearch_search/elasticsearch_search.py
backend/tracim_backend/lib/search/elasticsearch_search/es_models.py
backend/tracim_backend/lib/search/elasticsearch_search/models.py
backend/tracim_backend/lib/search/models.py
backend/tracim_backend/lib/search/simple_search/simple_search_api.py
backend/tracim_backend/models/tag.py
backend/tracim_backend/tests/functional/test_elasticsearch_search.py
backend/tracim_backend/tests/functional/test_simple_search.py
backend/tracim_backend/views/search_api/schemas.py
frontend/src/action-creator.async.js
frontend/src/component/Search/CheckboxFilter.jsx
frontend/src/component/Search/ContentFacets.jsx
frontend/src/container/AdvancedSearch.jsx
frontend/src/container/SearchFilterMenu.jsx
frontend/src/util/helper.js
frontend/test/src/container/AdvancedSearch.spec.js

Feat/4703  search tags

---

frontend/src/container/Dashboard.jsx
frontend/test/src/container/Header.spec.js
frontend_app_html-document/src/container/HtmlDocument.jsx
frontend_app_workspace_advanced/src/container/WorkspaceAdvanced.jsx
frontend_lib/src/appContentFactory.js
frontend_lib/src/component/Timeline/Comment.jsx
frontend_lib/src/css/Generic.styl
frontend_lib/src/helper.js
frontend_lib/src/index.js
frontend_lib/src/mentionOrLink.js
frontend_lib/test/apiMock.js
frontend_lib/test/links.spec.js

Feat/4732  improve link management

---

backend/tracim_backend/migration/versions/94893551ad7c_add_user_connection_status.py
frontend/i18next.scanner/fr/translation.json

The enum type had to be created explicitly for PostgreSQL.
Co-authored-by: Sébastien Grignard <sebastien.grignard@algoo.fr>

Fix(backend) connection_status migration

---

backend/README.md
backend/setup.cfg
changelog.md
frontend/src/version.json
tools_docker/Debian_Uwsgi/supervisord_tracim.conf

#4699 
(all these are irrelevant to this pull request)

 Feat: Prepare new release 3.9

---

frontend_lib/src/helper.js

#4805 
(This code was approved at #4807)
To test: 
1. Do a publication
2. Click to edit your publication
3. Click to edit the source code
4. Add a invalid url, something like `<p><a href="">test</a></p>`
5. Save and refresh

Fix/4805  fix url exception

---

backend/setup.cfg
changelog.md
frontend/src/version.json

#4809 
- Manual, quality tests have NOT been done

Prepare new release 3.9.1

---

frontend/src/action-creator.async.js

#4826 
- Automated tests doesn't use advanced search

Fix/4826  fix wrong naming at search

---

.travis.yml
README.md
install_frontend_dependencies.sh
tools_docker/Debian_Uwsgi/Dockerfile

fix(frontend): use node 14

---

setup_default_backend.sh
tools_docker/Debian_New_Uwsgi/Dockerfile

fix(back/docker): fix missing node to version 14

---

backend/setup.cfg
changelog.md
frontend/src/version.json

fix(doc): prepare new release 3.9.2

---

.travis.yml
backend/setup.cfg
changelog.md
frontend/src/version.json
install_frontend_dependencies.sh
setup_default_backend.sh
tools_docker/Debian_New_Uwsgi/Dockerfile
tools_docker/Debian_Uwsgi/Dockerfile

Merge maintenance/3.9 into develop

---

frontend/i18next.scanner/de/translation.json
frontend/i18next.scanner/en/translation.json
frontend/i18next.scanner/fr/translation.json
frontend/i18next.scanner/pt/translation.json
frontend/src/container/NotificationWall.jsx
frontend/src/css/NotificationWall.styl

Feat(frontend):  shorten date notification wall

---

frontend/src/component/DragHandle.styl
frontend/src/component/FeedItem/FeedItemFooter.styl
frontend/src/component/FeedItem/FeedItemHeader.styl
frontend/src/component/Workspace/ContentItem.jsx
frontend/src/component/Workspace/Folder.jsx
frontend/src/component/Workspace/Folder.styl
frontend/src/css/ContentItem.styl
frontend/src/css/NotificationWall.styl
frontend_lib/src/component/ConfirmPopup/ConfirmPopup.jsx

fix(frontend): fix spaces and UX issues

---

frontend/src/component/Workspace/ContentItem.jsx
frontend/src/component/Workspace/Folder.jsx
frontend/src/component/Workspace/Folder.styl
frontend/src/css/ContentItem.styl
frontend/src/css/ContentItemHeader.styl
frontend_lib/src/component/Lists/ListItemWrapper/ListItemWrapper.jsx

feat(frontend): improve drag and drop WS list

---

frontend/src/component/Workspace/ContentItem.jsx
functionnal_tests/cypress/integration/login/login_after_disconnection.js
functionnal_tests/cypress/integration/publication/publication_vue_recent_activities_spec.js

Fix(frontend): Fix cypress test on develop

---

frontend/src/action-creator.sync.js
frontend/src/component/Activity/ActivityList.jsx
frontend/src/component/Dashboard/UserStatus.jsx
frontend/src/container/Dashboard.jsx
frontend/src/container/Publications.jsx
frontend/src/container/Tracim.jsx
frontend/src/container/WorkspaceContent.jsx
frontend/src/container/WorkspacePage.jsx
frontend/src/reducer/currentWorkspace.js
frontend/test/setup.js
frontend/test/src/component/UserStatus.spec.js
frontend/test/src/container/Dashboard.spec.js
functionnal_tests/cypress/integration/activity_feed/ignored_modification_type_spec.js
functionnal_tests/cypress/integration/workspace/mention_in_publications_coming_from_another_workspace_spec.js

Fix/4666 Systematically load workspace details and member list when switching workspaces

---

frontend/src/container/Publications.jsx
frontend_lib/src/appContentFactory.js
frontend_lib/src/component/Breadcrumbs/Breadcrumbs.styl
frontend_lib/src/component/Input/AutoComplete/AutoComplete.jsx
frontend_lib/src/debug.js
functionnal_tests/cypress/integration/admin/switching_different_workspace_advanced.js
functionnal_tests/cypress/integration/app_file/notify_all_content_message_spec.js
functionnal_tests/cypress/integration/generic_frontend/group_mentions_spec.js

Fix/4463  group mention not translated

---

frontend/i18next.scanner/de/translation.json
frontend/i18next.scanner/en/translation.json
frontend/i18next.scanner/fr/translation.json
frontend/i18next.scanner/pt/translation.json
frontend/src/component/FeedItem/FeedItemFooter.jsx
frontend/src/component/FeedItem/FeedItemFooter.styl
frontend/src/container/FeedItemWithPreview.jsx
frontend/src/css/Publications.styl
frontend_lib/src/component/EmojiReactions/EmojiReactions.styl
frontend_lib/src/component/PopinFixed/PopinFixed.styl
frontend_lib/src/component/Timeline/Comment.jsx
frontend_lib/src/component/Timeline/Comment.styl
frontend_lib/src/css/Variable.styl
functionnal_tests/cypress/integration/publication/file_spec.js
functionnal_tests/cypress/integration/publication/options_spec.js
functionnal_tests/cypress/integration/publication/toggle_comments.js
functionnal_tests/cypress/integration/sidebar/feature_app_size_spec.js

feat(frontend): hide comments by default

---

frontend_lib/src/component/Timeline/Timeline.styl

fix(frontend): change spacing between comments

---

.travis.yml
frontend/i18next.scanner/de/translation.json
frontend/i18next.scanner/en/translation.json
frontend/i18next.scanner/fr/translation.json
frontend/i18next.scanner/pt/translation.json
frontend/src/component/TabBar/TabBar.jsx
frontend/src/container/Dashboard.jsx
frontend/src/container/FeedItemWithPreview.jsx
frontend/src/container/Publications.jsx
frontend_app_workspace_advanced/i18next.scanner/de/translation.json
frontend_app_workspace_advanced/i18next.scanner/en/translation.json
frontend_app_workspace_advanced/i18next.scanner/fr/translation.json
frontend_app_workspace_advanced/i18next.scanner/pt/translation.json
frontend_app_workspace_advanced/src/component/OptionalFeatures.jsx
frontend_app_workspace_advanced/src/container/WorkspaceAdvanced.jsx
functionnal_tests/cypress/integration/app_workspace_advanced/operation_workspace_advanced.js
install_frontend_dependencies.sh
setup_default_backend.sh
tools_docker/Debian_New_Uwsgi/Dockerfile
tools_docker/Debian_Uwsgi/Dockerfile

feat(frontend) rewording of 'Publications' in 'News'

---

frontend/src/component/FeedItem/FeedItemFooter.styl

fix(frontend): fix alignment on publications

---

concourse/pipelines/pull-request.yml
concourse/scripts/backend-full-tests
concourse/scripts/backend-lint
concourse/scripts/backend-quick-tests
concourse/scripts/end-to-end-cypress-tests
concourse/scripts/frontend-unit-tests
concourse/scripts/util-lib.sh

Skips tests if related source files aren't modified.
See #4886.

feat(ci): avoid running tests if the changes are not related.

---

backend/tracim_backend/lib/core/url_preview.py
backend/tracim_backend/tests/functional/test_preview_link.py

fix(backend): ensure image url is absolute.

---

backend/setup.cfg
changelog.md
frontend/src/version.json

release 4.0.2

---

backend/tracim_backend/views/frontend.py

**This PR changes the not found view behavior, so it should be merged only after Tracim 3.10 release.**
Linked issue: #4007

[NOT MERGE before 3.10] feat(backend): /api/doc now redirect to /api/doc/

---

backend/tracim_backend/lib/core/mention.py
backend/tracim_backend/tests/fixtures.py
backend/tracim_backend/tests/functional/test_comments.py
backend/tracim_backend/views/contents_api/comment_controller.py

Fix issues with bad mention: return 400 instead of 500

---

backend/tracim_backend/lib/core/content.py
backend/tracim_backend/tests/functional/test_favorites.py
backend/tracim_backend/views/core_api/favorite_content_controller.py

fix(backend): allow removing favorite even if not anymore in workspace

---

backend/tracim_backend/lib/core/event.py
backend/tracim_backend/lib/core/mention.py
backend/tracim_backend/tests/functional/test_message.py
backend/tracim_backend/tests/utils.py

avoid json fields filter

---

backend/requirements.txt
backend/setup.py

update to preview-generator 0.27

---

frontend_app_workspace_advanced/src/component/WorkspaceMembersList.jsx
frontend_app_workspace_advanced/src/container/WorkspaceAdvanced.jsx
functionnal_tests/cypress/integration/app_workspace_advanced/operation_workspace_advanced.js
functionnal_tests/cypress/integration/workspace/create_workspace_spec.js
functionnal_tests/cypress/support/generic_selector_commands.js
yarn.lock

Fix(frontend) fix severable unstable tests

---

frontend_lib/src/component/Timeline/Comment.jsx
frontend_lib/src/component/Timeline/CommentArea.jsx
functionnal_tests/cypress/integration/app_file/switch_between_apps_spec.js

misc: write functional test for the timeline

---

frontend/src/container/WorkspaceContent.jsx

#4985
- NOTHING NEW, I didn't add tests

Fix/4985 don't request read statuses too many times in WorskpaceContent

---

backend/tracim_backend/app_models/validator.py
backend/tracim_backend/models/data.py
backend/tracim_backend/models/tag.py
backend/tracim_backend/views/core_api/schemas.py

related to #4718
:warning: Add a frontend part ?

add better validator for max length of database fields

---

frontend/src/component/FeedItem/FeedItemHeader.jsx
frontend_lib/src/component/Button/TranslateButton.jsx
frontend_lib/src/component/Input/SelectStatus/SelectStatus.jsx
frontend_lib/src/component/PopinFixed/PopinFixedHeader.jsx
frontend_lib/src/component/Timeline/Comment.jsx

Fix(frontend) Display text in dropdown menu for small devices

---

frontend/src/component/Workspace/OpenContentApp.jsx
frontend/src/component/Workspace/OpenWorkspaceAdvanced.jsx
frontend/src/container/Dashboard.jsx
frontend/src/container/NotificationWall.jsx
frontend/src/container/Tracim.jsx
frontend_app_workspace_advanced/src/container/WorkspaceAdvanced.jsx
frontend_lib/src/helper.js

- I will create an issue for the failing functional tests 
Ticket: #5093

feat(frontend): redirect to advanced ws url

---

backend/setup.py
backend/tracim_backend/command/__init__.py
backend/tracim_backend/command/space.py
backend/tracim_backend/lib/core/workspace.py
backend/tracim_backend/tests/commands/test_commands.py

related to #3636.
Base feature is working, but need feedback.

feat: add tracimcli command to move space

---

frontend_lib/src/helper.js
frontend_lib/test/helper.spec.js
frontend_lib/test/setup.js

Fix/4907  created revision should come first

---

tools_docker/Debian_New_Uwsgi/Dockerfile
tools_docker/Debian_Uwsgi/Dockerfile

The version introducing the change is the 60.0.0.
See #5183.
-------

fix(docker): workaround to a behavior change in setuptools.

---

backend/setup.cfg
changelog.md
frontend/src/version.json

Prepare new release 4.0.4

---

backend/tracim_backend/tests/functional/test_contents.py
frontend/src/action-creator.async.js
frontend/src/container/ReduxTlmDispatcher.jsx

Which were missing a redirection in backend.
See #5157

Enable notifications for comments in Kanban Boards

---

backend/setup.cfg
changelog.md
frontend/src/version.json
functionnal_tests/cypress/integration/app_workspace_advanced/operation_workspace_advanced.js
tools_docker/Debian_New_Uwsgi/Dockerfile
tools_docker/Debian_Uwsgi/Dockerfile

- small changes in changelog
- skipped cypress test
- fix for docker image (setuptools, see #5183)
- [}] Automated tests covering the feature or the fix, have been written, deemed irrelevant (give the reason), or an issue has been created to implement the test (give the link) => No tests for those changes

[DO NOT SQUASH] Merging maintenance 4.0 branch

---

frontend_app_kanban/i18next.scanner/de/translation.json
frontend_app_kanban/i18next.scanner/en/translation.json
frontend_app_kanban/i18next.scanner/fr/translation.json
frontend_app_kanban/i18next.scanner/pt/translation.json
frontend_app_kanban/src/component/KanbanCard.jsx
frontend_app_kanban/src/component/KanbanCard.styl
frontend_app_kanban/src/component/KanbanColumnHeader.jsx
functionnal_tests/cypress/integration/app_kanban/kanban_cards_spec.js
functionnal_tests/cypress/integration/app_kanban/kanban_columns_spec.js
functionnal_tests/cypress/integration/app_kanban/navigation_create_kanban_spec.js

#5173 
~- [ ] Automated tests covering the feature or the fix, have been written, deemed irrelevant (give the reason), or an issue has been created to implement the test (give the link)~ See #5153 

Feat/5173  limit kanban card description

---

frontend_app_kanban/i18next.scanner/de/translation.json
frontend_app_kanban/i18next.scanner/en/translation.json
frontend_app_kanban/i18next.scanner/fr/translation.json
frontend_app_kanban/i18next.scanner/pt/translation.json
frontend_app_kanban/src/component/Kanban.jsx
frontend_app_kanban/src/component/KanbanCard.styl
frontend_app_kanban/src/css/index.styl
frontend_lib/src/component/PopinFixed/PopinFixed.styl

#5172
~- [ ] Automated tests covering the feature or the fix, have been written, deemed irrelevant (give the reason), or an issue has been created to implement the test (give the link)~ 

feat(frontend): add scroll per column on kanban

---

concourse/scripts/backend-full-tests
concourse/scripts/end-to-end-cypress-tests
tools_docker/pushpin/Dockerfile
tools_docker/pushpin/start.sh

misc(docker): Use bullseye's pushpin to build test & dev image.

---

backend/setup.cfg
changelog.md
frontend/src/version.json

doc: prepare release 4.0.5

---

backend/setup.cfg
changelog.md
concourse/scripts/backend-full-tests
concourse/scripts/end-to-end-cypress-tests
frontend/src/version.json
tools_docker/pushpin/Dockerfile
tools_docker/pushpin/start.sh

Merge 4.0.5 in develop

---

frontend_app_kanban/src/component/KanbanCard.styl
frontend_app_kanban/src/css/index.styl
frontend_lib/src/component/Tags/NewTagForm.jsx
frontend_lib/test/component/NewTagForm.spec.js
functionnal_tests/cypress/integration/app_workspace_advanced/read_mode_only_spec.js

#5199 
~- [ ] Automated tests covering the feature or the fix, have been written, deemed irrelevant (give the reason), or an issue has been created to implement the test (give the link)~ Automated tests for kanban at #5153 

Feat/5199  scroll by dragging cards

---

frontend_app_kanban/src/component/Kanban.jsx
frontend_app_kanban/src/css/index.styl
frontend_app_kanban/test/component/Kanban.spec.js
frontend_app_kanban/test/setup.js

fix(frontend, kanban): avoid resetting scroll when updating.

---

frontend_app_kanban/src/container/PopupCreateKanban.jsx
frontend_app_kanban/src/debug.js.sample
frontend_app_kanban/test/container/PopupCreateKanban.spec.js
frontend_app_kanban/test/setup.js

fix(frontend, kanban): display message on creation errors.

---

frontend_lib/src/appContentFactory.js
frontend_lib/src/helper.js
functionnal_tests/cypress/integration/app_kanban/kanban_cards_spec.js
functionnal_tests/cypress/integration/app_kanban/kanban_columns_spec.js
functionnal_tests/cypress/integration/app_kanban/navigation_create_kanban_spec.js

Re-enable Kanban cypress tests

---

frontend/i18next.scanner/de/translation.json
frontend/i18next.scanner/en/translation.json
frontend/i18next.scanner/fr/translation.json
frontend/i18next.scanner/pt/translation.json
frontend/src/util/helper.js
frontend/src/util/tinymceInit.js
frontend_app_kanban/src/component/KanbanCardEditor.jsx

#5202 
~- [ ] Automated tests covering the feature or the fix, have been written, deemed irrelevant (give the reason), or an issue has been created to implement the test (give the link)~ See #5153 
Also test if we still have the auto focus on tinymce for notes and comments.

Fix/5202  better handle search and popup kanban

---

frontend_app_kanban/src/component/KanbanCard.jsx
frontend_app_kanban/src/component/KanbanColumnHeader.jsx
frontend_app_kanban/src/css/index.styl
functionnal_tests/cypress/integration/app_kanban/helper.js
functionnal_tests/cypress/integration/app_kanban/kanban_cards_spec.js
functionnal_tests/cypress/integration/app_kanban/kanban_columns_spec.js

test(frontend, kanban): add cypress tests

---

frontend/src/css/Sidebar.styl
frontend_lib/src/component/Button/IconButton.styl

remove margin on small screen for icon button

---

frontend/src/component/TimedEvent.styl
frontend_lib/src/component/Layout/PageWrapper.styl
frontend_lib/src/component/ProfileNavigation/ProfileNavigation.styl

fix css for cards width responsive

---

frontend/src/component/Activity/MemberActivity.styl
frontend/src/component/FeedItem/FeedItemHeader.styl
frontend/src/container/Home.jsx
frontend/src/css/FeedItemWithPreview.styl
frontend_app_gallery/src/container/Gallery.jsx
frontend_app_html-document/src/component/HtmlDocument.jsx
frontend_app_html-document/src/container/HtmlDocument.jsx
frontend_app_kanban/src/component/KanbanCard.jsx
frontend_app_kanban/src/component/KanbanColumnHeader.jsx
frontend_lib/src/component/CardPopup/CardPopup.jsx
frontend_lib/src/component/ConfirmPopup/ConfirmPopup.jsx
frontend_lib/src/component/DropdownMenu/DropdownMenu.styl
frontend_lib/src/component/PopinFixed/PopinFixed.styl
frontend_lib/src/component/Timeline/CommentArea.jsx
frontend_lib/src/component/Timeline/EditCommentPopup.jsx

Fix/5234  improve buttons UX

---

frontend/src/component/Header/MenuActionListItem/AdminLink.jsx
frontend/src/component/Header/MenuActionListItem/DropdownLang.jsx
frontend/src/component/Header/MenuActionListItem/MenuProfil.jsx
frontend/src/component/Header/MenuActionListItem/NotificationButton.jsx
frontend/src/component/Search/SearchInput.jsx
frontend/src/container/Header.jsx
frontend/src/container/Sidebar.jsx
frontend_lib/src/component/DropdownMenu/DropdownMenu.styl

#5227 
~- [ ] Automated tests covering the feature or the fix, have been written, deemed irrelevant (give the reason), or an issue has been created to implement the test (give the link)~ See https://github.com/tracim/tracim/issues/3030

Fix/5227  close main header when click header buttons

---

frontend/src/container/Tracim.jsx

fix(frontend): display call popup on android

---

frontend/src/container/Publications.jsx
frontend/src/css/Publications.styl
frontend/src/reducer/publicationPage.js

feat(frontend): reverse order of publications

---

frontend_app_kanban/i18next.scanner/de/translation.json
frontend_app_kanban/i18next.scanner/en/translation.json
frontend_app_kanban/i18next.scanner/fr/translation.json
frontend_app_kanban/i18next.scanner/pt/translation.json
frontend_app_kanban/src/component/Kanban.jsx
frontend_app_kanban/src/component/KanbanCard.jsx
frontend_app_kanban/src/component/KanbanCard.styl
frontend_app_kanban/src/component/KanbanColumnHeader.jsx
frontend_app_kanban/src/css/index.styl
functionnal_tests/cypress/integration/app_kanban/helper.js

Fix/5255  kanban flashes scrolls readonly mode

---

backend/setup.cfg
changelog.md
frontend/src/version.json

doc: prepare release 4.0.6

---

frontend_app_admin_workspace_user/src/component/AdminUser.jsx
frontend_app_admin_workspace_user/src/component/AdminWorkspace.jsx
frontend_app_admin_workspace_user/src/container/AdminWorkspaceUser.jsx

fix(frontend): add loading icons to admin workspace user app

---

frontend/src/container/Publications.jsx
frontend_lib/i18next.scanner/de/translation.json
frontend_lib/i18next.scanner/en/translation.json
frontend_lib/i18next.scanner/fr/translation.json
frontend_lib/i18next.scanner/pt/translation.json
frontend_lib/src/component/Timeline/CommentArea.jsx
frontend_lib/src/component/Timeline/EditCommentPopup.jsx
frontend_lib/src/component/Timeline/Timeline.jsx

Icon and placeholder are now props so we can change and differantiate them easier

Change place holders on news and commentaries

---

frontend/src/component/FeedItem/FeedItemHeader.styl
frontend/src/component/Workspace/Folder.styl
frontend/src/css/FeedItemWithPreview.styl
frontend/src/css/PublicProfile.styl
frontend/src/css/Sidebar.styl
frontend_app_html-document/src/css/index.styl
frontend_app_share_folder_advanced/src/css/index.styl
frontend_app_thread/src/css/index.styl
frontend_app_workspace/src/css/index.styl
frontend_lib/src/component/Button/IconButton.styl
frontend_lib/src/component/HTMLContent/HTMLContent.styl
frontend_lib/src/component/Layout/PageWrapper.styl
frontend_lib/src/component/PopinFixed/PopinFixed.styl
frontend_lib/src/component/ShareDownload/ShareDownload.styl
frontend_lib/src/component/Timeline/Revision.styl
frontend_lib/src/component/Timeline/Timeline.styl

#5290
~- [ ] Automated tests covering the feature or the fix, have been written, deemed irrelevant (give the reason), or an issue has been created to implement the test (give the link)~ not relevant

Feat/5290 update from padding-left to padding-inline-start 

---

frontend/src/component/ContentListItem.styl
frontend/src/component/FlashMessage.styl
frontend/src/component/Search/AdvancedSearchContentList.styl
frontend/src/css/NotificationWall.styl
frontend_app_gallery/src/css/index.styl
frontend_app_kanban/src/css/index.styl
frontend_app_share_folder_advanced/src/css/index.styl
frontend_app_thread/src/css/index.styl
frontend_app_workspace_advanced/src/css/index.styl
frontend_lib/src/component/Layout/PageWrapper.styl

#5290
~- [ ] Automated tests covering the feature or the fix, have been written, deemed irrelevant (give the reason), or an issue has been created to implement the test (give the link)~ not relevant

Feat/5290 update from padding-right to padding-inline-end

---

frontend/src/component/Account/PersonalData.styl
frontend/src/component/Activity/MemberActivity.styl
frontend/src/component/FeedItem/FeedItemHeader.styl
frontend/src/css/ContentItemHeader.styl
frontend/src/css/Home.styl
frontend/src/css/JoinWorkspace.styl
frontend/src/css/NotificationWall.styl
frontend/src/css/Tracim.styl
frontend_app_admin_workspace_user/src/css/index.styl
frontend_app_custom-form/src/component/JsonForm/JsonForm.styl
frontend_app_custom-form/src/css/index.styl
frontend_app_gallery/src/css/index.styl
frontend_app_kanban/src/css/index.styl
frontend_lib/src/component/EmojiReactions/EmojiReactions.styl
frontend_lib/src/component/Input/TextAreaApp/TextAreaApp.styl
frontend_lib/src/component/Tags/TagList.styl
frontend_lib/src/component/Timeline/Revision.styl

#5290 
~- [ ] Automated tests covering the feature or the fix, have been written, deemed irrelevant (give the reason), or an issue has been created to implement the test (give the link)~ not relevant

Feat/5290 adapt all text-align to be rtl friendly

---

frontend/src/component/Dashboard/AgendaInfo.styl
frontend/src/component/Dashboard/WebdavInfo.styl
frontend/src/component/FlashMessage.styl
frontend/src/css/Sidebar.styl
frontend_lib/src/component/CardPopup/CardPopup.styl
frontend_lib/src/component/NewMemberForm/NewMemberForm.styl
frontend_lib/src/component/ProgressBar/ProgressBar.styl

#5290
~- [ ] Automated tests covering the feature or the fix, have been written, deemed irrelevant (give the reason), or an issue has been created to implement the test (give the link)~ not relevant

Feat/5290 add fallbacks for rtl recent commands 

---

frontend/src/component/Dashboard/ContentTypeBtn.styl
frontend/src/component/FeedItem/FeedItemFooter.styl
frontend/src/component/FeedItem/Preview.styl
frontend/src/component/common/Input/InputGroupText.styl
frontend/src/css/Dashboard.styl
frontend/src/css/Generic.styl
frontend/src/css/PublicProfile.styl
frontend/src/css/Workspace.styl
frontend_app_file/src/css/index.styl
frontend_app_share_folder_advanced/src/css/index.styl
frontend_lib/src/component/Input/BtnSwitch/BtnSwitch.styl
frontend_lib/src/component/Input/SingleChoiceList/SingleChoiceList.styl
frontend_lib/src/component/Layout/PageWrapper.styl

Feat/5290  start of adaptation of interface to rtl

---

frontend/src/container/Publications.jsx

Misc(frontend): Restore the publish icon

---

frontend/src/component/Workspace/Folder.styl

Fix(frontend): Folder triangles are not displayed correctly in RTL

---

frontend/src/container/Tracim.jsx

disable ringing on mobile

---

frontend_lib/src/component/ProgressBar/ProgressBar.styl

fix(frontend): fix display of progress bar in RTL languages

---

frontend_lib/src/component/Input/TextInput.jsx
frontend_lib/src/component/Input/TextInput.styl
functionnal_tests/cypress/integration/account/manage_user_space.js

feat(frontend): position search icon on left arabic

---

backend/tracim_backend/applications/agenda/controllers/radicale_proxy_controller.py
backend/tracim_backend/applications/agenda/lib.py
backend/tracim_backend/command/caldav.py
backend/tracim_backend/command/cleanup.py
backend/tracim_backend/lib/cleanup/cleanup.py
backend/tracim_backend/tests/functional/test_caldav.py

Including calendar activation/de-activation in a space.
See #5263.

Add calendar add/remove sync for some cases

---

frontend/src/component/Search/CheckboxFilter.jsx
frontend/src/component/Search/ContentItemSearch.jsx
frontend/src/component/Search/DateFilter.jsx
frontend/src/component/Sidebar/WorkspaceListItem.jsx
frontend/src/component/Workspace/ContentItem.jsx
frontend_app_admin_workspace_user/src/component/FormBuilder/FieldType.jsx
frontend_app_gallery/src/component/MainPreview.jsx
frontend_lib/src/component/Icon/ComposedIcon.styl

Issue ref #5319
This PR also update some ``padding-right/left`` and margin-right/left to ``padding-inline-start/end`` and ``margin-inline-start/end`` forgotten in .jsx files.

Feat(frontend): Add RTL support to composed icons

---

frontend/src/css/Sidebar.styl
frontend_lib/src/component/PopinFixed/PopinFixed.styl
frontend_lib/src/css/Variable.styl

Misc(frontend): put the expand part of the sidebar outside the sidebar

---

frontend_lib/src/LiveMessageManager.js
frontend_lib/test/LiveMessageManager.spec.js
frontend_lib/test/component/Timeline.spec.js

fix(frontend): detect pending state when receiving a TLM

---

backend/setup.cfg
changelog.md
frontend/src/version.json

#5351 
Release 4.1.1.
Refs: #5253, #5285, #5286, #5315

Prepare new release 4.1.1

---

frontend_app_kanban/src/css/index.styl
functionnal_tests/cypress/integration/app_thread/translation.js

Misc(frontend): change directionality RTL to LTR for kanban in RTL

---

frontend_app_file/src/component/PreviewComponent.styl
frontend_app_file/src/css/index.styl
frontend_lib/src/component/Icon/ComposedIcon.styl
frontend_lib/src/component/Input/TextInput.styl
functionnal_tests/cypress/integration/app_thread/translation.js

Fix(frontend): display composed icons correctly in RTL

---

backend/docker-compose.yml

Add limit to 4g of memory for elasticsearch in dev environnement

---

frontend_lib/src/component/Badge/Badge.jsx
frontend_lib/src/component/Badge/Badge.styl
frontend_lib/src/component/FilenameWithExtension/FilenameWithExtension.jsx
frontend_lib/src/component/FilenameWithExtension/FilenameWithExtension.styl
frontend_lib/src/component/Lists/ListItemWrapper/ListItemWrapper.styl
frontend_lib/test/component/Badge.spec.js

Fix(frontend): file extension dot position should be on the left even in RTL

---

frontend/package.json
frontend_lib/package.json
yarn.lock

fix(frontend): upgrade BroadcastChannel

---

backend/tracim_backend/lib/core/system.py
backend/tracim_backend/models/context_models.py
backend/tracim_backend/models/database_version.py
backend/tracim_backend/tests/functional/test_system.py
backend/tracim_backend/views/core_api/schemas.py

add database version info in system about view

---

backend/setup.cfg
changelog.md
frontend/src/version.json

doc: prepare new release 4.1.2

---

frontend/src/css/PublicProfile.styl

change css to support RTL and LTR on upload a profil picture

---

backend/setup.cfg
changelog.md
frontend/package.json
frontend/src/version.json
frontend_app_thread/src/css/index.styl
frontend_lib/package.json
tools_docker/Debian_Uwsgi_ARM64/Dockerfile
yarn.lock

DO NOT SQUASH
~- [ ] Manual, quality tests have been done~

Merge version 4.1.2 into develop

---

frontend_app_gallery/package.json
frontend_app_gallery/src/component/Carousel.jsx
frontend_app_gallery/src/component/GallerySlider.jsx
frontend_app_gallery/src/component/MainPreview.jsx
frontend_app_gallery/src/container/Gallery.jsx
frontend_app_gallery/src/css/index.styl
yarn.lock

Fix/5373  rtl gallery

---

frontend/src/css/NotificationWall.styl
frontend_lib/src/css/Variable.styl

Fix(frontend): position of avatars when the notification display two authors

---

frontend/src/component/NotificationItem.jsx
frontend/src/container/GroupedNotificationItem.jsx
frontend/src/container/NotificationWall.jsx

Issue ref #5333 
GroupedNotificationItem is now a function item
shortDate property is now a props String that is computed in the NotificationWall

change shortDate property and update GroupedNotificationItem to function

---

backend/tracim_backend/lib/core/event.py
backend/tracim_backend/lib/core/plugins.py
backend/tracim_backend/tests/library/test_event.py

remove message when workspace is deleted or user role is removed

---

frontend/src/container/Login.jsx

 feat(frontend): ask user for notification when they connect

---

frontend/dist/assets/branding.sample/welcome-simple-text.html

feat(frontend): update welcome page language

---

backend/tracim_backend/__init__.py

This reverts commit 40e9d6514309f72380c988412c5190ea784bae03.
related to #4706 

Revert "fix(backend): disable spreadsheet_preview"

---

backend/tracim_backend/__init__.py
backend/tracim_backend/lib/utils/http_cache.py

For all API responses.
See #5334.

fix(backend): ensure a default value for Cache-Control header

---

frontend/src/container/ForgotPasswordNoEmailNotif.jsx

I'm pushing the refactor we did as an exercise for react hooks.
It has no associated issue

fix(front): refactor ForgotPasswordNoEmailNotif.jsx to use hooks

---

frontend/dist/assets/_caldavzap/config.tracim.js
frontend/dist/assets/_caldavzap/localization.js

Issue: #5492
- The failing end-to-end test is not linked to this pr, so I will merge this as it is

feat(frontend): add caldav arabic translation

---

frontend/src/css/IconsRtl.styl

feat(front): invert all icons

---

frontend/GroupedNotificationItem/GroupRender.jsx
frontend/src/component/NotificationItem.jsx
frontend/src/component/Sidebar/WorkspaceListItem.jsx
frontend/src/container/GroupedNotificationItem.jsx
frontend/src/container/NotificationWall.jsx
frontend/src/container/withActivity.jsx
frontend/src/reducer/notificationPage.js
frontend/src/util/helper.js
frontend/test/src/container/NotificationWall.spec.js
frontend/test/src/reducer/notificationPage.spec.js

Issue ref #5497
group logic is now in `NotificationWall` component, `GroupedNotificationItem` now has the control of how/when they should display as a list or not

feat(frontend): notification refactoring 

---

frontend/src/component/Dashboard/ContentTypeBtn.jsx
frontend/src/container/Dashboard.jsx
frontend_app_file/src/container/File.jsx
frontend_lib/src/component/PopinFixed/PopinFixedHeader.jsx
frontend_lib/src/component/Tags/Tag.jsx
functionnal_tests/cypress/integration/app_file/open_file.js

fix(frontend, file): download link should include filename

---

frontend/dist/assets/_caldavzap/config.tracim.js
frontend/src/component/Search/CheckboxFilter.jsx
frontend/src/component/Search/CheckboxFilter.styl
frontend/src/component/Search/DateFilter.styl
frontend/src/css/SearchFilterMenu.styl
frontend_app_html-document/test/component/HtmlDocument.spec.js
frontend_app_workspace_advanced/test/src/component/SpaceSubscriptionsRequests.spec.js
frontend_lib/src/component/Tags/Tag.jsx
functionnal_tests/cypress/integration/app_file/switch_between_apps_spec.js
functionnal_tests/cypress/integration/workspace/mention_in_publications_coming_from_another_workspace_spec.js

#5532 (fix date filter on advanced search too)

Fix/5532  update calendars to better suport Arabic

---

backend/tracim_backend/tests/library/test_rq.py

add better timeouts for submit_jobs rq test

---

backend/requirements.txt
backend/setup.py
backend/tracim_backend/__init__.py
backend/tracim_backend/lib/utils/authentification.py
backend/tracim_backend/lib/utils/authorization.py
backend/tracim_backend/models/setup_models.py
backend/tracim_backend/views/base.py

add support for pyramid 2

---

frontend/src/util/tinymceInit.js
functionnal_tests/cypress/integration/generic_frontend/operation_tinymce.js
functionnal_tests/cypress/support/commands.js
functionnal_tests/cypress/support/db_commands.js

https://github.com/tracim/tracim/issues/5534

fix rtl for ul and ol

---

backend/requirements.txt
backend/setup.py

fix: update webpreview version to algoo one

---

frontend_app_kanban/src/component/KanbanCard.jsx
frontend_app_kanban/src/component/KanbanCard.styl
functionnal_tests/cypress/integration/app_kanban/kanban_cards_spec.js

(fix)frontend: make value and date visible kanban

---

frontend/package.json
frontend/test/src/container/Account.spec.js
frontend/test/src/container/AdminAccount.spec.js
frontend/test/src/container/NotificationWall.spec.js
frontend_app_admin_workspace_user/package.json
frontend_app_agenda/package.json
frontend_app_collaborative_document_edition/package.json
frontend_app_file/package.json
frontend_app_folder_advanced/package.json
frontend_app_gallery/package.json
frontend_app_html-document/package.json
frontend_app_kanban/package.json
frontend_app_share_folder_advanced/package.json
frontend_app_thread/package.json
frontend_app_workspace/package.json
frontend_app_workspace_advanced/package.json
frontend_lib/package.json
frontend_lib/src/component/Popover/Popover.jsx
frontend_lib/webpack.standalone.config.js
yarn.lock

https://github.com/tracim/tracim/issues/5223

fix(front): fix unit tests with hooks

---

frontend_app_file/src/component/PreviewComponent.styl
frontend_app_file/src/container/File.jsx
frontend_app_file/src/css/index.styl
frontend_app_workspace_advanced/src/component/WorkspaceAdvancedConfiguration.jsx
functionnal_tests/cypress/integration/app_file/file_display_spec.js

#5471 + small fix for agenda url

Fix/5471  fix not displayed pagination and agenda url

---

frontend/src/css/Generic.styl

fix(frontend):  Bottom of the tinymce disappears in full screen

---

backend/tracim_backend/views/core_api/schemas.py
frontend/src/action-creator.async.js
frontend/src/component/Account/PersonalData.jsx
frontend/src/container/Account.jsx
frontend/src/container/AdminAccount.jsx
frontend/src/container/ForgotPassword.jsx
frontend/src/container/Login.jsx
frontend/src/container/ResetPassword.jsx
frontend_app_admin_workspace_user/src/component/AddUserForm.jsx
frontend_app_admin_workspace_user/src/component/AdminUser.jsx
frontend_app_admin_workspace_user/src/container/AdminWorkspaceUser.jsx
frontend_lib/src/helper.js

related to #5558 
Fix by stripping email string in email input in backend as well as in frontend. 

fix(fronted/backend): Strip space in email address

---

frontend_lib/src/tinymceAutoCompleteHelper.js

Issue #4813
~- [ ] Manual, quality tests have been done~
Testing during integration

fix(frontend): add special character and arabic character to tinymce autocompletion

---

frontend_lib/src/component/Timeline/CommentArea.styl

#5593 
~- [ ] Automated tests covering the feature or the fix, have been written, deemed irrelevant (give the reason), or an issue has been created to implement the test (give the link)~ Tinymce tests are disabled for now #5436 

fix(frontend): better area for advanced edition on small screens

---

backend/tracim_backend/models/context_models.py
backend/tracim_backend/tests/functional/test_user.py
backend/tracim_backend/tests/functional/test_workspaces.py
backend/tracim_backend/views/core_api/schemas.py
backend/tracim_backend/views/core_api/user_controller.py
backend/tracim_backend/views/core_api/workspace_controller.py
frontend/src/container/Dashboard.jsx
frontend_app_workspace_advanced/src/container/WorkspaceAdvanced.jsx

related to #5558  (second part)

allow rfc email for invitation, creation and registration of users

---

functionnal_tests/cypress/integration/app_kanban/kanban_cards_spec.js
functionnal_tests/cypress/integration/login/content_login_page.js
functionnal_tests/cypress/integration/login/login_after_disconnection_spec.js
functionnal_tests/cypress/integration/login/navigation_home-page_to_login-page.js
functionnal_tests/cypress/integration/publication/open_in_app_spec.js

This PR is just about fixing tests that was failing due to integration fixes.

fix(frontend): Fix tests

---

tools_docker/Debian_New_Uwsgi/Dockerfile
tools_docker/Debian_Uwsgi/Dockerfile
tools_docker/Debian_Uwsgi_ARM64/Dockerfile

add kanban as default app in docker image

---

backend/setup.cfg
changelog.md
frontend/src/version.json

doc: prepare new release 4.2.0

---

frontend/package.json
frontend/src/component/PublicProfile/TextareaRich.jsx
frontend/src/util/tinymceInit.js
frontend_app_kanban/src/component/KanbanCardEditor.jsx
frontend_app_workspace_advanced/src/component/WorkspaceAdvancedConfiguration.jsx
frontend_lib/src/component/Input/TextAreaApp/TextAreaApp.jsx
frontend_lib/src/component/Timeline/CommentArea.jsx

Fix/5622  better performance for notes that has images on Chrome

---

frontend/package.json
frontend_app_admin_workspace_user/package.json
frontend_app_gallery/package.json
frontend_vendors/package.json
yarn.lock

misc(frontend): update Async dependency

---

backend/setup.cfg
changelog.md
frontend/src/version.json

doc: prepare new release 4.2.1

---

backend/setup.cfg
changelog.md
frontend/src/util/helper.js
frontend/src/version.json
frontend_app_gallery/src/container/Gallery.jsx
yarn.lock

doc: merge maintenance 4.2.2 into develop

---

frontend/src/component/Account/UserSpacesConfig.jsx
frontend/test/src/component/UserSpacesConfig.spec.js

Issue ref: #5624
This PR brings:
- `UserSpacesConfig` now in function
- `Loader` added to `UserSpacesConfig`

fix(frontend): display loader when loading space in user config

---

frontend/src/action-creator.async.js
frontend/src/component/Account/AdminUserSpacesConfigItem.jsx
frontend/src/component/Account/UserSpacesConfig.jsx
frontend/src/component/Account/UserSpacesConfigLine.jsx
frontend/src/container/AdminUserSpacesConfig.jsx
frontend/src/container/Login.jsx
frontend/src/container/PersonalRecentActivities.jsx
frontend/src/container/ReduxTlmDispatcher.jsx
frontend/src/container/Tracim.jsx
frontend/src/container/WorkspacePage.jsx
frontend/src/reducer/workspaceList.js
frontend/test/src/component/UserSpacesConfig.spec.js
frontend/test/src/container/Tracim.spec.js
frontend_app_workspace_advanced/src/action.async.js
frontend_app_workspace_advanced/src/container/WorkspaceAdvanced.jsx
frontend_lib/src/action.async.js

Fix/3001  consecutive requests to members

---

frontend/src/container/AdvancedSearch.jsx
frontend/src/container/Favorites.jsx
frontend/test/src/container/AdvancedSearch.spec.js

feat(frontend): add loader to search and favorite

---

frontend/src/container/FeedItemWithPreview.jsx
functionnal_tests/cypress/integration/activity_feed/hidden_preview_activity_spec.js

Fix/5404  do not display preview of deleted contents

---

frontend/src/component/Account/PersonalData.jsx

fix(frontend): Update password position

---

frontend_lib/src/component/Tags/TagList.jsx

Issue #5666
- ~[] Automated tests covering the feature or the fix, have been written, deemed irrelevant (give the reason), or an issue has been created to implement the test (give the link)~

feat(frontend): Add loader to tag list

---

frontend/src/component/Dashboard/MemberList.jsx
frontend/src/container/Dashboard.jsx

Issue ref #5668
- ~[] Automated tests covering the feature or the fix, have been written, deemed irrelevant (give the reason), or an issue has been created to implement the test (give the link)~

feat(frontend): Add loader when adding/removing member from dashboard

---

frontend/src/container/WorkspacePage.jsx
frontend/src/css/Dashboard.styl
frontend_app_workspace_advanced/src/container/WorkspaceAdvanced.jsx

feat(front): add loaders on dashboard and member list in advanced dashboard

---

frontend/src/container/AdminUserSpacesConfig.jsx

Feat/5131  add loader to user spaces management

---

frontend_app_file/src/container/File.jsx
frontend_app_html-document/src/container/HtmlDocument.jsx
frontend_app_kanban/src/container/Kanban.jsx
frontend_app_thread/src/container/Thread.jsx
frontend_lib/src/appContentFactory.js
frontend_lib/src/component/Timeline/CommentArea.jsx
frontend_lib/src/component/Timeline/Timeline.jsx

fix(front): add loader on file comments

---

frontend/src/container/withActivity.jsx

Fix/5679  fix undefined on preview when there is a mention

---

frontend/src/container/ForgotPassword.jsx

feat(front):adding login redirection after password reset

---

backend/setup.py

fix(back):updating setup file to fix missing comma

---

backend/tracim_backend/tests/functional/test_user.py
backend/tracim_backend/tests/functional/test_webdav.py

No descriptions since this PR is destined to be a fix of typos done on 233d0ae877768a983dd8ed788b17633bf3048b3d

fix broken tests

---

frontend_lib/src/container/EmojiReactions.jsx

https://github.com/tracim/tracim/issues/4946

fix(front): remove flash message when loading content reactions

---

backend/tracim_backend/lib/core/content.py
backend/tracim_backend/tests/library/test_content_api.py
backend/tracim_backend/views/core_api/workspace_controller.py

Fix/5707  correct author when creating file from model

---

backend/tests_configs.ini
backend/tracim_backend/app_models/contents.py
backend/tracim_backend/lib/search/elasticsearch_search/elasticsearch_search.py
backend/tracim_backend/lib/search/elasticsearch_search/es_models.py
backend/tracim_backend/lib/search/elasticsearch_search/models.py
backend/tracim_backend/lib/search/models.py
backend/tracim_backend/lib/search/simple_search/models.py
backend/tracim_backend/lib/search/simple_search/simple_search_api.py
backend/tracim_backend/models/context_models.py
backend/tracim_backend/models/data.py
backend/tracim_backend/tests/functional/test_elasticsearch_search.py
backend/tracim_backend/tests/functional/test_simple_search.py
backend/tracim_backend/views/contents_api/comment_controller.py
backend/tracim_backend/views/search_api/schemas.py
frontend/src/container/SearchFilterMenu.jsx
frontend/src/util/helper.js

add todo to search

---

backend/tracim_backend/migration/versions/622464216ab7_convert_allowed_content_as_json.py

fix issue on migration script with existing server default value

---

frontend/src/container/ToDo.jsx
frontend/src/css/ToDo.styl
frontend_lib/src/component/ToDo/ToDo.styl

Issue ref #5754 
~~- [ ] Automated tests covering the feature or the fix, have been written, deemed irrelevant (give the reason), or an issue has been created to implement the test (give the link)~~ See #5726 

feat(frontend): add todo filter to todo page

---

frontend_app_collaborative_document_edition/src/container/PopupCreateOfficeDocument.jsx
frontend_lib/src/appContentFactory.js

Issue #5775 
~~- [ ] Automated tests covering the feature or the fix, have been written, deemed irrelevant (give the reason), or an issue has been created to implement the test (give the link)~~ See #3695

fix(frontend): add extension to files when creating a collaborative file

---

frontend/src/container/GroupedNotificationItem.jsx
frontend/src/container/NotificationWall.jsx

Issue ref #5785
~~- [ ] Automated tests covering the feature or the fix, have been written, deemed irrelevant (give the reason), or an issue has been created to implement the test (give the link)~~ See #5726 

fix(frontend): wrong text on group of tasks in the notification wall

---

backend/setup.cfg
frontend/i18next.scanner/ar/translation.json
frontend/i18next.scanner/de/translation.json
frontend/i18next.scanner/en/translation.json
frontend/i18next.scanner/es/translation.json
frontend/i18next.scanner/fr/translation.json
frontend/i18next.scanner/nb_NO/translation.json
frontend/i18next.scanner/pt/translation.json
frontend/src/container/Favorites.jsx
frontend/src/container/Publications.jsx
frontend/src/container/SimpleSearch.jsx
frontend/src/container/ToDo.jsx
frontend/src/container/WorkspaceContent.jsx
frontend/src/css/Publications.styl
frontend/src/css/SimpleSearch.styl
frontend/src/css/ToDo.styl
frontend/src/css/Workspace.styl
frontend_lib/src/component/EmptyListMessage/EmptyListMessage.jsx
frontend_lib/src/component/EmptyListMessage/EmptyListMessage.styl
frontend_lib/src/component/Layout/PageWrapper.styl
frontend_lib/src/css/Variable.styl
frontend_lib/src/index.js
functionnal_tests/cypress/integration/app_thread/operation_dashboard_dashboardbutton_create_thread.js
functionnal_tests/cypress/integration/helpers/file.js
functionnal_tests/cypress/integration/helpers/htmldoc.js
functionnal_tests/cypress/integration/helpers/thread.js
functionnal_tests/cypress/integration/search/search_contents_spec.js
functionnal_tests/cypress/integration/sidebar/presence_sidebar_allcontent.js
functionnal_tests/cypress/support/generic_selector_commands.js

feat(frontend): add text to display that there is no assigned tasks in `my tasks` page

---

frontend/src/component/Workspace/OpenContentApp.jsx
frontend/src/container/Sidebar.jsx
frontend/test/src/container/Sidebar.spec.js
frontend_app_file/src/container/File.jsx
frontend_app_html-document/src/container/HtmlDocument.jsx
frontend_app_kanban/src/container/Kanban.jsx

#5770
~- [ ] Automated tests covering the feature or the fix, have been written, deemed irrelevant (give the reason), or an issue has been created to implement the test (give the link)~ See #5726 

feat(frontend): disable to dos according to backend configuration

---

backend/doc/roles.md
backend/setup.cfg
backend/tracim_backend/lib/utils/authorization.py
backend/tracim_backend/lib/utils/request.py
frontend_lib/src/component/ToDo/ToDoItem.jsx

Issue #5781 
~~- [ ] Automated tests covering the feature or the fix, have been written, deemed irrelevant (give the reason), or an issue has been created to implement the test (give the link)~~ See #5726 

fix(backend): allow contributor and reader to check a todo if they are assignee

---

frontend_app_file/src/container/File.jsx
frontend_app_html-document/src/container/HtmlDocument.jsx
frontend_app_kanban/src/container/Kanban.jsx
frontend_lib/src/appContentFactory.js
frontend_lib/src/component/Input/TextAreaApp/TextAreaApp.jsx
frontend_lib/src/component/Timeline/CommentArea.jsx
frontend_lib/src/component/ToDo/NewToDo.jsx
frontend_lib/src/component/ToDo/ToDoManagement.jsx
frontend_lib/src/localStorage.js
frontend_lib/test/appContentFactory.spec.js
frontend_lib/test/localStorage.spec.js

#5787 
~- [ ] Automated tests covering the feature or the fix, have been written, deemed irrelevant (give the reason), or an issue has been created to implement the test (give the link)~ See #5726 

feat(frontend): add local storage for to dos

---

frontend/src/css/ToDo.styl
frontend_app_file/src/container/File.jsx
frontend_app_html-document/src/container/HtmlDocument.jsx
frontend_app_kanban/src/container/Kanban.jsx
frontend_lib/src/component/ToDo/ToDoManagement.jsx

Issue #5790 
~~- [ ] Automated tests covering the feature or the fix, have been written, deemed irrelevant (give the reason), or an issue has been created to implement the test (give the link)~~ See #5726 

fix(frontend): fix concurrency display of todos

---

backend/development.ini.sample
backend/doc/setting.md
backend/docker-compose-alternative.yml
backend/docker-compose.yml
tools_docker/elasticsearch_ingest/Dockerfile
tools_docker/opensearch_ingest/Dockerfile
tools_docker/opensearch_ingest/README.md

Feat/3642  opensearch compat doc

---

backend/.env
backend/README.md
backend/development.ini.sample
backend/doc/live_message_setup.md
backend/docker-compose-alternative.yml
backend/docker-compose-optional.yml
backend/docker-compose.yml
concourse/scripts/backend-full-tests
concourse/scripts/backend-quick-tests
concourse/scripts/install_docker
run_dev_backend.sh
tools_docker/concourse/Dockerfile

Doc: update docker-compose

---

frontend/dist/assets/branding.sample/welcome-simple-text.html

issue #5811
Add spanish on welcome page for new instance

misc(frontend): add spanish on welcome-simple-text.html

---

backend/setup.cfg
backend/tracim_backend/lib/core/content.py
backend/tracim_backend/tests/functional/test_content_templates.py
backend/tracim_backend/views/core_api/schemas.py
backend/tracim_backend/views/core_api/workspace_controller.py

Fix/5813  improve access to template

---

backend/setup.cfg
changelog.md
frontend/src/version.json

doc(release): create v4.3.2

---

frontend/src/component/Sidebar/SidebarUserItemList.jsx
frontend/src/container/Header.jsx
frontend/src/container/Sidebar.jsx
frontend/src/css/Sidebar.styl
frontend_app_collaborative_document_edition/src/container/CollaborativeEditionFrame.jsx
frontend_app_kanban/src/css/index.styl
frontend_lib/src/component/Layout/PageTitle.jsx
frontend_lib/src/css/Variable.styl
functionnal_tests/cypress/integration/account/account_main_page.js
functionnal_tests/cypress/integration/admin/content_admin_user.js
functionnal_tests/cypress/integration/admin/navigation_admin_user.js
functionnal_tests/cypress/integration/admin/navigation_admin_workspace.js
functionnal_tests/cypress/integration/login/login_after_disconnection_spec.js
functionnal_tests/cypress/integration/login/navigation_home-page_to_login-page.js

#5822 
~- [ ] Automated tests covering the feature or the fix, have been written, deemed irrelevant (give the reason), or an issue has been created to implement the test (give the link)~ We don't control the screen size on tests to test the kanban bug and the other informations are disabled 

fix(frontend): better handle collabora, kanban and custom button with new sidebar

---

backend/setup.cfg
backend/tracim_backend/lib/core/content.py
backend/tracim_backend/tests/functional/test_content_templates.py
backend/tracim_backend/views/core_api/schemas.py
backend/tracim_backend/views/core_api/workspace_controller.py
changelog.md
frontend/src/version.json

Merge maintenance 4.3.2 to develop

---

frontend/src/container/FeedItemWithPreview.jsx
frontend/src/container/Header.jsx
frontend/src/container/Publications.jsx
frontend/src/css/Header.styl
frontend_app_thread/src/container/Thread.jsx
frontend_lib/src/component/Timeline/Comment.jsx
functionnal_tests/cypress/integration/publication/file_spec.js

feat(frontend): make all news as threads

---

backend/doc/api.md
backend/tracim_backend/config.py
backend/tracim_backend/lib/search/elasticsearch_search/es_models.py
backend/tracim_backend/lib/search/elasticsearch_search/lang_analyzers/es.py

docs(backend) : memo Add curl example for Basic-Auth 

---

frontend_app_file/src/container/File.jsx
functionnal_tests/cypress/integration/app_file/file_header_spec.js

feat(frontend): add play button on app header

---

frontend/src/component/Activity/ActivityList.jsx
frontend/src/component/Activity/ContentWithoutPreviewActivity.jsx
frontend/src/component/FeedItem/FeedItemFooter.jsx
frontend/src/component/FeedItem/FeedItemFooter.styl
frontend/src/component/FeedItem/FeedItemHeader.jsx
frontend/src/container/FeedItemWithPreview.jsx
frontend/src/container/Publications.jsx
frontend/src/util/activity.js
frontend/test/src/activity.spec.js
frontend_app_gallery/src/css/index.styl
frontend_lib/src/component/Button/IconButton.styl
frontend_lib/src/component/Timeline/Comment.jsx
frontend_lib/src/component/Timeline/Comment.styl
frontend_lib/src/component/Timeline/CommentFilePreview.jsx
frontend_lib/src/component/Timeline/Timeline.jsx
frontend_lib/src/component/Timeline/Timeline.styl
frontend_lib/src/css/Variable.styl
frontend_lib/src/index.js
functionnal_tests/cypress/integration/activity_feed/show_discussion_spec.js
functionnal_tests/cypress/integration/publication/toggle_comments_spec.js

https://github.com/tracim/tracim/issues/5843

Feat/5843  show discussion on activities

---

frontend_app_file/src/component/FileComponent.jsx
frontend_app_file/src/component/PreviewComponent.jsx
frontend_app_file/src/container/File.jsx
functionnal_tests/cypress/integration/app_file/preview_video_spec.js
functionnal_tests/cypress/integration/app_file/video_play_spec.js
functionnal_tests/cypress/integration/publication/file_spec.js

feat(frontend): display the preview video on click on the preview

---

frontend/src/util/activity.js
functionnal_tests/cypress/integration/activity_feed/first_item_spec.js

fix(frontend): content go up activity feed when file attached

---

frontend/src/container/Sidebar.jsx
frontend/src/util/tinymceInit.js
frontend_app_collaborative_document_edition/src/container/CollaborativeEditionFrame.jsx
frontend_app_kanban/src/container/Kanban.jsx
functionnal_tests/cypress/integration/sidebar/close_when_fullscreen_spec.js

Feat/5879  close sidebar by default

---

backend/tracim_backend/applications/content_todo/schema.py

Issue ref: #5844
Update todo creation description in API description
~- [ ] Manual, quality tests have been done~
No test needed

:memo: Update todo creation description in API description

---

backend/README.md

The backend doc is not working about apt install lines. This PR suggests a working example.

doc: change apt install line to a working command line

---

backend/doc/minio-encryption.md
tools_docker/docker-compose-minio.yml
tools_docker/minio-encryption/docker-compose.yml
tools_docker/minio-encryption/kes-config/config.yml

This is an old branch but all information not exist in Tracim repo.
I think information lost when we done Min.IO support.

Minio encryption - documentation

---

backend/requirements-build.txt

fix(backend): update pip to 22.2.2 to repair CI

---

backend/requirements-build.txt

build(deps): revert pip version to 21.1.3

---

frontend_lib/src/component/Tags/NewTagForm.jsx
functionnal_tests/cypress/integration/tags/hide_tag_autocomplete_spec.js

Additionally, clicking inside show autocomplete
#5760 

fix(front): Clicking outside new tag input field now hides autocomplete.

---

frontend/src/action-creator.async.js
frontend/src/component/Activity/ActivityList.jsx
frontend/src/container/NotificationWall.jsx
frontend/src/container/Publications.jsx
frontend/src/container/withActivity.jsx
frontend/src/reducer/workspaceContentList.js
frontend/src/reducer/workspaceShareFolderContentList.js
frontend/src/util/helper.js
frontend/test/src/reducer/currentWorkspace.spec.js
frontend/test/src/reducer/workspaceContentList.spec.js
frontend/test/src/reducer/workspaceShareFolderContentList.spec.js
frontend_lib/src/helper.js

feat(frontend): remove constant CONTENT_NAMESPACE from frontend and use the one from frontend_lib

---

frontend/src/component/Account/UserInfo.jsx
frontend/src/component/Account/UserInfo.styl
frontend/test/src/component/UserInfo.spec.js
frontend/test/src/container/Account.spec.js
frontend/test/src/container/AdminAccount.spec.js
functionnal_tests/cypress/integration/account/content_account_spec.js

Feat/4570  add a profile customisation button in the account settings page

---

frontend_lib/src/component/CardPopup/CardPopup.styl

#5748
I just added scrolling on overflow on the CardPopup, this might fix the problem on other usages of this component if they were any, if not, there is no impacts

fix(frontend): Kanban card creation not fine depending on screen size

---

doc/BUILD.md

Issue #5949 
~~- [ ] Manual, quality tests have been done~~ Not relevant

doc: Fix error in building tracim source documentation

---

frontend/src/component/PublicProfile/ProfileMainBar.jsx
frontend/src/css/PublicProfile.styl
functionnal_tests/cypress/integration/profile/profile_interface_spec.js

feat(frontend):  add an account settings button in the profile customization page

---

frontend_lib/src/component/Timeline/Comment.styl

fix(frontend): overflowing comments when there is code

---

frontend/src/container/Login.jsx
frontend/src/container/Sidebar.jsx
frontend/src/container/Tracim.jsx

This dev allows to communicate with the mobile application WebView.
~- [ ] The original issue is up to date w.r.t the latest discussions and contains a short summary of the implemented solution~
~- [ ] Manual, quality tests have been done~ This dev can only be tested on the mobile app.

Feat/mobile  Communication with webview

---

frontend/src/container/FeedItemWithPreview.jsx
frontend_lib/src/component/Timeline/Comment.jsx
functionnal_tests/cypress/integration/activity_feed/activity_spec.js

[#5969](https://github.com/tracim/tracim/issues/5969)

fix(frontend): affecting value to props inside of component in FeedItemWithPreview

---

frontend/src/container/Publications.jsx

feat(frontend): Automatic scroll when click on news see more button

---

frontend/src/component/ContentListItem.styl
frontend/src/css/Favorites.styl

fix(frontend): Favorites are hard to read due to new font size

---

frontend/dist/index.html
frontend/dist/index.mak
frontend_app_admin_workspace_user/dist/index.html
frontend_app_agenda/dist/index.html
frontend_app_collaborative_document_edition/dist/index.html
frontend_app_custom-form/dist/index.html
frontend_app_file/dist/index.html
frontend_app_folder_advanced/dist/index.html
frontend_app_gallery/dist/index.html
frontend_app_html-document/dist/index.html
frontend_app_kanban/dist/index.html
frontend_app_share_folder_advanced/dist/index.html
frontend_app_thread/dist/index.html
frontend_app_workspace/dist/index.html
frontend_app_workspace_advanced/dist/index.html
frontend_lib/dist/index.html

feat(frontend): Increased the font boldness

---

backend/tests_configs.ini
backend/tracim_backend/app_models/contents.py
backend/tracim_backend/lib/webdav/resources.py
backend/tracim_backend/tests/functional/test_webdav.py

fix(backend, webdav): support kanban files with webdav

---

CHANGELOG.md
backend/setup.cfg
frontend/src/version.json

See #5999
- ~~[x] Manual, quality tests have been done~~ No tests, changes are documentation only

✨ Feat: prepare new release 4.4.1

---

CHANGELOG.md
backend/setup.cfg
backend/tests_configs.ini
backend/tracim_backend/app_models/contents.py
backend/tracim_backend/lib/webdav/resources.py
backend/tracim_backend/tests/functional/test_webdav.py
frontend/src/version.json

Merge maintenance 4.4.1 to develop

misc(frontend, backend): merge maintenance 4.4.1 to develop

---

CHANGELOG.md
backend/setup.cfg
frontend/src/version.json

doc(release): create v4.4.2

---

frontend/src/action-creator.async.js
frontend_lib/src/component/ErrorFlashMessageTemplateHtml/ErrorFlashMessageTemplateHtml.jsx

feat(frontend): "Unknown error" flash is now more descriptive

---

frontend_app_file/src/component/FileComponent.jsx
frontend_app_file/src/component/PreviewComponent.jsx
frontend_app_file/src/component/PreviewComponent.styl
frontend_app_file/src/container/File.jsx
frontend_app_file/test/component/PreviewComponent.spec.js
functionnal_tests/cypress/integration/app_file/preview_video_spec.js

#5996 
A smart way to reduce data transit while making it still readable would be to set "Steps" according to screen size, this could be thought about in another issue

feat(frontend): Improved preview size to make it readable

---

frontend/src/container/Publications.jsx
frontend_app_gallery/src/css/index.styl
frontend_lib/src/appContentFactory.js
frontend_lib/src/component/Timeline/CommentFilePreview.jsx

feat(frontend): preview files instead of downloading it in comments

---

frontend/src/component/Search/ContentItemSearch.jsx
frontend/src/component/Search/ContentItemSearch.styl
frontend/src/component/Workspace/ContentItem.jsx
frontend/src/component/Workspace/ContentItemHeader.jsx
frontend/src/component/Workspace/Folder.jsx
frontend/src/component/Workspace/Folder.styl
frontend/src/container/WorkspaceContent.jsx
frontend/src/css/ContentItem.styl
frontend/src/css/ContentItemHeader.styl
frontend/src/reducer/workspaceContentList.js
frontend/test/src/component/ContentItemSearch.spec.js

feat(frontend): add a last modification column in content listings

---

frontend/src/css/Sidebar.styl

#5966 
~- [ ] Automated tests covering the feature or the fix, have been written, deemed irrelevant (give the reason), or an issue has been created to implement the test (give the link)~ Just style.

fix(frontend): fix sidebar alignement

---

frontend_lib/src/appContentFactory.js
frontend_lib/src/helper.js
functionnal_tests/cypress/integration/publication/text_spec.js

Issue: #6048 
Cherry-pick from #6049 that already been reviewed, only tests are needed.

fix(frontend): consider also public name to autocompletion

---

CHANGELOG.md
backend/setup.cfg
frontend/src/version.json

misc(frontend): merge maintenance 4.4.2 to develop

---

backend/setup.cfg
frontend/src/version.json

doc(release): create v4.4.3 build_098

doc(release): create v4.4.3 build_098

---

backend/setup.cfg
frontend/src/version.json

doc(release): create v4.4.3 build_099

doc(release): create v4.4.3 build_099

---

doc/BUILD.md
doc/backend_specific/cli.md
doc/backend_specific/database.md
tools_docker/README.md

📝: Add a warning/remove documentation about mysql

---

frontend_app_file/src/container/File.jsx
frontend_app_html-document/src/container/HtmlDocument.jsx
frontend_app_kanban/src/container/Kanban.jsx
frontend_app_workspace_advanced/src/component/WorkspaceAdvancedConfiguration.jsx
frontend_app_workspace_advanced/src/container/WorkspaceAdvanced.jsx
frontend_lib/src/component/Tags/NewTagForm.jsx
frontend_lib/src/component/Tags/Tag.jsx
frontend_lib/src/component/Tags/TagList.jsx

#6088
~- [ ] Automated tests covering the feature or the fix, have been written, deemed irrelevant (give the reason), or an issue has been created to implement the test (give the link)~ Since the colors are customizable and it is just a matter of style, tests are not necessary.

Fix/6088 add customColor to Tag component

---

frontend_lib/src/component/TinyEditor/TinyEditor.jsx

fix(frontend): better mention display

---

concourse/scripts/install_docker

ci: fix docker installation when already installed

---

backend/tracim_backend/lib/core/event.py
backend/tracim_backend/lib/core/user.py
backend/tracim_backend/lib/core/userworkspace.py
backend/tracim_backend/lib/crud_hook/caller.py
backend/tracim_backend/lib/crud_hook/hookspec.py
backend/tracim_backend/models/tracim_session.py

When creating a new user.
Ref: #4652
-------

perf(backend): improve creation of messages history

---

frontend_lib/src/component/Timeline/Revision.jsx

fix(frontend): translate document state

---

frontend_app_html-document/src/container/HtmlDocument.jsx
frontend_lib/src/component/Avatar/Avatar.jsx
frontend_lib/src/component/Timeline/CommentArea.jsx
frontend_lib/src/component/TinyEditor/TinyEditor.jsx
frontend_lib/src/component/TinyEditor/TinyEditor.styl
frontend_lib/src/css/Variable.styl
functionnal_tests/cypress/integration/generic_frontend/operation_tinymce.js
functionnal_tests/cypress/integration/links/autocomplete_link_spec.js
functionnal_tests/cypress/integration/notification_wall/notification_button_sidebar_spec.js

~~- [ ] The original issue is up to date w.r.t the latest discussions and contains a short summary of the implemented solution~~
~~- [ ] Original authors of the features included in a multi-feature branch (maintenance fixes -> develop, security fixes -> develop, …) should be part of the reviewers, especially if you encountered merge …

fix(frontend): apply suggestions

---

frontend_lib/src/mentionOrLink.js

fix(frontend): remove lookbehind

---

frontend_lib/test/mention.spec.js

Fix mention tests due to regex change ;
Add some tests about mentions

fix(frontend): mention tests

---

frontend/src/action-creator.sync.js
frontend/src/reducer/notificationPage.js
frontend/test/src/reducer/notificationPage.spec.js

Issue ref #6134
~~- [ ] Manual, quality tests have been done~~ tests will be done in preproduction

fix(frontend): correctly reduce the mention number

---

frontend_lib/src/component/TinyEditor/TinyEditor.jsx

Issue ref #6142 
~~- [ ] Automated tests covering the feature or the fix, have been written, deemed irrelevant (give the reason), or an issue has been created to implement the test (give the link)~~ See #6144
~~- [ ] Manual, quality tests have been done~~ tests will be done in preproduction

fix(frontend): don't apply shortcut to send comment if editor content is empty

---

frontend_lib/src/component/Avatar/Avatar.jsx

Issue ref #6145 
~~- [ ] Automated tests covering the feature or the fix, have been written, deemed irrelevant (give the reason), or an issue has been created to implement the test (give the link)~~ Not relevant

fix(frontend): remove alt avatar

---

doc/backend/migrate_storage.md
frontend/src/container/ForgotPassword.jsx
frontend/src/container/Login.jsx
tools_docker/README.md

Mainly documentation changes
Also change timer before popup disapear

fix(documentation): update documentation

---

frontend/src/component/Account/PersonalData.jsx
frontend/src/util/helper.js
frontend/test/src/component/PersonalData.spec.js

https://github.com/tracim/tracim/issues/6172

fix(front): disable user field edition when not using auth type internal

---

.pre-commit-config.yaml
backend/development.ini.sample
backend/tests_configs.ini
backend/tracim_backend/config.py
backend/tracim_backend/lib/core/user.py
backend/tracim_backend/tests/functional/test_reset_password.py
backend/tracim_backend/tests/functional/test_session.py
backend/tracim_backend/tests/functional/test_user.py
backend/tracim_backend/tests/functional/test_workspaces.py
backend/tracim_backend/tests/library/test_user_api.py
doc/backend/env_settings.md
doc/backend/migrate_from_v1.md
doc/backend/setting.md
frontend_lib/src/helper.js
frontend_lib/src/mentionOrLink.js

feat: authorize the use of dot in a username

---

CHANGELOG.md
backend/setup.cfg
frontend/src/version.json

Doc: Prepare new release 4.5.1

---

backend/tracim_backend/applications/collaborative_document_edition/controller.py

quick fix, seen with @PhilippeAccorsi

fix: rename incorrect import

---

frontend_lib/src/component/TinyEditor/TinyEditor.styl

https://github.com/tracim/tracim/issues/6087

fix(front): change css to increase the size of emoji in TinyMCE

---

backend/tracim_backend/models/data.py
concourse/pipelines/pull-request.yml

https://github.com/tracim/tracim/issues/6201

fix(backend): add lazy loading for workspace description

---

backend/setup.cfg
frontend/src/version.json

doc(release): create v4.5.1 build_117

---

CHANGELOG.md
backend/setup.cfg
frontend/src/version.json

https://github.com/tracim/tracim/issues/6215
- ~~[ ] Manual, quality tests have been done~~ No test necessary here

doc(release): create v4.6.0

---

CHANGELOG.md
backend/setup.cfg
frontend/src/version.json

https://github.com/tracim/tracim/issues/6225

Doc: prepare new release 4.6.1

---

backend/tracim_backend/lib/core/mention.py

No Issue related
~~- [ ] The original issue is up to date w.r.t the latest discussions and contains a short summary of the implemented solution~~

fix(backend): user username instead of public name

---

frontend/src/container/FeedItemWithPreview.jsx

https://github.com/tracim/tracim/issues/6192

fix(front): change the members list used for the mention

---

backend/tracim_backend/command/periodic.py
backend/tracim_backend/models/auth.py
concourse/pipelines/pull-request.yml

https://github.com/tracim/tracim/issues/6219

fix(backend): disable mail notification to deactivated users

---

backend/settings_saml2.json
backend/setup.cfg
backend/tracim_backend/config.py
backend/tracim_backend/lib/core/system.py
backend/tracim_backend/lib/utils/authentication.py
backend/tracim_backend/models/context_models.py
backend/tracim_backend/views/core_api/schemas.py
doc/backend/setting.md
frontend/src/component/Login/SignIn.jsx
frontend/src/css/Login.styl

https://github.com/tracim/tracim/issues/6209
https://github.com/tracim/tracim/issues/6210
https://github.com/tracim/tracim/issues/6212
This PR comes from https://github.com/tracim/tracim/pull/6232 so they need to be merged in order, ideally

Feat: Configuration for mapping saml attributes to user properties

---

backend/setup.cfg
frontend/src/container/FeedItemWithPreview.jsx
frontend/src/version.json

https://github.com/tracim/tracim/issues/6238
The commit "fix(front): change the list of member use for mention " has been cherry picked from develop

Doc prepare new release 04.06.02 build 118

---

CHANGELOG.md
backend/setup.cfg
frontend/src/version.json

https://github.com/tracim/tracim/issues/6240

doc(release): create v4.6.2

---

doc/backend/setting.md

https://github.com/tracim/tracim/pull/6232

fix(doc): improve documentation related to saml configuration

---

doc/backend/setting.md

Feat: adding documentation on connecting tracim to a Redis cluster

---

backend/development.ini.sample
backend/tracim_backend/config.py
backend/tracim_backend/lib/search/elasticsearch_search/elasticsearch_search.py

https://github.com/tracim/tracim/issues/6257

Feat: allow elastic to search in an elasticsearch cluster containing several nodes

---

backend/tracim_backend/__init__.py
doc/backend/hello_world_plugin.py
doc/backend/plugins.md

Feat: add the ability to access configurator in plugins loaded hook

---

CHANGELOG.md
backend/setup.cfg
frontend/src/version.json

doc(release): create v4.7.0 build_119 [skip ci]

---

backend/tracim_backend/views/core_api/user_controller.py
frontend/src/action-creator.sync.js
frontend/src/container/ReduxTlmDispatcher.jsx
frontend/src/container/Sidebar.jsx
frontend/src/reducer/workspaceList.js
frontend/test/fixture/user/globalManagerSetting.js
frontend/test/fixture/user/globalSetting.js
frontend/test/src/reducer/workspaceList.spec.js

https://github.com/tracim/tracim/issues/6276

fix(frontend) : fix reducer for setting when creating a space

---

backend/tracim_backend/lib/core/user.py
backend/tracim_backend/models/context_models.py
backend/tracim_backend/tests/functional/test_user.py
backend/tracim_backend/views/core_api/schemas.py
backend/tracim_backend/views/core_api/user_controller.py
frontend/src/action-creator.async.js
frontend/src/action-creator.sync.js
frontend/src/component/Mention/Mention.jsx
frontend/src/container/Dashboard.jsx
frontend/src/container/FeedItemWithPreview.jsx
frontend/src/container/Login.jsx
frontend/src/container/Tracim.jsx
frontend/src/reducer/currentWorkspace.js
frontend/src/reducer/knownMemberList.js
frontend/src/reducer/root.js
frontend/src/reducer/user.js
frontend/test/fixture/user/globalManagerAsDigestSchema.js
frontend/test/fixture/workspaceSetting/globalManagerWorkspaceSetting.js
frontend/test/setup.js
frontend/test/src/container/Account.spec.js
frontend/test/src/container/Tracim.spec.js
frontend/test/src/reducer/currentWorkspace.spec.js
frontend/test/src/reducer/knownMemberList.spec.js
frontend/test/src/reducer/workspaceList.spec.js
functionnal_tests/cypress/integration/recent_activity/activity_spec.js

fix(back, front): mentions in recent activities

---

CHANGELOG.md
backend/setup.cfg
frontend/src/version.json

https://github.com/tracim/tracim/issues/6282

Doc: prepare new release 4.7.0 build_120

---

backend/tracim_backend/lib/core/user.py

fix(backend): known_members don't filter deleted users and workspaces

---

frontend/src/container/ReduxTlmDispatcher.jsx
frontend/src/reducer/knownMemberList.js

https://github.com/tracim/tracim/issues/6284
https://github.com/tracim/tracim/issues/6285

fix(frontend) fix reducer when user leave a space or join a new one

---

frontend/src/container/Favorites.jsx

fix: fixed favorites crash on load

---

frontend/src/reducer/currentWorkspace.js
frontend/src/reducer/workspaceList.js
frontend/test/fixture/workspace/firstWorkspace.js
frontend/test/src/component/OpenContentApp.spec.js
frontend/test/src/reducer/currentWorkspace.spec.js
frontend/test/src/reducer/workspaceList.spec.js

fix(front): avoid serializeWorkspace to overrides memberList

---

backend/setup.cfg
frontend/src/version.json

https://github.com/tracim/tracim/issues/6296

Doc: prepare new build 4.7.0+build_121

---

frontend/src/container/Dashboard.jsx

https://github.com/tracim/tracim/issues/6298

fix(front): fix subscription request send to check role from workspaceList instead of currentList

---

doc/backend/setting.md

Update backend setting.md to add info about metadata section of saml config

doc: update backend setting.md to add info about metadata section of saml config

---

backend/tracim_backend/lib/utils/authentication.py

fix(backend): prevent login through saml with no profile match

---

CHANGELOG.md
backend/setup.cfg
frontend/src/version.json

https://github.com/tracim/tracim/issues/6326

Prepare new release 4.7.1

---

CHANGELOG.md
backend/setup.cfg
frontend/src/component/Login/FooterLogin.jsx
frontend/src/container/Sidebar.jsx
frontend/src/version.json

https://github.com/tracim/tracim/issues/6334

Prepare new release 4.7.1+build_123

---

frontend/src/container/NotificationWall.jsx
frontend/src/css/NotificationWall.styl

fix(frontend): added missing title on button to mark all notification as read

---

frontend/package.json
frontend_app_admin_workspace_user/package.json
frontend_app_agenda/package.json
frontend_app_collaborative_document_edition/package.json
frontend_app_custom-form/package.json
frontend_app_file/package.json
frontend_app_folder_advanced/package.json
frontend_app_gallery/package.json
frontend_app_html-document/package.json
frontend_app_kanban/package.json
frontend_app_share_folder_advanced/package.json
frontend_app_thread/package.json
frontend_app_workspace/package.json
frontend_app_workspace_advanced/package.json
frontend_lib/package.json
i18next.scanner.js
yarn.lock

fix(frontend): upgrade i18nextscanner to 4.4.0

---

frontend/i18next.scanner/ar/translation.json
frontend/i18next.scanner/de/translation.json
frontend/i18next.scanner/en/translation.json
frontend/i18next.scanner/es/translation.json
frontend/i18next.scanner/fr/translation.json
frontend/i18next.scanner/nb_NO/translation.json
frontend/i18next.scanner/pt/translation.json
frontend/src/container/Publications.jsx

fix(front): set better label for news title popup

---

frontend/.gitignore
frontend_app_admin_workspace_user/.gitignore
frontend_app_agenda/.gitignore
frontend_app_collaborative_document_edition/.gitignore
frontend_app_custom-form/.gitignore
frontend_app_file/.gitignore
frontend_app_folder_advanced/.gitignore
frontend_app_gallery/.gitignore
frontend_app_html-document/.gitignore
frontend_app_kanban/.gitignore
frontend_app_share_folder_advanced/.gitignore
frontend_app_thread/.gitignore
frontend_app_workspace/.gitignore
frontend_app_workspace_advanced/.gitignore

fix(front): add license files to gitignore

---

CHANGELOG.md
backend/setup.cfg
frontend/src/version.json

https://github.com/tracim/tracim/issues/6345

Prepare new release 4.7.1+build_124

---

frontend/src/container/ReduxTlmDispatcher.jsx
frontend/src/container/WorkspaceContent.jsx
frontend_app_kanban/i18next.scanner/ar/translation.json
frontend_app_kanban/i18next.scanner/de/translation.json
frontend_app_kanban/i18next.scanner/en/translation.json
frontend_app_kanban/i18next.scanner/es/translation.json
frontend_app_kanban/i18next.scanner/fr/translation.json
frontend_app_kanban/i18next.scanner/nb_NO/translation.json
frontend_app_kanban/i18next.scanner/pt/translation.json
frontend_app_kanban/src/component/Kanban.jsx
frontend_app_kanban/src/component/KanbanCardEditor.jsx

fix(frontend): stabilize kanbans

---

backend/requirements.txt
backend/setup.py

fix(backend): add pysaml2 in setup.py

---

backend/tracim_backend/lib/core/user.py

fix(backend): LDAP auth flow doesn't compromise auth for "internal as unknown" users anymore

---

frontend/src/container/NotificationWall.jsx
frontend/src/css/NotificationWall.styl

https://github.com/tracim/tracim/issues/6375

fix(front): fix filter input in notification wall on firefox

---

frontend_app_workspace/src/css/index.styl
functionnal_tests/cypress/integration/app_interface/switching_same_apps_feature_spec.js

fix(frontend): improved responsiveness for space creation popup

---

CHANGELOG.md
backend/setup.cfg
frontend/src/version.json

Prepare new release 4.8.0+build_125

---

CHANGELOG.md

#6388 
- ~~[ ] Manual, quality tests have been done~~ No test necessary here

doc: added pr review for changelog for 4.9.0

---

backend/development.ini.sample
tools_docker/Debian_New_Uwsgi/Dockerfile
tools_docker/Debian_Uwsgi/Dockerfile
tools_docker/Debian_Uwsgi_ARM64/Dockerfile

fix: add new logbook app to dockerfile and in some config/documentation files

---

frontend/src/container/ReduxTlmDispatcher.jsx
frontend/src/util/activity.js
frontend_lib/src/helper.js

fix: added logbook and notifications to recent activities

---

frontend/src/component/Dashboard/UserStatus.jsx
frontend/src/container/Dashboard.jsx

fix(frontend): added optional chaining on currentWorkspace props

---

CHANGELOG.md
backend/setup.cfg
frontend/src/version.json

https://github.com/tracim/tracim/issues/6405

Prepare new release 4.8.0+build_126

---

README.md
frontend_lib/src/css/Generic.styl

https://github.com/tracim/tracim/issues/6407

fix(front): fix true delete border top color

---

frontend/src/component/Publication/PopupSetPublicationTitle.jsx
frontend/src/container/PopupSetPublicationTitle.jsx
frontend/src/container/Publications.jsx

https://github.com/tracim/tracim/issues/6408

fix(front): news re-render with each characters when writing title

---

frontend_lib/src/helper.js

fix(frontend): added falsy string check in stripEmojis

---

CHANGELOG.md
backend/setup.cfg
frontend/src/version.json

https://github.com/tracim/tracim/issues/6420

Prepare new release 4.8.0+build_127

---

frontend_app_file/src/container/File.jsx
frontend_app_html-document/src/container/HtmlDocument.jsx
frontend_app_html-document/src/css/index.styl
frontend_app_kanban/src/container/Kanban.jsx
frontend_app_logbook/src/container/Logbook.jsx
frontend_app_thread/src/container/Thread.jsx
frontend_app_thread/src/css/index.styl
frontend_lib/src/component/PopinFixed/PopinFixed.styl
frontend_lib/src/component/PopinFixed/PopinFixedContent.jsx
frontend_lib/src/component/PopinFixed/PopinFixedHeader.jsx
frontend_lib/test/component/PopinFixed.spec.js
frontend_lib/test/component/PopinFixedContent.spec.js
functionnal_tests/cypress/integration/emojireactions/emojireactions_spec.js

https://github.com/tracim/tracim/issues/6432

fix(front): move emoji reaction to live bellow header

---

CHANGELOG.md
backend/setup.cfg
frontend/src/version.json

https://github.com/tracim/tracim/issues/6434

Prepare new release 4.8.0+build_128

---

backend/tracim_backend/command/periodic.py
backend/tracim_backend/locale/ar/LC_MESSAGES/tracim_backend.po
backend/tracim_backend/locale/de/LC_MESSAGES/tracim_backend.po
backend/tracim_backend/locale/en/LC_MESSAGES/tracim_backend.po
backend/tracim_backend/locale/eo/LC_MESSAGES/tracim_backend.po
backend/tracim_backend/locale/es/LC_MESSAGES/tracim_backend.po
backend/tracim_backend/locale/fr/LC_MESSAGES/tracim_backend.po
backend/tracim_backend/locale/it/LC_MESSAGES/tracim_backend.po
backend/tracim_backend/locale/ja/LC_MESSAGES/tracim_backend.po
backend/tracim_backend/locale/nb_NO/LC_MESSAGES/tracim_backend.po
backend/tracim_backend/locale/nl/LC_MESSAGES/tracim_backend.po
backend/tracim_backend/locale/pt/LC_MESSAGES/tracim_backend.po
backend/tracim_backend/models/data.py
frontend/src/component/Dashboard/UserStatus.styl
frontend/src/component/EmailNotificationTypeButton/EmailNotificationTypeButton.jsx
frontend_app_file/src/container/File.jsx
frontend_app_html-document/src/container/HtmlDocument.jsx
frontend_app_kanban/src/container/Kanban.jsx
frontend_app_logbook/src/component/LogbookEntry.jsx
frontend_app_logbook/src/container/Logbook.jsx
frontend_app_logbook/src/css/index.styl
frontend_lib/src/component/PopinFixed/PopinFixedContent.jsx
tools_docker/Debian_New_Uwsgi/common.sh
tools_docker/Debian_New_Uwsgi/cron_task_tracim_send_summary_mails.sample
tools_docker/Debian_New_Uwsgi/send_summary_mails.sh.sample
tools_docker/Debian_Uwsgi/common.sh
tools_docker/Debian_Uwsgi/send_summary_mails.sh.sample

https://github.com/tracim/tracim/issues/6436

fix(back and front): fix bug of build 128

---

CHANGELOG.md
backend/setup.cfg
frontend/src/version.json

https://github.com/tracim/tracim/issues/6438

Prepare new release 4.8.0+build_129

---

frontend_app_file/src/container/File.jsx
frontend_app_html-document/src/container/HtmlDocument.jsx
frontend_app_kanban/src/container/Kanban.jsx
frontend_app_logbook/src/container/Logbook.jsx
frontend_app_thread/src/container/Thread.jsx
frontend_lib/src/appContentFactory.js
frontend_lib/src/component/Timeline/Comment.jsx
frontend_lib/src/component/Timeline/Timeline.jsx

https://github.com/tracim/tracim/issues/6427

fix(front): allow permanently delete comment

---

backend/tracim_backend/migration/versions/2cfb200caf44_add_period_to_summary_mail.py
frontend_app_thread/src/css/index.styl
frontend_lib/src/helper.js
functionnal_tests/cypress/integration/app_interface/switching_same_apps_feature_spec.js
functionnal_tests/cypress/integration/notification_wall/filter_notification_spec.js

various bugfixes before release

---

CHANGELOG.md
frontend_app_thread/src/container/Thread.jsx

Fix/x  add missing dash app thread emoji

---

backend/official_plugins/tracim_backend_video_alert/README.md
backend/official_plugins/tracim_backend_video_alert/__init__.py

fix(frontend): changed default message for video_alert plugin

---

frontend_app_kanban/src/component/KanbanCard.jsx

Fix(frontend): change kanban menu color dynamically

---

CHANGELOG.md
backend/setup.cfg
frontend/src/version.json

Prepare new release 4.8.0+build_130

---

frontend_app_logbook/src/css/index.styl

fix(frontend): changed color of dot in logbook timeline

---

backend/official_plugins/tracim_backend_video_alert/__init__.py
frontend/i18next.scanner/fr/translation.json
frontend/src/component/EmailNotificationTypeButton/PopoverHelperBody.jsx
frontend_lib/src/component/PopinFixed/PopinFixed.styl

fix(front): fix translation and add border for title editing

---

backend/setup.cfg
frontend/src/version.json

https://github.com/tracim/tracim/issues/6462

Prepare new release 4.8.0+build_131

---

frontend_app_file/src/component/FileComponent.jsx
frontend_app_html-document/src/component/HtmlDocument.jsx
frontend_app_kanban/src/component/Kanban.jsx
frontend_app_logbook/src/component/Logbook.jsx
frontend_lib/src/component/PromptMessage/PromptMessage.jsx
frontend_lib/src/component/Timeline/Timeline.jsx
frontend_lib/src/helper.js

fix(frontend): icons for restore/restored are now different

---

frontend_app_logbook/src/component/LogbookEntryEditor.jsx

fix(frontend): added support for past-noon dates

---

frontend_app_logbook/i18next.scanner/ar/translation.json
frontend_app_logbook/i18next.scanner/de/translation.json
frontend_app_logbook/i18next.scanner/en/translation.json
frontend_app_logbook/i18next.scanner/es/translation.json
frontend_app_logbook/i18next.scanner/fr/translation.json
frontend_app_logbook/i18next.scanner/nb_NO/translation.json
frontend_app_logbook/i18next.scanner/pt/translation.json
frontend_app_logbook/src/component/Logbook.jsx
frontend_app_logbook/src/css/index.styl

fix(frontend): bug missing confirm popin when deleting an item from a logbook

---

frontend/src/container/WorkspaceContent.jsx

fix(frontend): disable rendering of static elements while loading content list

---

frontend_app_kanban/src/css/index.styl
frontend_app_logbook/src/css/index.styl

fix(frontend): add margin to logbook and kanban overlapping elements when in fullscreen

---

frontend_app_logbook/src/component/LogbookEntry.jsx
frontend_app_logbook/src/css/index.styl
frontend_lib/src/helper.js

fix(frontend): added dynamic color on logbook timestamp

---

CHANGELOG.md
backend/setup.cfg
frontend/src/version.json

https://github.com/tracim/tracim/issues/6483

Prepare new release 4.9.0+build_132

---

CHANGELOG.md
backend/setup.cfg
frontend/src/version.json

Prepare new release 4.9.1

---

CHANGELOG.md
backend/setup.cfg
frontend/src/version.json

Revert "Prepare new release 4.9.1"

---

CHANGELOG.md
backend/setup.cfg
frontend/src/container/WorkspaceContent.jsx
frontend/src/version.json
frontend_app_file/src/component/FileComponent.jsx
frontend_app_html-document/src/component/HtmlDocument.jsx
frontend_app_kanban/src/component/Kanban.jsx
frontend_app_kanban/src/css/index.styl
frontend_app_logbook/i18next.scanner/ar/translation.json
frontend_app_logbook/i18next.scanner/de/translation.json
frontend_app_logbook/i18next.scanner/en/translation.json
frontend_app_logbook/i18next.scanner/es/translation.json
frontend_app_logbook/i18next.scanner/fr/translation.json
frontend_app_logbook/i18next.scanner/nb_NO/translation.json
frontend_app_logbook/i18next.scanner/pt/translation.json
frontend_app_logbook/src/component/Logbook.jsx
frontend_app_logbook/src/component/LogbookEntry.jsx
frontend_app_logbook/src/component/LogbookEntryEditor.jsx
frontend_app_logbook/src/css/index.styl
frontend_lib/src/component/PromptMessage/PromptMessage.jsx
frontend_lib/src/component/Timeline/Timeline.jsx
frontend_lib/src/helper.js

Misc: merge 4.9.1 into develop

---

backend/requirements-db-postgres.txt
backend/requirements-devtool.txt
backend/requirements-full-preview-generator.txt
backend/requirements-test.txt
backend/requirements.txt
backend/setup.py
backend/tracim_backend/tests/library/test_tracim_context.py
concourse/pipelines/pull-request.yml
concourse/scripts/backend-full-tests
concourse/scripts/backend-lint
concourse/scripts/backend-quick-tests
concourse/scripts/end-to-end-cypress-tests
tools_docker/concourse/Dockerfile

Feat/6360  support python 3.9 3.10 3.11

---

CHANGELOG.md
backend/setup.cfg
frontend/src/version.json

https://github.com/tracim/tracim/issues/6496

Prepare new release 4.9.1+build_133

---

frontend_app_kanban/src/css/index.styl
frontend_app_logbook/src/css/index.styl

https://github.com/tracim/tracim/issues/6502

Fix/6502  fix horizontal scrollbar in app kanban

---

CHANGELOG.md
backend/setup.cfg
frontend/src/version.json

Prepare release 4.9.1+build_134

---

CHANGELOG.md
backend/setup.cfg
frontend/src/version.json

Prepare new release 4.9.2

---

CHANGELOG.md
backend/setup.cfg
frontend/src/version.json
frontend_app_kanban/src/css/index.styl
frontend_app_logbook/src/css/index.styl

Misc: merge 4.9.2 into develop

---

backend/tracim_backend/lib/core/user.py
backend/tracim_backend/tests/functional/test_elasticsearch_search.py
backend/tracim_backend/tests/functional/test_live_messages.py
backend/tracim_backend/tests/functional/test_user_call.py
backend/tracim_backend/views/core_api/schemas.py
backend/tracim_backend/views/core_api/user_controller.py
frontend/src/reducer/knownMemberList.js
frontend_lib/src/component/TinyEditor/TinyEditor.jsx

https://github.com/tracim/tracim/issues/6398

fix: remove inactive users from autocomplete in the recent activities page

---

frontend/i18next.scanner/ar/translation.json
frontend/i18next.scanner/de/translation.json
frontend/i18next.scanner/en/translation.json
frontend/i18next.scanner/es/translation.json
frontend/i18next.scanner/fr/translation.json
frontend/i18next.scanner/nb_NO/translation.json
frontend/i18next.scanner/pt/translation.json
frontend/src/container/NotificationWall.jsx

https://github.com/tracim/tracim/issues/6498

feat: merge notifications in the notification wall

---

backend/tracim_backend/lib/core/system.py
backend/tracim_backend/models/context_models.py
backend/tracim_backend/views/core_api/schemas.py
doc/backend/branding.md
frontend/dist/assets/branding.sample/app_custom_actions.json
frontend/src/component/Workspace/ContentItem.jsx
frontend_app_file/src/container/File.jsx
frontend_app_folder_advanced/src/container/FolderAdvanced.jsx
frontend_app_html-document/src/container/HtmlDocument.jsx
frontend_app_kanban/src/container/Kanban.jsx
frontend_app_logbook/src/container/Logbook.jsx
frontend_app_thread/src/container/Thread.jsx
frontend_lib/src/appCustomAction.js
frontend_lib/src/index.js
frontend_lib/test/appCustomAction.spec.js

https://github.com/tracim/tracim/issues/6250

feat(back, front): allow multiple location to show app custom actions

---

backend/development.ini.sample

https://github.com/tracim/tracim/issues/6399

fix(doc): add missing kanban for web.notifications.excluded doc

---

frontend_app_kanban/i18next.scanner/ar/translation.json
frontend_app_kanban/i18next.scanner/de/translation.json
frontend_app_kanban/i18next.scanner/en/translation.json
frontend_app_kanban/i18next.scanner/es/translation.json
frontend_app_kanban/i18next.scanner/fr/translation.json
frontend_app_kanban/i18next.scanner/nb_NO/translation.json
frontend_app_kanban/i18next.scanner/pt/translation.json
frontend_app_kanban/src/component/KanbanColumnHeader.jsx
frontend_app_kanban/src/css/index.styl

https://github.com/tracim/tracim/issues/4189

feat(front): add numbers of card to each colum in kanban

---

CHANGELOG.md
backend/setup.cfg
frontend/src/version.json

Prepare release 4.9.2+build_136

---

backend/development.ini.sample
backend/tracim_backend/applications/content_file/controller.py
backend/tracim_backend/config.py
backend/tracim_backend/lib/core/content.py

https://github.com/tracim/tracim/issues/6500

feat(back): add a configurable list of extensions to skip preview

---

frontend/i18next.scanner/ar/translation.json
frontend/i18next.scanner/de/translation.json
frontend/i18next.scanner/en/translation.json
frontend/i18next.scanner/es/translation.json
frontend/i18next.scanner/fr/translation.json
frontend/i18next.scanner/nb_NO/translation.json
frontend/i18next.scanner/pt/translation.json
frontend/src/container/NotificationWall.jsx

https://github.com/tracim/tracim/issues/6534

fix(frontend): add translations for web notification related elements

---

frontend/src/container/Tracim.jsx
frontend/src/reducer/notificationPage.js
frontend/test/src/reducer/notificationPage.spec.js

https://github.com/tracim/tracim/issues/6534

fix(frontend): prevented notifications from reappearing

---

frontend_app_logbook/src/component/LogbookEntry.jsx
frontend_app_logbook/src/component/LogbookEntry.styl

https://github.com/tracim/tracim/issues/6534
https://github.com/tracim/tracim/issues/6539

fix(frontend): added more lines to the logbook entry preview

---

CHANGELOG.md
backend/setup.cfg
frontend/src/version.json

https://github.com/tracim/tracim/issues/6544

Prepare release 4.9.2+build_137

---

frontend_lib/src/component/Breadcrumbs/Breadcrumbs.jsx
frontend_lib/src/component/Breadcrumbs/Breadcrumbs.styl

https://github.com/tracim/tracim/issues/6524

fix(front): improve breadcrumbs

---

frontend_app_kanban/src/component/KanbanCard.jsx
frontend_app_kanban/src/component/KanbanColumnHeader.jsx
functionnal_tests/cypress/integration/app_kanban/kanban_cards_spec.js
functionnal_tests/cypress/integration/app_kanban/kanban_columns_spec.js

https://github.com/tracim/tracim/issues/6542

fix(front): use confirm popup componant in the kanban card for delete

---

CHANGELOG.md

https://github.com/tracim/tracim/issues/6555

Prepare new release 4.10.0+build_138

---

frontend_lib/src/component/Breadcrumbs/Breadcrumbs.jsx
frontend_lib/src/component/Breadcrumbs/Breadcrumbs.styl

https://github.com/tracim/tracim/issues/6558

fix(frontend): removed underline on space in breadcrumbs

---

frontend/src/component/EmailNotificationTypeButton/PopoverHelperBody.styl

fix: set max size for mobile email helper popin

---

frontend/i18next.scanner/ar/translation.json
frontend/i18next.scanner/de/translation.json
frontend/i18next.scanner/en/translation.json
frontend/i18next.scanner/es/translation.json
frontend/i18next.scanner/fr/translation.json
frontend/i18next.scanner/nb_NO/translation.json
frontend/i18next.scanner/pt/translation.json
frontend/src/component/Sidebar/SidebarSpaceItem.jsx

https://github.com/tracim/tracim/issues/6561

feat(frontend): added icon to muted spaces

---

CHANGELOG.md
backend/setup.cfg
frontend/src/version.json

Prepare release 4.10.0+build_139

---

concourse/README.md
doc/backend/env_settings.md

doc(back): improve concourse documentation and add missing backend env setting

---

doc/backend/env_settings.md

https://github.com/tracim/tracim/issues/6567
- ~~Manual, quality tests have been done~~ Not necessary here

doc(env_settings): fixed invalid entry in env_settings.md

---

backend/setup.cfg
frontend/src/version.json

https://github.com/tracim/tracim/issues/6569

Prepare release 4.10.0+build_140

---

backend/setup.cfg
frontend/src/version.json

https://github.com/tracim/tracim/issues/6575

Prepare release 4.10.0+build_141

---

frontend/dist/index.html
frontend_lib/src/appContentFactory.js

https://github.com/tracim/tracim/issues/6557

fix(front): add generic handling for tlm content deleted and restored

---

.editorconfig
frontend_app_logbook/i18next.scanner/ar/translation.json
frontend_app_logbook/i18next.scanner/de/translation.json
frontend_app_logbook/i18next.scanner/en/translation.json
frontend_app_logbook/i18next.scanner/es/translation.json
frontend_app_logbook/i18next.scanner/fr/translation.json
frontend_app_logbook/i18next.scanner/nb_NO/translation.json
frontend_app_logbook/i18next.scanner/pt/translation.json
frontend_app_logbook/src/component/Logbook.jsx
frontend_app_logbook/src/component/LogbookEntry.jsx
frontend_app_logbook/src/css/index.styl

https://github.com/tracim/tracim/issues/6539

feat(front): reduce the scrolling in logbook with event with long description

---

frontend/src/action-creator.sync.js
frontend/src/container/WorkspaceRecentActivities.jsx
frontend/src/container/withActivity.jsx
frontend/src/reducer/workspaceActivity.js

https://github.com/tracim/tracim/issues/6577

fix(front): prevent setting recent activities from wrong space

---

CHANGELOG.md
backend/setup.cfg
frontend/src/version.json

Prepare release 4.10.0+build_142

---

backend/setup.cfg
frontend/src/version.json

https://github.com/tracim/tracim/issues/6587

doc(release): create 4.10.0+build_143

---

CHANGELOG.md
backend/setup.cfg
frontend/src/version.json

Prepare release 4.10.0 build_144

---

CHANGELOG.md
backend/setup.cfg
frontend/src/version.json

https://github.com/tracim/tracim/issues/6597

Prepare new release 4.11.1

---

CHANGELOG.md
backend/setup.cfg
frontend/src/version.json

Misc: merge 4.11.1 into develop

---

backend/setup.cfg
frontend/src/version.json

https://github.com/tracim/tracim/issues/6607

Prepare release 4.11.1 build_145

---

CHANGELOG.md
backend/setup.cfg
frontend/src/version.json

https://github.com/tracim/tracim/issues/6612

Prepare release 4.11.1 build_146

---

CHANGELOG.md
backend/setup.cfg
frontend/src/version.json

https://github.com/tracim/tracim/issues/6621

Prepare release 4.11.1 build_147

---

CHANGELOG.md
backend/setup.cfg
frontend/src/version.json

https://github.com/tracim/tracim/issues/6626

doc(release): create 4.11.1+build_148 [skip ci]

---

backend/requirements-build.txt
concourse/pipelines/pull-request.yml

fix(ci): set concourse docker image to version for build_148

---

backend/tracim_backend/lib/rich_text_preview/html_preview.py
frontend/dist/assets/branding.sample/rich_text_preview.css

https://github.com/tracim/tracim/issues/6620

fix(back): handle image resize in pdf generated + remove transparency

---

backend/setup.cfg
frontend/src/version.json

Prepare release 4.11.1 build_149

---

frontend_app_kanban/src/component/KanbanCard.jsx
frontend_lib/src/component/HTMLContent/HTMLContent.jsx

fix(front): improve kanban performance

---

CHANGELOG.md
backend/setup.cfg
frontend/src/version.json

https://github.com/tracim/tracim/issues/6638

Prepare release 4.11.1 build_150

---

frontend/dist/assets/branding.sample/rich_text_preview.css
frontend/dist/assets/branding.sample/rich_text_preview.template

https://github.com/tracim/tracim/issues/6643

fix(front): fix line break in code block + fix bg and border color

---

CHANGELOG.md
backend/setup.cfg
frontend/src/version.json

https://github.com/tracim/tracim/issues/6657

Prepare release 4.12.0 build_151

---

CHANGELOG.md
backend/setup.cfg
frontend/src/version.json

Prepare release 4.12.0 build_152

---

backend/setup.cfg
frontend/src/version.json

Prepare release 4.12.0 build_153

---

frontend/src/component/PublicProfile/CustomFormManager.styl
frontend/src/css/Generic.styl
frontend_app_kanban/src/css/index.styl
frontend_app_logbook/src/css/index.styl
frontend_app_workspace_advanced/src/component/SpaceDescription.jsx
frontend_lib/src/component/CardPopup/CardPopup.styl
frontend_lib/src/component/HTMLContent/HTMLContent.styl
frontend_lib/src/component/TinyEditor/TinyEditor.styl

https://github.com/tracim/tracim/issues/6674

fix(front): fix hugerte style

---

backend/setup.cfg
frontend/src/version.json

https://github.com/tracim/tracim/issues/6678

doc(release): create 4.12.0+build_154 [skip ci]

---

frontend_app_kanban/src/component/KanbanColumnHeader.jsx

https://github.com/tracim/tracim/issues/6692

fix(front): add html title to kanban column title

---

backend/tracim_backend/lib/core/url_preview.py

#6691 in some case, url string includes a line return, resulting in HTTP 500 

---

frontend_lib/src/component/TinyEditor/TinyEditor.jsx

https://github.com/tracim/tracim/issues/6698

fix(front): deactivate plugin advlist

---

frontend_app_file/src/component/IfcViewer/IfcViewer.jsx
frontend_app_file/src/component/TextViewerSyntaxHighlight/TextViewerSyntaxHighlight.jsx

https://github.com/tracim/tracim/issues/6694

fix(front): better cleanup of ifc viewer on error

---

tools_docker/Debian_New_Uwsgi/Dockerfile
tools_docker/Debian_Uwsgi/Dockerfile
tools_docker/Debian_Uwsgi_ARM64/Dockerfile

https://github.com/tracim/tracim/issues/6684

fix(docker): set Dockerfile to use node 16 image

---

backend/development.ini.sample
backend/tracim_backend/config.py
backend/tracim_backend/tests/functional/test_frontend.py
backend/tracim_backend/views/frontend.py
docs/administration/installation/using_environment_variables_instead_of_configuration_parameters.md
frontend_lib/src/component/TinyEditor/TinyEditor.jsx
functionnal_tests/cypress/e2e/generic_frontend/operation_tinymce.cy.js
run_dev_backend.sh

https://github.com/tracim/tracim/issues/6688 

fix(back): allow adding new CSP rule without overwriting default CSP

---

frontend_app_file/i18next.scanner/ar/translation.json
frontend_app_file/i18next.scanner/de/translation.json
frontend_app_file/i18next.scanner/en/translation.json
frontend_app_file/i18next.scanner/es/translation.json
frontend_app_file/i18next.scanner/fr/translation.json
frontend_app_file/i18next.scanner/nb_NO/translation.json
frontend_app_file/i18next.scanner/pt/translation.json
frontend_app_file/src/component/FileComponent.jsx
frontend_app_file/src/component/TextViewerSyntaxHighlight/TextViewerSyntaxHighlight.jsx
frontend_app_file/src/component/TextViewerSyntaxHighlight/TextViewerSyntaxHighlight.styl
frontend_app_file/src/component/ViewerSelector.jsx
frontend_app_file/src/container/File.jsx
frontend_lib/src/component/HTMLContent/HTMLContent.jsx
frontend_lib/src/component/HTMLContent/HTMLContent.styl
frontend_lib/src/helper.js
functionnal_tests/cypress/e2e/generic_frontend/operation_tinymce.cy.js

https://github.com/tracim/tracim/issues/6694

Fix/6694  add size limit to text viewer

---

CHANGELOG.md
backend/setup.cfg
frontend/src/version.json

Prepare release 4.12.0+build_156

---

backend/setup.cfg
frontend/src/version.json

Prepare release 4.12.0+build_157

---

backend/setup.cfg

fix(back): fix setup.cfg naming

---

backend/setup.cfg
frontend/src/version.json

Prepare release 4.12.0+build_158
